# -*- coding: utf-8 -*-
"""encoder basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGao9q44jifRmnRze5OyT6liEBLo_oMl
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

# ─────────────────────────────────────────────
# 0.  Device
# ─────────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ─────────────────────────────────────────────
# 1.  Load MNIST dataset
# ─────────────────────────────────────────────
transform = transforms.Compose([
    transforms.ToTensor(),   # → [0, 1], shape (1, 28, 28)
])

train_dataset = datasets.MNIST(root="./data", train=True,  download=True, transform=transform)
test_dataset  = datasets.MNIST(root="./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True,  num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=128, shuffle=False, num_workers=2, pin_memory=True)

print(f"Train samples: {len(train_dataset)} | Test samples: {len(test_dataset)}")


# ─────────────────────────────────────────────
# Weight initialisation helper
# ─────────────────────────────────────────────
def _init_weights(m):
    if isinstance(m, nn.Conv2d):
        nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
        if m.bias is not None:
            nn.init.zeros_(m.bias)
    elif isinstance(m, nn.BatchNorm2d):
        nn.init.ones_(m.weight)
        nn.init.zeros_(m.bias)


# ═══════════════════════════════════════════════════════════════════════
# BASE MODEL  (direct PyTorch equivalent of the Keras tutorial model)
# ═══════════════════════════════════════════════════════════════════════

class BaseAutoencoder(nn.Module):
    """
    Encoder:
        Conv2d(1→32, 3×3, padding=same) + ReLU
        MaxPool2d(2×2)                          → 14×14
        Conv2d(32→64, 3×3, padding=same) + ReLU
        MaxPool2d(2×2)                          → 7×7  (latent space)

    Decoder:
        Conv2d(64→64, 3×3, padding=same) + ReLU
        Upsample(×2)                            → 14×14
        Conv2d(64→32, 3×3, padding=same) + ReLU
        Upsample(×2)                            → 28×28
        Conv2d(32→1,  3×3, padding=same) + Sigmoid
    """

    def __init__(self):
        super().__init__()

        # ── Encoder ──────────────────────────────────────────────────
        self.encoder = nn.Sequential(
            nn.Conv2d(1,  32, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),                            # 28×28 → 14×14

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),                            # 14×14 → 7×7
        )

        # ── Decoder ──────────────────────────────────────────────────
        self.decoder = nn.Sequential(
            nn.Conv2d(64, 64, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Upsample(scale_factor=2, mode="nearest"),   # 7×7  → 14×14

            nn.Conv2d(64, 32, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Upsample(scale_factor=2, mode="nearest"),   # 14×14 → 28×28

            nn.Conv2d(32,  1, kernel_size=3, padding=1),
            nn.Sigmoid(),
        )

        self.apply(_init_weights)

    def forward(self, x):
        return self.decoder(self.encoder(x))


# ═══════════════════════════════════════════════════════════════════════
# IMPROVED MODEL  (Task: more layers → better reconstruction quality)
# ═══════════════════════════════════════════════════════════════════════

class ImprovedAutoencoder(nn.Module):
    """
    Deeper architecture with Batch Normalisation and more conv layers.

    Encoder:
        Conv(1→32)  + BN + ReLU + MaxPool  → 14×14
        Conv(32→64) + BN + ReLU + MaxPool  → 7×7
        Conv(64→128)+ BN + ReLU            → 7×7  (latent — richer representation)

    Decoder:
        Conv(128→64)+ BN + ReLU + Upsample → 14×14
        Conv(64→32) + BN + ReLU + Upsample → 28×28
        Conv(32→16) + BN + ReLU
        Conv(16→1)  + Sigmoid
    """

    def __init__(self):
        super().__init__()

        # ── Encoder ──────────────────────────────────────────────────
        self.encoder = nn.Sequential(
            nn.Conv2d(1,   32,  3, padding=1, bias=False),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),                             # → 14×14

            nn.Conv2d(32,  64,  3, padding=1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),                             # → 7×7

            nn.Conv2d(64,  128, 3, padding=1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),                          # 7×7 latent
        )

        # ── Decoder ──────────────────────────────────────────────────
        self.decoder = nn.Sequential(
            nn.Conv2d(128, 64, 3, padding=1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.Upsample(scale_factor=2, mode="bilinear", align_corners=False),  # → 14×14

            nn.Conv2d(64,  32, 3, padding=1, bias=False),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.Upsample(scale_factor=2, mode="bilinear", align_corners=False),  # → 28×28

            nn.Conv2d(32,  16, 3, padding=1, bias=False),
            nn.BatchNorm2d(16),
            nn.ReLU(inplace=True),

            nn.Conv2d(16,   1, 3, padding=1),
            nn.Sigmoid(),
        )

        self.apply(_init_weights)

    def forward(self, x):
        return self.decoder(self.encoder(x))


# ─────────────────────────────────────────────
# 2.  Training & evaluation
# ─────────────────────────────────────────────

def train(model, loader, optimizer, criterion, epoch):
    model.train()
    total_loss = 0.0
    for images, _ in loader:
        images = images.to(device)
        optimizer.zero_grad()
        recon  = model(images)
        loss   = criterion(recon, images)   # clean → clean reconstruction
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    avg = total_loss / len(loader)
    print(f"Epoch [{epoch:3d}]  Train Loss: {avg:.5f}")
    return avg


def evaluate(model, loader, criterion):
    model.eval()
    total_loss = 0.0
    with torch.no_grad():
        for images, _ in loader:
            images = images.to(device)
            recon  = model(images)
            total_loss += criterion(recon, images).item()
    return total_loss / len(loader)


# ─────────────────────────────────────────────
# 3.  Visualize original vs reconstructed
# ─────────────────────────────────────────────

def visualize(model, loader, title="Results", n=10):
    model.eval()
    images, _ = next(iter(loader))
    images = images[:n].to(device)

    with torch.no_grad():
        recon = model(images)

    images_np = images.cpu().numpy()
    recon_np  = recon.cpu().numpy()

    fig, axes = plt.subplots(2, n, figsize=(20, 4))
    fig.suptitle(title, fontsize=14)
    for i in range(n):
        axes[0, i].imshow(images_np[i, 0], cmap="gray")
        axes[0, i].set_title("Original",      fontsize=8)
        axes[0, i].axis("off")

        axes[1, i].imshow(recon_np[i, 0], cmap="gray")
        axes[1, i].set_title("Reconstructed", fontsize=8)
        axes[1, i].axis("off")

    plt.tight_layout()
    plt.savefig(f"{title.replace(' ', '_')}.png", dpi=150, bbox_inches="tight")
    plt.show()
    print(f"Saved → {title.replace(' ', '_')}.png")


# ─────────────────────────────────────────────
# 4.  Run everything
# ─────────────────────────────────────────────

if __name__ == "__main__":

    EPOCHS   = 50
    LR       = 1e-3
    criterion = nn.MSELoss()

    # ══════════════════════════════════════════
    # BASE MODEL
    # ══════════════════════════════════════════
    print("\n" + "═" * 50)
    print("  Training BASE autoencoder")
    print("═" * 50)

    base_model = BaseAutoencoder().to(device)
    base_optim = optim.Adam(base_model.parameters(), lr=LR)

    base_train_losses, base_val_losses = [], []
    for epoch in range(1, EPOCHS + 1):
        tl = train(base_model, train_loader, base_optim, criterion, epoch)
        vl = evaluate(base_model, test_loader, criterion)
        base_train_losses.append(tl)
        base_val_losses.append(vl)
        print(f"           Val  Loss: {vl:.5f}")

    visualize(base_model, test_loader, title="Base Autoencoder")

    # ══════════════════════════════════════════
    # IMPROVED MODEL
    # ══════════════════════════════════════════
    print("\n" + "═" * 50)
    print("  Training IMPROVED autoencoder")
    print("═" * 50)

    imp_model = ImprovedAutoencoder().to(device)
    imp_optim = optim.Adam(imp_model.parameters(), lr=LR)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        imp_optim, mode="min", factor=0.5, patience=5
    )

    imp_train_losses, imp_val_losses = [], []
    for epoch in range(1, EPOCHS + 1):
        tl = train(imp_model, train_loader, imp_optim, criterion, epoch)
        vl = evaluate(imp_model, test_loader, criterion)
        scheduler.step(vl)
        imp_train_losses.append(tl)
        imp_val_losses.append(vl)
        print(f"           Val  Loss: {vl:.5f}")

    visualize(imp_model, test_loader, title="Improved Autoencoder")

    # ── Training curves ───────────────────────
    fig1, ax1 = plt.subplots(figsize=(8, 4))
    ax1.plot(base_train_losses, label="Base train")
    ax1.plot(base_val_losses,   label="Base val")
    ax1.plot(imp_train_losses,  label="Improved train", linestyle="--")
    ax1.plot(imp_val_losses,    label="Improved val",   linestyle="--")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("MSE Loss")
    ax1.set_title("Training curves")
    ax1.legend()
    fig1.tight_layout()
    fig1.savefig("Training_curves.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("Saved → Training_curves.png")

    # ── Side-by-side comparison (3 rows: original / base / improved) ──
    base_model.eval(); imp_model.eval()
    imgs, _ = next(iter(test_loader))
    imgs = imgs[:5].to(device)
    with torch.no_grad():
        base_recon = base_model(imgs).cpu().numpy()
        imp_recon  = imp_model(imgs).cpu().numpy()
    imgs_np = imgs.cpu().numpy()

    fig2, axes2 = plt.subplots(3, 5, figsize=(14, 7))
    row_labels = ["Original", "Base recon", "Improved recon"]
    rows       = [imgs_np, base_recon, imp_recon]
    for r, (row, label) in enumerate(zip(rows, row_labels)):
        for c in range(5):
            axes2[r, c].imshow(row[c, 0], cmap="gray")
            axes2[r, c].axis("off")
        axes2[r, 0].set_ylabel(label, fontsize=10, rotation=0,
                                labelpad=90, va="center")
    fig2.suptitle("Base vs Improved Reconstruction Quality", fontsize=13)
    fig2.tight_layout()
    fig2.savefig("Comparison.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("Saved → Comparison.png")

    # ── Parameter counts ─────────────────────
    def count_params(m):
        return sum(p.numel() for p in m.parameters() if p.requires_grad)

    print(f"\nBase model params:     {count_params(base_model):,}")
    print(f"Improved model params: {count_params(imp_model):,}")