# -*- coding: utf-8 -*-
"""deep autoencoderc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123U-aaYXpCIx6f4CKG0BSppo8gRGyaiX
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

# ── Device ──────────────────────────────────────
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ── Load Dataset ────────────────────────────────
transform     = transforms.ToTensor()
train_dataset = datasets.MNIST(root='./data', train=True,  transform=transform, download=True)
test_dataset  = datasets.MNIST(root='./data', train=False, transform=transform, download=True)
train_loader  = DataLoader(train_dataset, batch_size=128, shuffle=True)
test_loader   = DataLoader(test_dataset,  batch_size=128, shuffle=False)

# ── Add Noise ───────────────────────────────────
def add_noise(images, noise_factor=0.5):
    """Add Gaussian noise to a batch of images."""
    noisy_images = images + noise_factor * torch.randn_like(images)
    noisy_images = torch.clamp(noisy_images, 0., 1.)
    return noisy_images

# ── Build Denoising Autoencoder ─────────────────
class DenoisingAutoencoder(nn.Module):
    def __init__(self):
        super().__init__()

        # Encoder
        self.encoder = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),   # 32x28x28
            nn.ReLU(),
            nn.MaxPool2d(2, 2),                            # 32x14x14
            nn.Conv2d(32, 64, kernel_size=3, padding=1),  # 64x14x14
            nn.ReLU(),
            nn.MaxPool2d(2, 2)                             # 64x7x7
        )

        # Decoder
        self.decoder = nn.Sequential(
            nn.Conv2d(64, 64, kernel_size=3, padding=1),  # 64x7x7
            nn.ReLU(),
            nn.Upsample(scale_factor=2),                   # 64x14x14
            nn.Conv2d(64, 32, kernel_size=3, padding=1),  # 32x14x14
            nn.ReLU(),
            nn.Upsample(scale_factor=2),                   # 32x28x28
            nn.Conv2d(32, 1,  kernel_size=3, padding=1),  # 1x28x28
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.decoder(self.encoder(x))

model     = DenoisingAutoencoder().to(device)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)
print(model)

# ── Train ───────────────────────────────────────
num_epochs   = 10
train_losses = []
val_losses   = []

for epoch in range(num_epochs):
    model.train()
    train_loss = 0.0
    for imgs, _ in train_loader:
        imgs       = imgs.to(device)
        noisy_imgs = add_noise(imgs).to(device)
        outputs    = model(noisy_imgs)
        loss       = criterion(outputs, imgs)
        optimizer.zero_grad(); loss.backward(); optimizer.step()
        train_loss += loss.item() * imgs.size(0)

    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for imgs, _ in test_loader:
            imgs       = imgs.to(device)
            noisy_imgs = add_noise(imgs).to(device)
            outputs    = model(noisy_imgs)
            val_loss  += criterion(outputs, imgs).item() * imgs.size(0)

    avg_train = train_loss / len(train_dataset)
    avg_val   = val_loss   / len(test_dataset)
    train_losses.append(avg_train)
    val_losses.append(avg_val)
    print(f"Epoch [{epoch+1}/{num_epochs}]  Train Loss: {avg_train:.4f}  Val Loss: {avg_val:.4f}")

# ── Loss Curve ──────────────────────────────────
plt.figure(figsize=(8, 4))
plt.plot(range(1, num_epochs+1), train_losses, label='Train Loss', color='steelblue')
plt.plot(range(1, num_epochs+1), val_losses,   label='Val Loss',   color='tomato', linestyle='--')
plt.xlabel('Epoch'); plt.ylabel('BCE Loss')
plt.title('Denoising Autoencoder - Train vs Val Loss')
plt.legend(); plt.tight_layout()
plt.savefig('dae_loss_curve.png', dpi=150)
plt.show()

# ── Visualize Results ───────────────────────────
model.eval()
sample_imgs, _ = next(iter(test_loader))
sample_imgs    = sample_imgs[:10].to(device)
noisy_imgs     = add_noise(sample_imgs)

with torch.no_grad():
    decoded_imgs = model(noisy_imgs)

n = 10
fig, axes = plt.subplots(2, n, figsize=(20, 4))
for i in range(n):
    axes[0, i].imshow(noisy_imgs[i].cpu().squeeze(), cmap='gray'); axes[0, i].axis('off')
    axes[1, i].imshow(decoded_imgs[i].cpu().squeeze(), cmap='gray'); axes[1, i].axis('off')
axes[0, 0].set_title('Noisy')
axes[1, 0].set_title('Reconstructed')
plt.suptitle('Denoising Autoencoder - Reconstruction Results', fontsize=12)
plt.tight_layout()
plt.savefig('dae_reconstruction.png', dpi=150)
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

# ── Device ──────────────────────────────────────
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ── Load Dataset ────────────────────────────────
transform     = transforms.ToTensor()
train_dataset = datasets.MNIST(root='./data', train=True,  transform=transform, download=True)
test_dataset  = datasets.MNIST(root='./data', train=False, transform=transform, download=True)

train_loader  = DataLoader(train_dataset, batch_size=128, shuffle=True)
test_loader   = DataLoader(test_dataset,  batch_size=128, shuffle=False)

# ── Add Noise Function ──────────────────────────
def add_noise(images, noise_factor=0.4):
    noise = torch.randn_like(images) * noise_factor
    noisy_images = images + noise
    return torch.clamp(noisy_images, 0., 1.)

# ── Deep Denoising Autoencoder ──────────────────
class DeepAutoencoder(nn.Module):
    def __init__(self):
        super().__init__()

        # Encoder
        self.encoder = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1),
            nn.BatchNorm2d(32), nn.ReLU(),
            nn.Conv2d(32, 32, 3, padding=1),
            nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2),                  # 14x14

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64), nn.ReLU(),
            nn.Conv2d(64, 64, 3, padding=1),
            nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2),                  # 7x7

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128), nn.ReLU(),
            nn.Conv2d(128, 128, 3, padding=1),
            nn.BatchNorm2d(128), nn.ReLU(),
            nn.MaxPool2d(2, padding=1)        # 4x4
        )

        # Decoder
        self.decoder = nn.Sequential(
            nn.Conv2d(128, 128, 3, padding=1),
            nn.BatchNorm2d(128), nn.ReLU(),
            nn.Upsample(size=(7, 7)),

            nn.Conv2d(128, 64, 3, padding=1),
            nn.BatchNorm2d(64), nn.ReLU(),
            nn.Conv2d(64, 64, 3, padding=1),
            nn.BatchNorm2d(64), nn.ReLU(),
            nn.Upsample(scale_factor=2),      # 14x14

            nn.Conv2d(64, 32, 3, padding=1),
            nn.BatchNorm2d(32), nn.ReLU(),
            nn.Conv2d(32, 32, 3, padding=1),
            nn.BatchNorm2d(32), nn.ReLU(),
            nn.Upsample(scale_factor=2),      # 28x28

            nn.Conv2d(32, 1, 3, padding=1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.decoder(self.encoder(x))

# ── Model Setup ─────────────────────────────────
model     = DeepAutoencoder().to(device)
criterion = nn.MSELoss()   # better for images
optimizer = optim.Adam(model.parameters(), lr=1e-3)

print(model)

# ── Training ────────────────────────────────────
num_epochs   = 10
train_losses = []
val_losses   = []

for epoch in range(num_epochs):
    model.train()
    train_loss = 0.0

    for imgs, _ in train_loader:
        imgs = imgs.to(device)

        # 🔥 Add noise
        noisy_imgs = add_noise(imgs)

        # Forward
        recon = model(noisy_imgs)
        loss  = criterion(recon, imgs)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item() * imgs.size(0)

    # Validation
    model.eval()
    val_loss = 0.0

    with torch.no_grad():
        for imgs, _ in test_loader:
            imgs = imgs.to(device)
            noisy_imgs = add_noise(imgs)

            recon = model(noisy_imgs)
            val_loss += criterion(recon, imgs).item() * imgs.size(0)

    avg_train = train_loss / len(train_dataset)
    avg_val   = val_loss   / len(test_dataset)

    train_losses.append(avg_train)
    val_losses.append(avg_val)

    print(f"Epoch [{epoch+1}/{num_epochs}]  Train Loss: {avg_train:.4f}  Val Loss: {avg_val:.4f}")

# ── Loss Curve ──────────────────────────────────
plt.figure(figsize=(8, 4))
plt.plot(range(1, num_epochs+1), train_losses, label='Train Loss')
plt.plot(range(1, num_epochs+1), val_losses, label='Val Loss', linestyle='--')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Deep Denoising Autoencoder Loss')
plt.legend()
plt.tight_layout()
plt.show()

# ── Visualization ───────────────────────────────
model.eval()
sample_imgs, _ = next(iter(test_loader))
sample_imgs = sample_imgs[:10].to(device)

noisy_imgs = add_noise(sample_imgs)

with torch.no_grad():
    reconstructed = model(noisy_imgs)

fig, axes = plt.subplots(3, 10, figsize=(20, 6))

for i in range(10):
    # Original
    axes[0, i].imshow(sample_imgs[i].cpu().squeeze(), cmap='gray')
    axes[0, i].axis('off')

    # Noisy
    axes[1, i].imshow(noisy_imgs[i].cpu().squeeze(), cmap='gray')
    axes[1, i].axis('off')

    # Reconstructed
    axes[2, i].imshow(reconstructed[i].cpu().squeeze(), cmap='gray')
    axes[2, i].axis('off')

axes[0, 0].set_title('Original')
axes[1, 0].set_title('Noisy')
axes[2, 0].set_title('Denoised')

plt.tight_layout()
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

# ── Device ──────────────────────────────────────
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ── Load Dataset ────────────────────────────────
transform     = transforms.ToTensor()
train_dataset = datasets.MNIST(root='./data', train=True,  transform=transform, download=True)
test_dataset  = datasets.MNIST(root='./data', train=False, transform=transform, download=True)
train_loader  = DataLoader(train_dataset, batch_size=128, shuffle=True)
test_loader   = DataLoader(test_dataset,  batch_size=128, shuffle=False)

# ── VAE Architecture ─────────────────────────────
class VAE(nn.Module):
    def __init__(self, latent_dim=16):
        super().__init__()
        self.latent_dim = latent_dim

        # ── Encoder ──────────────────────────────
        # Input: 1x28x28
        self.enc_conv = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),   # 32x28x28
            nn.ReLU(),
            nn.MaxPool2d(2, 2),                            # 32x14x14
            nn.Conv2d(32, 64, kernel_size=3, padding=1),  # 64x14x14
            nn.ReLU(),
            nn.MaxPool2d(2, 2),                            # 64x7x7
            nn.Conv2d(64, 128, kernel_size=3, padding=1), # 128x7x7
            nn.ReLU(),
        )
        self.flatten_dim = 128 * 7 * 7  # = 6272

        # Project to mean and log-variance of the latent distribution
        self.fc_mu     = nn.Linear(self.flatten_dim, latent_dim)
        self.fc_logvar = nn.Linear(self.flatten_dim, latent_dim)

        # ── Decoder ──────────────────────────────
        self.fc_decode = nn.Linear(latent_dim, self.flatten_dim)

        self.dec_conv = nn.Sequential(
            nn.Conv2d(128, 64, kernel_size=3, padding=1), # 64x7x7
            nn.ReLU(),
            nn.Upsample(scale_factor=2),                   # 64x14x14
            nn.Conv2d(64, 32, kernel_size=3, padding=1),  # 32x14x14
            nn.ReLU(),
            nn.Upsample(scale_factor=2),                   # 32x28x28
            nn.Conv2d(32, 1,  kernel_size=3, padding=1),  # 1x28x28
            nn.Sigmoid()
        )

    def encode(self, x):
        """Encode input image to latent parameters (mu, logvar)."""
        h = self.enc_conv(x)
        h = h.view(h.size(0), -1)          # Flatten
        mu     = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        return mu, logvar

    def reparameterize(self, mu, logvar):
        """
        Reparameterization trick:
        z = mu + eps * std,  where eps ~ N(0, I)
        This allows gradients to flow through the sampling step.
        """
        if self.training:
            std = torch.exp(0.5 * logvar)   # std deviation
            eps = torch.randn_like(std)      # random noise
            return mu + eps * std
        else:
            return mu  # Use mean directly at inference

    def decode(self, z):
        """Decode latent vector back to image space."""
        h = self.fc_decode(z)
        h = h.view(h.size(0), 128, 7, 7)  # Reshape to feature map
        return self.dec_conv(h)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z          = self.reparameterize(mu, logvar)
        recon      = self.decode(z)
        return recon, mu, logvar


# ── VAE Loss Function ────────────────────────────
def vae_loss(recon_x, x, mu, logvar):
    """
    VAE loss = Reconstruction loss + KL Divergence

    - Reconstruction loss (BCE): measures how well the decoder
      reconstructs the original image from the latent vector.
    - KL Divergence: regularizes the latent space to be close
      to a standard normal distribution N(0, I).
      KLD = -0.5 * sum(1 + logvar - mu^2 - exp(logvar))
    """
    bce = F.binary_cross_entropy(recon_x, x, reduction='sum')
    kld = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return bce + kld


# ── Instantiate Model ────────────────────────────
latent_dim = 16
model      = VAE(latent_dim=latent_dim).to(device)
optimizer  = optim.Adam(model.parameters(), lr=1e-3)
print(model)
print(f"\nLatent Dimension: {latent_dim}")
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total Trainable Parameters: {total_params:,}")


# ── Train ────────────────────────────────────────
num_epochs   = 10
train_losses = []
val_losses   = []

for epoch in range(num_epochs):
    # Training phase
    model.train()
    train_loss = 0.0
    for imgs, _ in train_loader:
        imgs              = imgs.to(device)
        recon, mu, logvar = model(imgs)
        loss              = vae_loss(recon, imgs, mu, logvar)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

    # Validation phase
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for imgs, _ in test_loader:
            imgs              = imgs.to(device)
            recon, mu, logvar = model(imgs)
            val_loss         += vae_loss(recon, imgs, mu, logvar).item()

    # Normalize by dataset size for comparability
    avg_train = train_loss / len(train_dataset)
    avg_val   = val_loss   / len(test_dataset)
    train_losses.append(avg_train)
    val_losses.append(avg_val)
    print(f"Epoch [{epoch+1}/{num_epochs}]  Train Loss: {avg_train:.4f}  Val Loss: {avg_val:.4f}")


# ── Loss Curve ───────────────────────────────────
plt.figure(figsize=(8, 4))
plt.plot(range(1, num_epochs+1), train_losses, label='Train Loss', color='steelblue')
plt.plot(range(1, num_epochs+1), val_losses,   label='Val Loss',   color='tomato', linestyle='--')
plt.xlabel('Epoch')
plt.ylabel('VAE Loss (BCE + KLD)')
plt.title('Variational Autoencoder - Train vs Val Loss')
plt.legend()
plt.tight_layout()
plt.savefig('vae_loss_curve.png', dpi=150)
plt.show()


# ── Visualize Reconstruction ─────────────────────
model.eval()
sample_imgs, _ = next(iter(test_loader))
sample_imgs    = sample_imgs[:10].to(device)

with torch.no_grad():
    recon_imgs, _, _ = model(sample_imgs)

n = 10
fig, axes = plt.subplots(2, n, figsize=(20, 4))
for i in range(n):
    axes[0, i].imshow(sample_imgs[i].cpu().squeeze(), cmap='gray')
    axes[0, i].axis('off')
    axes[1, i].imshow(recon_imgs[i].cpu().squeeze(), cmap='gray')
    axes[1, i].axis('off')
axes[0, 0].set_title('Original')
axes[1, 0].set_title('Reconstructed')
plt.suptitle('VAE - Reconstruction Results', fontsize=12)
plt.tight_layout()
plt.savefig('vae_reconstruction.png', dpi=150)
plt.show()


# ── Visualize Generated Samples ──────────────────
# Sample random latent vectors from N(0, I) and decode them
model.eval()
with torch.no_grad():
    z = torch.randn(10, latent_dim).to(device)
    generated = model.decode(z)

fig, axes = plt.subplots(1, 10, figsize=(20, 2))
for i in range(10):
    axes[i].imshow(generated[i].cpu().squeeze(), cmap='gray')
    axes[i].axis('off')
plt.suptitle('VAE - Randomly Generated Digits (from N(0,I))', fontsize=12)
plt.tight_layout()
plt.savefig('vae_generated.png', dpi=150)
plt.show()


# ── Latent Space Interpolation ───────────────────
# Encode two test images and interpolate between their latent vectors
model.eval()
imgs_pair, labels_pair = next(iter(test_loader))

# Pick two different digit images
img_a = imgs_pair[0:1].to(device)
img_b = imgs_pair[1:2].to(device)

with torch.no_grad():
    mu_a, _ = model.encode(img_a)
    mu_b, _ = model.encode(img_b)

steps = 10
alphas = torch.linspace(0, 1, steps)
interpolated = []
with torch.no_grad():
    for alpha in alphas:
        z_interp = (1 - alpha) * mu_a + alpha * mu_b
        out = model.decode(z_interp)
        interpolated.append(out.cpu().squeeze())

fig, axes = plt.subplots(1, steps, figsize=(20, 2))
for i, img in enumerate(interpolated):
    axes[i].imshow(img, cmap='gray')
    axes[i].axis('off')
    axes[i].set_title(f'{alphas[i]:.1f}', fontsize=8)
plt.suptitle('VAE - Latent Space Interpolation (Image A → Image B)', fontsize=12)
plt.tight_layout()
plt.savefig('vae_interpolation.png', dpi=150)
plt.show()

print("\nAll plots saved: vae_loss_curve.png, vae_reconstruction.png, vae_generated.png, vae_interpolation.png")