# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ogHBX2EIIAfrgYW1YePqHReM7GKr13bA
"""

# ============================================================
# CODE 1 — SIMPLE ARCHITECTURE (Baseline)
# ============================================================

import torch
import torch.nn as nn
import matplotlib.pyplot as plt

sentences = [
    "Barack Obama was born in Hawaii",
    "Google is based in Mountain View",
    "Elon Musk founded SpaceX in California",
    "Paris is the capital of France",
    "Barack Obama visited Paris last year",
    "Elon Musk traveled to France recently",
    "Apple is located in California",
    "Obama flew to Mountain View",
    "SpaceX launched a rocket in California",
    "Michelle Obama was born in Chicago",
    "Microsoft is headquartered in Seattle",
    "Jeff Bezos founded Amazon in Seattle",
    "London is a city in England",
    "Tesla is based in Austin",
    "Elon Musk moved to Texas recently",
]

labels = [
    ["PERSON",       "PERSON", "O", "O",            "O",        "LOCATION"],
    ["ORGANIZATION", "O",      "O", "O",            "LOCATION", "O"],
    ["PERSON",       "PERSON", "O", "ORGANIZATION", "O",        "LOCATION"],
    ["LOCATION",     "O",      "O", "O",            "O",        "LOCATION"],
    ["PERSON",       "PERSON", "O", "LOCATION",     "O",        "O"],
    ["PERSON",       "PERSON", "O", "O",            "LOCATION", "O"],
    ["ORGANIZATION", "O",      "O", "O",            "LOCATION"],
    ["PERSON",       "O",      "O", "LOCATION",     "O"],
    ["ORGANIZATION", "O",      "O", "O",            "O",        "LOCATION"],
    ["PERSON",       "PERSON", "O", "O",            "O",        "LOCATION"],
    ["ORGANIZATION", "O",      "O", "O",            "LOCATION"],
    ["PERSON",       "PERSON", "O", "ORGANIZATION", "O",        "LOCATION"],
    ["LOCATION",     "O",      "O", "O",            "O",        "LOCATION"],
    ["ORGANIZATION", "O",      "O", "O",            "LOCATION"],
    ["PERSON",       "PERSON", "O", "O",            "LOCATION", "O"],
]

test_sentences = [
    "Barack Obama visited Paris",
    "Elon Musk lives in California",
    "Jeff Bezos moved to Seattle",
]

# ── Vocabulary ───────────────────────────────────────────────
all_words  = set(w for s in sentences for w in s.split())
all_labels = set(l for ls in labels for l in ls)

word_to_idx  = {"<PAD>": 0, "<UNK>": 1}
label_to_idx = {"<PAD>": 0}
for w in sorted(all_words):  word_to_idx[w]  = len(word_to_idx)
for l in sorted(all_labels): label_to_idx[l] = len(label_to_idx)
idx_to_label = {v: k for k, v in label_to_idx.items()}

def encode_sentence(s):
    return [word_to_idx.get(w, 1) for w in s.split()]
def encode_labels(ls):
    return [label_to_idx[l] for l in ls]
def pad(seq, length, val=0):
    return seq + [val] * (length - len(seq))

max_len = max(len(s.split()) for s in sentences)
X = torch.tensor([pad(encode_sentence(s), max_len) for s in sentences], dtype=torch.long)
y = torch.tensor([pad(encode_labels(l),   max_len) for l in labels],    dtype=torch.long)

# ── Simple Model ─────────────────────────────────────────────
class SimpleNER(nn.Module):
    def __init__(self, vocab_size, num_labels):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim=16, padding_idx=0)
        self.rnn       = nn.RNN(input_size=16, hidden_size=32, batch_first=True)
        self.fc        = nn.Linear(32, num_labels)

    def forward(self, x):
        out, _ = self.rnn(self.embedding(x))
        return self.fc(out)

VOCAB_SIZE    = len(word_to_idx)
NUM_LABELS    = len(label_to_idx)
LEARNING_RATE = 0.01
EPOCHS        = 30

model     = SimpleNER(VOCAB_SIZE, NUM_LABELS)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
loss_fn   = nn.CrossEntropyLoss(ignore_index=0)

print("=== CODE 1 — SIMPLE ARCHITECTURE ===")
print(f"Embed: 16 | Hidden: 32 | LR: {LEARNING_RATE} | Epochs: {EPOCHS}\n")

# ── Training — record every epoch ────────────────────────────
history_loss = []
history_acc  = []

model.train()
for epoch in range(1, EPOCHS + 1):
    optimizer.zero_grad()
    logits = model(X)
    loss   = loss_fn(logits.view(-1, NUM_LABELS), y.view(-1))
    loss.backward()
    optimizer.step()

    preds   = torch.argmax(logits, dim=-1)
    mask    = y != 0
    acc     = 100.0 * (preds == y)[mask].sum().item() / mask.sum().item()

    history_loss.append(loss.item())
    history_acc.append(acc)

    if epoch % 10 == 0:
        print(f"Epoch {epoch:3d}/{EPOCHS} | Loss: {loss.item():.4f} | Accuracy: {acc:.1f}%")

# ── Training Curve ───────────────────────────────────────────
epochs_range = range(1, EPOCHS + 1)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle("Code 1 — Simple Architecture Training Curve", fontsize=13, fontweight='bold')

ax1.plot(epochs_range, history_loss, color='steelblue', linewidth=2)
ax1.set_title("Loss per Epoch")
ax1.set_xlabel("Epoch")
ax1.set_ylabel("Loss")
ax1.grid(True, alpha=0.3)

ax2.plot(epochs_range, history_acc, color='darkorange', linewidth=2)
ax2.set_title("Accuracy per Epoch")
ax2.set_xlabel("Epoch")
ax2.set_ylabel("Accuracy (%)")
ax2.set_ylim(0, 105)
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("code1_training_curve.png", dpi=150, bbox_inches='tight')
plt.show()
print("\nCurve saved: code1_training_curve.png")

# ── Test Predictions ─────────────────────────────────────────
print("\n--- Test Predictions ---")
model.eval()
with torch.no_grad():
    for sentence in test_sentences:
        words  = sentence.split()
        tensor = torch.tensor([pad(encode_sentence(sentence), max_len)], dtype=torch.long)
        logits = model(tensor)
        preds  = torch.argmax(logits, dim=-1)[0]
        probs  = torch.softmax(logits[0], dim=-1)
        print(f"\n'{sentence}'")
        print(f"  {'Word':<20} {'Label':<16} Confidence")
        print(f"  {'-'*45}")
        for i, (w, idx) in enumerate(zip(words, preds[:len(words)])):
            label = idx_to_label[idx.item()]
            conf  = probs[i][idx.item()].item() * 100
            print(f"  {w:<20} {label:<16} {conf:.1f}%")

# ============================================================
# CODE 2 — LARGE HYPERPARAMETERS (Tuned)
# ============================================================

import torch
import torch.nn as nn
import matplotlib.pyplot as plt

sentences = [
    "Barack Obama was born in Hawaii",
    "Google is based in Mountain View",
    "Elon Musk founded SpaceX in California",
    "Paris is the capital of France",
    "Barack Obama visited Paris last year",
    "Elon Musk traveled to France recently",
    "Apple is located in California",
    "Obama flew to Mountain View",
    "SpaceX launched a rocket in California",
    "Michelle Obama was born in Chicago",
    "Microsoft is headquartered in Seattle",
    "Jeff Bezos founded Amazon in Seattle",
    "London is a city in England",
    "Tesla is based in Austin",
    "Elon Musk moved to Texas recently",
]

labels = [
    ["PERSON",       "PERSON", "O", "O",            "O",        "LOCATION"],
    ["ORGANIZATION", "O",      "O", "O",            "LOCATION", "O"],
    ["PERSON",       "PERSON", "O", "ORGANIZATION", "O",        "LOCATION"],
    ["LOCATION",     "O",      "O", "O",            "O",        "LOCATION"],
    ["PERSON",       "PERSON", "O", "LOCATION",     "O",        "O"],
    ["PERSON",       "PERSON", "O", "O",            "LOCATION", "O"],
    ["ORGANIZATION", "O",      "O", "O",            "LOCATION"],
    ["PERSON",       "O",      "O", "LOCATION",     "O"],
    ["ORGANIZATION", "O",      "O", "O",            "O",        "LOCATION"],
    ["PERSON",       "PERSON", "O", "O",            "O",        "LOCATION"],
    ["ORGANIZATION", "O",      "O", "O",            "LOCATION"],
    ["PERSON",       "PERSON", "O", "ORGANIZATION", "O",        "LOCATION"],
    ["LOCATION",     "O",      "O", "O",            "O",        "LOCATION"],
    ["ORGANIZATION", "O",      "O", "O",            "LOCATION"],
    ["PERSON",       "PERSON", "O", "O",            "LOCATION", "O"],
]

test_sentences = [
    "Barack Obama visited Paris",
    "Elon Musk lives in California",
    "Jeff Bezos moved to Seattle",
]

# ── Vocabulary ───────────────────────────────────────────────
all_words  = set(w for s in sentences for w in s.split())
all_labels = set(l for ls in labels for l in ls)

word_to_idx  = {"<PAD>": 0, "<UNK>": 1}
label_to_idx = {"<PAD>": 0}
for w in sorted(all_words):  word_to_idx[w]  = len(word_to_idx)
for l in sorted(all_labels): label_to_idx[l] = len(label_to_idx)
idx_to_label = {v: k for k, v in label_to_idx.items()}

def encode_sentence(s):
    return [word_to_idx.get(w, 1) for w in s.split()]
def encode_labels(ls):
    return [label_to_idx[l] for l in ls]
def pad(seq, length, val=0):
    return seq + [val] * (length - len(seq))

max_len = max(len(s.split()) for s in sentences)
X = torch.tensor([pad(encode_sentence(s), max_len) for s in sentences], dtype=torch.long)
y = torch.tensor([pad(encode_labels(l),   max_len) for l in labels],    dtype=torch.long)

# ── Larger Model ─────────────────────────────────────────────
class TunedNER(nn.Module):
    def __init__(self, vocab_size, num_labels):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim=64, padding_idx=0)
        self.rnn       = nn.RNN(input_size=64, hidden_size=256, batch_first=True)
        self.dropout   = nn.Dropout(0.3)
        self.fc        = nn.Linear(256, num_labels)

    def forward(self, x):
        out, _ = self.rnn(self.embedding(x))
        return self.fc(self.dropout(out))

VOCAB_SIZE    = len(word_to_idx)
NUM_LABELS    = len(label_to_idx)
LEARNING_RATE = 0.001
EPOCHS        = 150

model     = TunedNER(VOCAB_SIZE, NUM_LABELS)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
loss_fn   = nn.CrossEntropyLoss(ignore_index=0)

print("=== CODE 2 — LARGE HYPERPARAMETERS ===")
print(f"Embed: 64 | Hidden: 256 | LR: {LEARNING_RATE} | Epochs: {EPOCHS}\n")

# ── Training — record every epoch ────────────────────────────
history_loss = []
history_acc  = []

model.train()
for epoch in range(1, EPOCHS + 1):
    optimizer.zero_grad()
    logits = model(X)
    loss   = loss_fn(logits.view(-1, NUM_LABELS), y.view(-1))
    loss.backward()
    optimizer.step()

    preds   = torch.argmax(logits, dim=-1)
    mask    = y != 0
    acc     = 100.0 * (preds == y)[mask].sum().item() / mask.sum().item()

    history_loss.append(loss.item())
    history_acc.append(acc)

    if epoch % 30 == 0:
        print(f"Epoch {epoch:3d}/{EPOCHS} | Loss: {loss.item():.4f} | Accuracy: {acc:.1f}%")

# ── Training Curve ───────────────────────────────────────────
epochs_range = range(1, EPOCHS + 1)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle("Code 2 — Large Hyperparameters Training Curve", fontsize=13, fontweight='bold')

ax1.plot(epochs_range, history_loss, color='steelblue', linewidth=2)
ax1.set_title("Loss per Epoch")
ax1.set_xlabel("Epoch")
ax1.set_ylabel("Loss")
ax1.grid(True, alpha=0.3)

ax2.plot(epochs_range, history_acc, color='darkorange', linewidth=2)
ax2.set_title("Accuracy per Epoch")
ax2.set_xlabel("Epoch")
ax2.set_ylabel("Accuracy (%)")
ax2.set_ylim(0, 105)
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("code2_training_curve.png", dpi=150, bbox_inches='tight')
plt.show()
print("\nCurve saved: code2_training_curve.png")

# ── Test Predictions ─────────────────────────────────────────
print("\n--- Test Predictions ---")
model.eval()
with torch.no_grad():
    for sentence in test_sentences:
        words  = sentence.split()
        tensor = torch.tensor([pad(encode_sentence(sentence), max_len)], dtype=torch.long)
        logits = model(tensor)
        preds  = torch.argmax(logits, dim=-1)[0]
        probs  = torch.softmax(logits[0], dim=-1)
        print(f"\n'{sentence}'")
        print(f"  {'Word':<20} {'Label':<16} Confidence")
        print(f"  {'-'*45}")
        for i, (w, idx) in enumerate(zip(words, preds[:len(words)])):
            label = idx_to_label[idx.item()]
            conf  = probs[i][idx.item()].item() * 100
            print(f"  {w:<20} {label:<16} {conf:.1f}%")