# -*- coding: utf-8 -*-
"""IMAGE SEGMENTATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YHvDY7aXVWcXc2ync26hXKjsNx-IiJp
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="cyGDeK8mgvw7ZFBtmJ9I")
project = rf.workspace("emans-workspace-bczzy").project("guns-vhehj")
version = project.version(1)
dataset = version.download("coco-segmentation")

import os

# Check what folder was created
print("Dataset location:", dataset.location)

# Check folder structure
for split in ["train", "valid", "test"]:
    img_dir = os.path.join(dataset.location, split, "images")
    ann_file = os.path.join(dataset.location, split, "_annotations.coco.json")

    imgs = len(os.listdir(img_dir)) if os.path.exists(img_dir) else 0
    ann  = "✅ Found" if os.path.exists(ann_file) else "❌ Missing"

    print(f"{split}: {imgs} images | Annotation file: {ann}")

# Let's see exact folder structure
import os

for root, dirs, files in os.walk("/content/Guns-1"):
    level = root.replace("/content/Guns-1", "").count(os.sep)
    indent = " " * 2 * level
    print(f"{indent}{os.path.basename(root)}/")
    if level < 3:  # show files only in first 3 levels
        for file in files[:5]:  # show max 5 files per folder
            print(f"{indent}  {file}")

import glob

for split in ["train", "valid", "test"]:
    imgs = glob.glob(f"/content/Guns-1/{split}/*.jpg")
    print(f"{split}: {len(imgs)} images")

import os, glob, json
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import matplotlib.pyplot as plt
import cv2

CONFIG = {
    "dataset_root": "/content/Guns-1",
    "img_size": 128,
    "batch_size": 4,
    "epochs": 20,
    "learning_rate": 1e-4,
    "vis_samples": 3,
    "model_path": "unet_gun.pth",
}

class GunDataset(Dataset):
    def __init__(self, root, split="train", img_size=128):
        self.img_size = img_size
        # ✅ images are directly in split folder, no /images/ subfolder
        self.img_dir  = os.path.join(root, split)
        ann_file      = os.path.join(root, split, "_annotations.coco.json")

        with open(ann_file) as f:
            coco = json.load(f)

        self.id2file = {img["id"]: img["file_name"] for img in coco["images"]}

        self.id2anns = {}
        for ann in coco["annotations"]:
            iid = ann["image_id"]
            self.id2anns.setdefault(iid, []).append(ann)

        self.image_ids = list(self.id2file.keys())
        print(f"  {split}: {len(self.image_ids)} images loaded")

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        iid      = self.image_ids[idx]
        img_path = os.path.join(self.img_dir, self.id2file[iid])

        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        h, w = img.shape[:2]

        # build mask from polygons
        mask = np.zeros((h, w), dtype=np.uint8)
        for ann in self.id2anns.get(iid, []):
            for seg in ann.get("segmentation", []):
                pts = np.array(seg).reshape(-1, 2).astype(np.int32)
                cv2.fillPoly(mask, [pts], 1)

        img  = cv2.resize(img,  (self.img_size, self.img_size))
        mask = cv2.resize(mask, (self.img_size, self.img_size),
                          interpolation=cv2.INTER_NEAREST)

        img  = torch.tensor(img.astype(np.float32) / 255.0).permute(2, 0, 1)
        mask = torch.tensor(mask.astype(np.float32)).unsqueeze(0)
        return img, mask

# ── Model ──────────────────────────────────────────────
class DoubleConv(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
    def forward(self, x): return self.block(x)

class EncoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = DoubleConv(in_ch, out_ch)
        self.pool = nn.MaxPool2d(2)
    def forward(self, x):
        skip = self.conv(x)
        return skip, self.pool(skip)

class DecoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.up   = nn.ConvTranspose2d(in_ch, out_ch, 2, 2)
        self.conv = DoubleConv(out_ch * 2, out_ch)
    def forward(self, x, skip):
        x = self.up(x)
        if x.shape != skip.shape:
            x = nn.functional.interpolate(x, size=skip.shape[2:])
        return self.conv(torch.cat([x, skip], dim=1))

class UNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.enc1       = EncoderBlock(3, 64)
        self.enc2       = EncoderBlock(64, 128)
        self.bottleneck = DoubleConv(128, 256)
        self.dec1       = DecoderBlock(256, 128)
        self.dec2       = DecoderBlock(128, 64)
        self.out        = nn.Conv2d(64, 1, 1)
    def forward(self, x):
        s1, x = self.enc1(x)
        s2, x = self.enc2(x)
        x     = self.bottleneck(x)
        x     = self.dec1(x, s2)
        x     = self.dec2(x, s1)
        return torch.sigmoid(self.out(x))

# ── Train & Eval functions ──────────────────────────────
def train_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total = 0
    for imgs, masks in loader:
        imgs, masks = imgs.to(device), masks.to(device)
        optimizer.zero_grad()
        loss = criterion(model(imgs), masks)
        loss.backward()
        optimizer.step()
        total += loss.item()
    return total / len(loader)

def eval_epoch(model, loader, criterion, device):
    model.eval()
    total = 0
    with torch.no_grad():
        for imgs, masks in loader:
            imgs, masks = imgs.to(device), masks.to(device)
            total += criterion(model(imgs), masks).item()
    return total / len(loader)

# ── Run ─────────────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

train_ds = GunDataset(CONFIG["dataset_root"], "train", CONFIG["img_size"])
val_ds   = GunDataset(CONFIG["dataset_root"], "valid", CONFIG["img_size"])

train_loader = DataLoader(train_ds, batch_size=CONFIG["batch_size"], shuffle=True)
val_loader   = DataLoader(val_ds,   batch_size=CONFIG["batch_size"])

model     = UNet().to(device)
optimizer = optim.Adam(model.parameters(), lr=CONFIG["learning_rate"])
criterion = nn.BCELoss()

train_losses, val_losses = [], []

for epoch in range(CONFIG["epochs"]):
    tr = train_epoch(model, train_loader, optimizer, criterion, device)
    vl = eval_epoch(model, val_loader,   criterion,             device)
    train_losses.append(tr)
    val_losses.append(vl)
    print(f"Epoch {epoch+1:02d}/{CONFIG['epochs']} | Train: {tr:.4f} | Val: {vl:.4f}")

torch.save(model.state_dict(), CONFIG["model_path"])
print("✅ Model saved!")

# ── Plot Loss ───────────────────────────────────────────
plt.figure(figsize=(8,4))
plt.plot(train_losses, label="Train Loss", marker='o')
plt.plot(val_losses,   label="Val Loss",   marker='s')
plt.title("Training vs Validation Loss")
plt.xlabel("Epoch"); plt.ylabel("BCE Loss")
plt.legend(); plt.grid(True); plt.tight_layout()
plt.show()

# ── Visualize Predictions ───────────────────────────────
model.eval()
imgs, masks = next(iter(val_loader))
imgs, masks = imgs.to(device), masks.to(device)

with torch.no_grad():
    preds = model(imgs)

for i in range(min(CONFIG["vis_samples"], len(imgs))):
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))
    axes[0].imshow(imgs[i].cpu().permute(1,2,0))
    axes[0].set_title("Input Image")
    axes[1].imshow(masks[i].cpu().squeeze(), cmap='gray')
    axes[1].set_title("True Mask")
    axes[2].imshow((preds[i].cpu().squeeze() > 0.5), cmap='gray')
    axes[2].set_title("Predicted Mask")
    for ax in axes: ax.axis('off')
    plt.tight_layout()
    plt.show()

import os, glob, json
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import matplotlib.pyplot as plt
import cv2
CONFIG = {
    "dataset_root": "/content/Guns-1",
    "img_size":     256,       # bigger than before (was 128)
    "batch_size":   4,
    "epochs":       50,        # more epochs (was 20)
    "learning_rate": 1e-4,
    "vis_samples":  3,
    "model_path":   "unet_gun_v2.pth",
}
class GunDataset(Dataset):
    def __init__(self, root, split="train", img_size=256):
        self.img_size = img_size
        self.img_dir  = os.path.join(root, split)
        ann_file      = os.path.join(root, split, "_annotations.coco.json")

        with open(ann_file) as f:
            coco = json.load(f)

        self.id2file = {img["id"]: img["file_name"] for img in coco["images"]}

        self.id2anns = {}
        for ann in coco["annotations"]:
            iid = ann["image_id"]
            self.id2anns.setdefault(iid, []).append(ann)

        self.image_ids = list(self.id2file.keys())
        print(f"  {split}: {len(self.image_ids)} images loaded")

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        iid      = self.image_ids[idx]
        img_path = os.path.join(self.img_dir, self.id2file[iid])

        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        h, w = img.shape[:2]

        # build mask from polygons
        mask = np.zeros((h, w), dtype=np.uint8)
        for ann in self.id2anns.get(iid, []):
            for seg in ann.get("segmentation", []):
                pts = np.array(seg).reshape(-1, 2).astype(np.int32)
                cv2.fillPoly(mask, [pts], 1)

        img  = cv2.resize(img,  (self.img_size, self.img_size))
        mask = cv2.resize(mask, (self.img_size, self.img_size),
                          interpolation=cv2.INTER_NEAREST)

        img  = torch.tensor(img.astype(np.float32) / 255.0).permute(2, 0, 1)
        mask = torch.tensor(mask.astype(np.float32)).unsqueeze(0)
        return img, mask
class DoubleConv(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
    def forward(self, x): return self.block(x)

class EncoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = DoubleConv(in_ch, out_ch)
        self.pool = nn.MaxPool2d(2)
    def forward(self, x):
        skip = self.conv(x)
        return skip, self.pool(skip)

class DecoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.up   = nn.ConvTranspose2d(in_ch, out_ch, 2, 2)
        self.conv = DoubleConv(out_ch * 2, out_ch)
    def forward(self, x, skip):
        x = self.up(x)
        if x.shape != skip.shape:
            x = nn.functional.interpolate(x, size=skip.shape[2:])
        return self.conv(torch.cat([x, skip], dim=1))

# ✅ Bigger UNet — 3 encoder + 3 decoder levels
class UNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.enc1       = EncoderBlock(3,   64)
        self.enc2       = EncoderBlock(64,  128)
        self.enc3       = EncoderBlock(128, 256)   # NEW
        self.bottleneck = DoubleConv(256,   512)   # BIGGER
        self.dec1       = DecoderBlock(512, 256)   # NEW
        self.dec2       = DecoderBlock(256, 128)
        self.dec3       = DecoderBlock(128, 64)    # NEW
        self.out        = nn.Conv2d(64, 1, 1)

    def forward(self, x):
        s1, x = self.enc1(x)
        s2, x = self.enc2(x)
        s3, x = self.enc3(x)
        x     = self.bottleneck(x)
        x     = self.dec1(x, s3)
        x     = self.dec2(x, s2)
        x     = self.dec3(x, s1)
        return torch.sigmoid(self.out(x))


# ✅ Dice Loss — better for segmentation than BCE alone
def dice_loss(pred, target, smooth=1):
    pred   = pred.view(-1)
    target = target.view(-1)
    intersection = (pred * target).sum()
    return 1 - (2 * intersection + smooth) / (pred.sum() + target.sum() + smooth)

# ✅ Combined Loss = BCE + Dice
def combined_loss(pred, target):
    return nn.BCELoss()(pred, target) + dice_loss(pred, target)
def train_epoch(model, loader, optimizer, device):
    model.train()
    total = 0
    for imgs, masks in loader:
        imgs, masks = imgs.to(device), masks.to(device)
        optimizer.zero_grad()
        loss = combined_loss(model(imgs), masks)
        loss.backward()
        optimizer.step()
        total += loss.item()
    return total / len(loader)

def eval_epoch(model, loader, device):
    model.eval()
    total = 0
    with torch.no_grad():
        for imgs, masks in loader:
            imgs, masks = imgs.to(device), masks.to(device)
            total += combined_loss(model(imgs), masks).item()
    return total / len(loader)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

train_ds = GunDataset(CONFIG["dataset_root"], "train", CONFIG["img_size"])
val_ds   = GunDataset(CONFIG["dataset_root"], "valid", CONFIG["img_size"])

train_loader = DataLoader(train_ds, batch_size=CONFIG["batch_size"], shuffle=True)
val_loader   = DataLoader(val_ds,   batch_size=CONFIG["batch_size"])

model     = UNet().to(device)
optimizer = optim.Adam(model.parameters(), lr=CONFIG["learning_rate"])

# ✅ Scheduler — auto reduces LR when loss stops improving
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=5
)

train_losses, val_losses = [], []
best_val_loss = float('inf')

for epoch in range(CONFIG["epochs"]):
    tr = train_epoch(model, train_loader, optimizer, device)
    vl = eval_epoch(model, val_loader,   device)

    train_losses.append(tr)
    val_losses.append(vl)

    # step scheduler
    scheduler.step(vl)
    current_lr = optimizer.param_groups[0]['lr']

    # ✅ save best model automatically
    if vl < best_val_loss:
        best_val_loss = vl
        torch.save(model.state_dict(), CONFIG["model_path"])
        saved = "✅ saved"
    else:
        saved = ""

    print(f"Epoch {epoch+1:02d}/{CONFIG['epochs']} | "
          f"Train: {tr:.4f} | Val: {vl:.4f} | "
          f"LR: {current_lr:.6f} {saved}")

print(f"\nBest Val Loss: {best_val_loss:.4f}")
print("Model saved to", CONFIG["model_path"])
plt.figure(figsize=(10, 4))
plt.plot(train_losses, label="Train Loss", marker='o', markersize=3)
plt.plot(val_losses,   label="Val Loss",   marker='s', markersize=3)
plt.title("Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("BCE + Dice Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()
# load best saved model
model.load_state_dict(torch.load(CONFIG["model_path"]))
model.eval()

imgs, masks = next(iter(val_loader))
imgs, masks = imgs.to(device), masks.to(device)

with torch.no_grad():
    preds = model(imgs)

for i in range(min(CONFIG["vis_samples"], len(imgs))):
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))

    axes[0].imshow(imgs[i].cpu().permute(1, 2, 0))
    axes[0].set_title("Input Image")

    axes[1].imshow(masks[i].cpu().squeeze(), cmap='gray')
    axes[1].set_title("True Mask")

    axes[2].imshow((preds[i].cpu().squeeze() > 0.5), cmap='gray')
    axes[2].set_title("Predicted Mask")

    for ax in axes:
        ax.axis('off')

    plt.tight_layout()
    plt.show()

# ============================================================
# CELL 1 — Install & Download
# ============================================================
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="cyGDeK8mgvw7ZFBtmJ9I")
project = rf.workspace("emans-workspace-bczzy").project("guns-vhehj")
version = project.version(1)
dataset = version.download("coco-segmentation")

# ============================================================
# CELL 2 — Imports
# ============================================================
import os, json
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import matplotlib.pyplot as plt
import cv2

# ============================================================
# CELL 3 — Config
# ============================================================
CONFIG = {
    "dataset_root":  "/content/Guns-1",
    "img_size":      256,
    "batch_size":    4,
    "epochs":        60,
    "learning_rate": 5e-5,
    "vis_samples":   3,
    "model_path":    "unet_gun_v3.pth",
}

# ============================================================
# CELL 4 — Dataset
# ============================================================
class GunDataset(Dataset):
    def __init__(self, root, split="train", img_size=256):
        self.img_size = img_size
        self.img_dir  = os.path.join(root, split)
        ann_file      = os.path.join(root, split, "_annotations.coco.json")

        with open(ann_file) as f:
            coco = json.load(f)

        self.id2file = {img["id"]: img["file_name"] for img in coco["images"]}

        self.id2anns = {}
        for ann in coco["annotations"]:
            iid = ann["image_id"]
            self.id2anns.setdefault(iid, []).append(ann)

        self.image_ids = list(self.id2file.keys())
        print(f"  {split}: {len(self.image_ids)} images loaded")

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        iid      = self.image_ids[idx]
        img_path = os.path.join(self.img_dir, self.id2file[iid])

        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        h, w = img.shape[:2]

        mask = np.zeros((h, w), dtype=np.uint8)
        for ann in self.id2anns.get(iid, []):
            for seg in ann.get("segmentation", []):
                pts = np.array(seg).reshape(-1, 2).astype(np.int32)
                cv2.fillPoly(mask, [pts], 1)

        img  = cv2.resize(img,  (self.img_size, self.img_size))
        mask = cv2.resize(mask, (self.img_size, self.img_size),
                          interpolation=cv2.INTER_NEAREST)

        img  = torch.tensor(img.astype(np.float32) / 255.0).permute(2, 0, 1)
        mask = torch.tensor(mask.astype(np.float32)).unsqueeze(0)
        return img, mask

# ============================================================
# CELL 5 — U-Net Model
# ============================================================
class DoubleConv(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
    def forward(self, x): return self.block(x)

class EncoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = DoubleConv(in_ch, out_ch)
        self.pool = nn.MaxPool2d(2)
    def forward(self, x):
        skip = self.conv(x)
        return skip, self.pool(skip)

class DecoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.up   = nn.ConvTranspose2d(in_ch, out_ch, 2, 2)
        self.conv = DoubleConv(out_ch * 2, out_ch)
    def forward(self, x, skip):
        x = self.up(x)
        if x.shape != skip.shape:
            x = nn.functional.interpolate(x, size=skip.shape[2:])
        return self.conv(torch.cat([x, skip], dim=1))

class UNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.enc1       = EncoderBlock(3,   64)
        self.enc2       = EncoderBlock(64,  128)
        self.enc3       = EncoderBlock(128, 256)
        self.bottleneck = DoubleConv(256,   512)
        self.dec1       = DecoderBlock(512, 256)
        self.dec2       = DecoderBlock(256, 128)
        self.dec3       = DecoderBlock(128, 64)
        self.out        = nn.Conv2d(64, 1, 1)

    def forward(self, x):
        s1, x = self.enc1(x)
        s2, x = self.enc2(x)
        s3, x = self.enc3(x)
        x     = self.bottleneck(x)
        x     = self.dec1(x, s3)
        x     = self.dec2(x, s2)
        x     = self.dec3(x, s1)
        return torch.sigmoid(self.out(x))

# ============================================================
# CELL 6 — Loss Functions
# ============================================================
def dice_loss(pred, target, smooth=1):
    pred        = pred.view(-1)
    target      = target.view(-1)
    intersection = (pred * target).sum()
    return 1 - (2 * intersection + smooth) / (pred.sum() + target.sum() + smooth)

def combined_loss(pred, target):
    return nn.BCELoss()(pred, target) + dice_loss(pred, target)

# ============================================================
# CELL 7 — Training Loop
# ============================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

train_ds = GunDataset(CONFIG["dataset_root"], "train", CONFIG["img_size"])
val_ds   = GunDataset(CONFIG["dataset_root"], "valid", CONFIG["img_size"])

train_loader = DataLoader(train_ds, batch_size=CONFIG["batch_size"], shuffle=True)
val_loader   = DataLoader(val_ds,   batch_size=CONFIG["batch_size"])

model     = UNet().to(device)
optimizer = optim.Adam(model.parameters(),
                       lr=CONFIG["learning_rate"],
                       weight_decay=1e-4)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=CONFIG["epochs"],
    eta_min=1e-6
)

train_losses, val_losses = [], []
best_val_loss = float('inf')

for epoch in range(CONFIG["epochs"]):

    # Train
    model.train()
    total = 0
    for imgs, masks in train_loader:
        imgs, masks = imgs.to(device), masks.to(device)
        optimizer.zero_grad()
        loss = combined_loss(model(imgs), masks)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        total += loss.item()
    tr = total / len(train_loader)

    # Validate
    model.eval()
    total = 0
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.to(device), masks.to(device)
            total += combined_loss(model(imgs), masks).item()
    vl = total / len(val_loader)

    train_losses.append(tr)
    val_losses.append(vl)
    scheduler.step()

    current_lr = optimizer.param_groups[0]['lr']

    if vl < best_val_loss:
        best_val_loss = vl
        torch.save(model.state_dict(), CONFIG["model_path"])
        saved = "✅ saved"
    else:
        saved = ""

    print(f"Epoch {epoch+1:02d}/{CONFIG['epochs']} | "
          f"Train: {tr:.4f} | Val: {vl:.4f} | "
          f"LR: {current_lr:.6f} {saved}")

print(f"\n✅ Best Val Loss: {best_val_loss:.4f}")
print(f"✅ Model saved to {CONFIG['model_path']}")

# ============================================================
# CELL 8 — Plot Loss
# ============================================================
plt.figure(figsize=(10, 4))
plt.plot(train_losses, label="Train Loss", marker='o', markersize=3)
plt.plot(val_losses,   label="Val Loss",   marker='s', markersize=3)
plt.title("Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("BCE + Dice Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# ============================================================
# CELL 9 — Visualize Predictions
# ============================================================
model.load_state_dict(torch.load(CONFIG["model_path"]))
model.eval()

imgs, masks = next(iter(val_loader))
imgs, masks = imgs.to(device), masks.to(device)

with torch.no_grad():
    preds = model(imgs)

for i in range(min(CONFIG["vis_samples"], len(imgs))):
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))

    axes[0].imshow(imgs[i].cpu().permute(1, 2, 0))
    axes[0].set_title("Input Image")

    axes[1].imshow(masks[i].cpu().squeeze(), cmap='gray')
    axes[1].set_title("True Mask")

    axes[2].imshow((preds[i].cpu().squeeze() > 0.5), cmap='gray')
    axes[2].set_title("Predicted Mask")

    for ax in axes:
        ax.axis('off')

    plt.tight_layout()
    plt.show()

# ============================================================
# CELL 10 — IoU Score
# ============================================================
def compute_iou(pred, target, threshold=0.5):
    pred         = (pred > threshold).float()
    target       = target.float()
    intersection = (pred * target).sum()
    union        = pred.sum() + target.sum() - intersection
    return (intersection / (union + 1e-6)).item()

model.eval()
iou_scores = []

with torch.no_grad():
    for imgs, masks in val_loader:
        imgs, masks = imgs.to(device), masks.to(device)
        preds = model(imgs)
        for i in range(len(imgs)):
            iou = compute_iou(preds[i], masks[i])
            iou_scores.append(iou)

print(f"Mean IoU: {np.mean(iou_scores):.4f}")
print(f"Best IoU: {np.max(iou_scores):.4f}")
print(f"Worst IoU: {np.min(iou_scores):.4f}")

# ============================================================
# CELL 2 — Imports
# ============================================================
import os, json, random
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import matplotlib.pyplot as plt
import cv2

# ============================================================
# CELL 3 — Config
# ============================================================
CONFIG = {
    "dataset_root":  "/content/Guns-1",
    "img_size":      256,
    "batch_size":    4,
    "epochs":        60,
    "learning_rate": 5e-5,
    "vis_samples":   3,
    "model_path":    "unet_gun_v4.pth",  # NEW version
}

# ============================================================
# CELL 4 — Dataset WITH Augmentation (NEW)
# ============================================================
class GunDataset(Dataset):
    def __init__(self, root, split="train", img_size=256):
        self.img_size = img_size
        self.split    = split                          # ✅ NEW — track split
        self.img_dir  = os.path.join(root, split)
        ann_file      = os.path.join(root, split, "_annotations.coco.json")

        with open(ann_file) as f:
            coco = json.load(f)

        self.id2file = {img["id"]: img["file_name"] for img in coco["images"]}

        self.id2anns = {}
        for ann in coco["annotations"]:
            iid = ann["image_id"]
            self.id2anns.setdefault(iid, []).append(ann)

        self.image_ids = list(self.id2file.keys())
        print(f"  {split}: {len(self.image_ids)} images loaded")

    # ✅ NEW — augmentation function
    def augment(self, img, mask):
        # Random horizontal flip
        if random.random() > 0.5:
            img  = cv2.flip(img,  1)
            mask = cv2.flip(mask, 1)

        # Random vertical flip
        if random.random() > 0.5:
            img  = cv2.flip(img,  0)
            mask = cv2.flip(mask, 0)

        # Random brightness
        if random.random() > 0.5:
            factor = random.uniform(0.7, 1.3)
            img    = np.clip(img * factor, 0, 255).astype(np.uint8)

        # Random rotation
        if random.random() > 0.5:
            angle = random.randint(-30, 30)
            h, w  = img.shape[:2]
            M     = cv2.getRotationMatrix2D((w//2, h//2), angle, 1.0)
            img   = cv2.warpAffine(img,  M, (w, h))
            mask  = cv2.warpAffine(mask, M, (w, h))

        # ✅ NEW — Random zoom in
        if random.random() > 0.5:
            scale  = random.uniform(0.8, 1.0)
            h, w   = img.shape[:2]
            nh, nw = int(h * scale), int(w * scale)
            y1     = (h - nh) // 2
            x1     = (w - nw) // 2
            img    = img[y1:y1+nh,  x1:x1+nw]
            mask   = mask[y1:y1+nh, x1:x1+nw]
            img    = cv2.resize(img,  (w, h))
            mask   = cv2.resize(mask, (w, h),
                                interpolation=cv2.INTER_NEAREST)

        return img, mask

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        iid      = self.image_ids[idx]
        img_path = os.path.join(self.img_dir, self.id2file[iid])

        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        h, w = img.shape[:2]

        mask = np.zeros((h, w), dtype=np.uint8)
        for ann in self.id2anns.get(iid, []):
            for seg in ann.get("segmentation", []):
                pts = np.array(seg).reshape(-1, 2).astype(np.int32)
                cv2.fillPoly(mask, [pts], 1)

        # ✅ NEW — only augment train, never validation
        if self.split == "train":
            img, mask = self.augment(img, mask)

        img  = cv2.resize(img,  (self.img_size, self.img_size))
        mask = cv2.resize(mask, (self.img_size, self.img_size),
                          interpolation=cv2.INTER_NEAREST)

        img  = torch.tensor(img.astype(np.float32) / 255.0).permute(2, 0, 1)
        mask = torch.tensor(mask.astype(np.float32)).unsqueeze(0)
        return img, mask

# ============================================================
# CELL 5 — U-Net Model (unchanged, still 3 levels)
# ============================================================
class DoubleConv(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),
        )
    def forward(self, x): return self.block(x)

class EncoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = DoubleConv(in_ch, out_ch)
        self.pool = nn.MaxPool2d(2)
    def forward(self, x):
        skip = self.conv(x)
        return skip, self.pool(skip)

class DecoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.up   = nn.ConvTranspose2d(in_ch, out_ch, 2, 2)
        self.conv = DoubleConv(out_ch * 2, out_ch)
    def forward(self, x, skip):
        x = self.up(x)
        if x.shape != skip.shape:
            x = nn.functional.interpolate(x, size=skip.shape[2:])
        return self.conv(torch.cat([x, skip], dim=1))

class UNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.enc1       = EncoderBlock(3,   64)
        self.enc2       = EncoderBlock(64,  128)
        self.enc3       = EncoderBlock(128, 256)
        self.bottleneck = DoubleConv(256,   512)
        self.dec1       = DecoderBlock(512, 256)
        self.dec2       = DecoderBlock(256, 128)
        self.dec3       = DecoderBlock(128, 64)
        self.out        = nn.Conv2d(64, 1, 1)

    def forward(self, x):
        s1, x = self.enc1(x)
        s2, x = self.enc2(x)
        s3, x = self.enc3(x)
        x     = self.bottleneck(x)
        x     = self.dec1(x, s3)
        x     = self.dec2(x, s2)
        x     = self.dec3(x, s1)
        return torch.sigmoid(self.out(x))

# ============================================================
# CELL 6 — Loss Functions (unchanged)
# ============================================================
def dice_loss(pred, target, smooth=1):
    pred         = pred.view(-1)
    target       = target.view(-1)
    intersection = (pred * target).sum()
    return 1 - (2 * intersection + smooth) / (pred.sum() + target.sum() + smooth)

def combined_loss(pred, target):
    return nn.BCELoss()(pred, target) + dice_loss(pred, target)

# ============================================================
# CELL 7 — Training Loop (unchanged)
# ============================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

train_ds = GunDataset(CONFIG["dataset_root"], "train", CONFIG["img_size"])
val_ds   = GunDataset(CONFIG["dataset_root"], "valid", CONFIG["img_size"])

train_loader = DataLoader(train_ds, batch_size=CONFIG["batch_size"], shuffle=True)
val_loader   = DataLoader(val_ds,   batch_size=CONFIG["batch_size"])

model     = UNet().to(device)
optimizer = optim.Adam(model.parameters(),
                       lr=CONFIG["learning_rate"],
                       weight_decay=1e-4)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=CONFIG["epochs"],
    eta_min=1e-6
)

train_losses, val_losses = [], []
best_val_loss = float('inf')

for epoch in range(CONFIG["epochs"]):

    # Train
    model.train()
    total = 0
    for imgs, masks in train_loader:
        imgs, masks = imgs.to(device), masks.to(device)
        optimizer.zero_grad()
        loss = combined_loss(model(imgs), masks)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        total += loss.item()
    tr = total / len(train_loader)

    # Validate
    model.eval()
    total = 0
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.to(device), masks.to(device)
            total += combined_loss(model(imgs), masks).item()
    vl = total / len(val_loader)

    train_losses.append(tr)
    val_losses.append(vl)
    scheduler.step()

    current_lr = optimizer.param_groups[0]['lr']

    if vl < best_val_loss:
        best_val_loss = vl
        torch.save(model.state_dict(), CONFIG["model_path"])
        saved = "✅ saved"
    else:
        saved = ""

    print(f"Epoch {epoch+1:02d}/{CONFIG['epochs']} | "
          f"Train: {tr:.4f} | Val: {vl:.4f} | "
          f"LR: {current_lr:.6f} {saved}")

print(f"\n✅ Best Val Loss: {best_val_loss:.4f}")
print(f"✅ Model saved to {CONFIG['model_path']}")

# ============================================================
# CELL 8 — Plot Loss
# ============================================================
plt.figure(figsize=(10, 4))
plt.plot(train_losses, label="Train Loss", marker='o', markersize=3)
plt.plot(val_losses,   label="Val Loss",   marker='s', markersize=3)
plt.title("Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("BCE + Dice Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# ============================================================
# CELL 9 — Visualize Predictions
# ============================================================
model.load_state_dict(torch.load(CONFIG["model_path"]))
model.eval()

imgs, masks = next(iter(val_loader))
imgs, masks = imgs.to(device), masks.to(device)

with torch.no_grad():
    preds = model(imgs)

for i in range(min(CONFIG["vis_samples"], len(imgs))):
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))

    axes[0].imshow(imgs[i].cpu().permute(1, 2, 0))
    axes[0].set_title("Input Image")

    axes[1].imshow(masks[i].cpu().squeeze(), cmap='gray')
    axes[1].set_title("True Mask")

    axes[2].imshow((preds[i].cpu().squeeze() > 0.5), cmap='gray')
    axes[2].set_title("Predicted Mask")

    for ax in axes:
        ax.axis('off')

    plt.tight_layout()
    plt.show()

# ============================================================
# CELL 10 — IoU Score
# ============================================================
def compute_iou(pred, target, threshold=0.5):
    pred         = (pred > threshold).float()
    target       = target.float()
    intersection = (pred * target).sum()
    union        = pred.sum() + target.sum() - intersection
    return (intersection / (union + 1e-6)).item()

model.eval()
iou_scores = []

with torch.no_grad():
    for imgs, masks in val_loader:
        imgs, masks = imgs.to(device), masks.to(device)
        preds = model(imgs)
        for i in range(len(imgs)):
            iou = compute_iou(preds[i], masks[i])
            iou_scores.append(iou)

print(f"Mean IoU: {np.mean(iou_scores):.4f}")
print(f"Best IoU: {np.max(iou_scores):.4f}")
print(f"Worst IoU: {np.min(iou_scores):.4f}")