# -*- coding: utf-8 -*-
"""GANS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Amv3hOcs3cSQu1y4WD0p3nfPmJt8TtWs
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# ============================================================
# DATA
# ============================================================
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])
train_dataset = datasets.MNIST(root="./data", train=True, transform=transform, download=True)
train_loader  = DataLoader(train_dataset, batch_size=128, shuffle=True, drop_last=True)
print(f"Dataset: {len(train_dataset)} images\n")

# ============================================================
# HELPERS
# ============================================================
def plot_losses(g_losses, d_losses, title, ymax=2.5):
    plt.figure(figsize=(8, 4))
    plt.plot(g_losses, label='Generator Loss',     color='blue')
    plt.plot(d_losses, label='Discriminator Loss', color='red')
    plt.title(title); plt.xlabel('Epoch'); plt.ylabel('Loss')
    plt.ylim(0, ymax); plt.legend(); plt.tight_layout()
    plt.savefig(title.replace(' ','_')+".png", dpi=150, bbox_inches='tight')
    plt.show()

def visualize_images(generator, latent_dim, title, dc=False):
    generator.eval()
    with torch.no_grad():
        noise = torch.randn(16, latent_dim, 1, 1).to(device) if dc \
                else torch.randn(16, latent_dim).to(device)
        imgs = generator(noise).cpu()
    fig, axes = plt.subplots(2, 8, figsize=(16, 4))
    for i, ax in enumerate(axes.flatten()):
        ax.imshow(imgs[i].squeeze(), cmap="gray"); ax.axis("off")
    fig.suptitle(title, fontsize=13); plt.tight_layout()
    plt.savefig(title.replace(' ','_')+".png", dpi=150, bbox_inches='tight')
    plt.show()
    generator.train()

# ============================================================
# BASE GAN — Fully Connected, 30 epochs  (FIXED v3)
# ============================================================
class Generator(nn.Module):
    def __init__(self, latent_dim):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(latent_dim, 256), nn.LeakyReLU(0.2),
            nn.Linear(256, 512),        nn.LeakyReLU(0.2),
            nn.Linear(512, 784),        nn.Tanh()
        )
    def forward(self, z): return self.model(z).view(z.size(0), 1, 28, 28)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(784, 512), nn.LeakyReLU(0.2), nn.Dropout(0.3),
            nn.Linear(512, 256), nn.LeakyReLU(0.2), nn.Dropout(0.3),
            nn.Linear(256, 1),   nn.Sigmoid()
        )
    def forward(self, x): return self.model(x.view(x.size(0), -1))

def train_gan(generator, discriminator, loader, epochs, latent_dim, g_opt, d_opt, label):
    criterion = nn.BCELoss()
    g_losses, d_losses = [], []
    print(f"\n{'='*50}\nTraining: {label}\n{'='*50}")
    for epoch in range(epochs):
        g_ep = d_ep = 0
        for real_images, _ in loader:
            bs = real_images.size(0)
            real_images = real_images.to(device)
            real_labels = torch.full((bs, 1), 0.9).to(device)
            fake_labels = torch.zeros(bs, 1).to(device)

            # Train D once
            d_opt.zero_grad()
            noise = torch.randn(bs, latent_dim).to(device)
            fakes = generator(noise)
            d_loss = criterion(discriminator(real_images), real_labels) + \
                     criterion(discriminator(fakes.detach()), fake_labels)
            d_loss.backward(); d_opt.step()

            # Train G twice
            for _ in range(2):
                g_opt.zero_grad()
                noise2 = torch.randn(bs, latent_dim).to(device)
                g_loss = criterion(discriminator(generator(noise2)),
                                   torch.ones(bs, 1).to(device))
                g_loss.backward(); g_opt.step()

            g_ep += g_loss.item(); d_ep += d_loss.item()

        avg_g = g_ep / len(loader); avg_d = d_ep / len(loader)
        g_losses.append(avg_g); d_losses.append(avg_d)
        print(f"Epoch [{epoch+1:3d}/{epochs}] | D Loss: {avg_d:.4f} | G Loss: {avg_g:.4f}")
    return g_losses, d_losses

latent_dim = 100
gen = Generator(latent_dim).to(device)
dis = Discriminator().to(device)
g_opt = optim.Adam(gen.parameters(), lr=0.0003, betas=(0.5, 0.999))
d_opt = optim.Adam(dis.parameters(), lr=0.0001, betas=(0.5, 0.999))

g_base, d_base = train_gan(gen, dis, train_loader, epochs=30,
    latent_dim=latent_dim, g_opt=g_opt, d_opt=d_opt, label="Base GAN FC 30 Epochs")
plot_losses(g_base, d_base, "Base GAN Loss Curve")
visualize_images(gen, latent_dim, "Base GAN Generated Images Epoch 30")


# ============================================================
# TASK 2 — DCGAN FULLY STABLE VERSION
# Uses smaller architecture + spectral norm + no collapse
# ============================================================
transform_dc = transforms.Compose([
    transforms.Resize(32), transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])
train_ds_dc = datasets.MNIST(root="./data", train=True, transform=transform_dc, download=True)
train_ld_dc = DataLoader(train_ds_dc, batch_size=128, shuffle=True, drop_last=True)

def weights_init(m):
    classname = m.__class__.__name__
    if classname.find('Conv') != -1:
        nn.init.normal_(m.weight.data, 0.0, 0.02)
    elif classname.find('BatchNorm') != -1:
        nn.init.normal_(m.weight.data, 1.0, 0.02)
        nn.init.constant_(m.bias.data, 0)

class DCGenerator(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            # 1x1 -> 4x4
            nn.ConvTranspose2d(100, 256, 4, 1, 0, bias=False),
            nn.BatchNorm2d(256), nn.ReLU(True),
            # 4x4 -> 8x8
            nn.ConvTranspose2d(256, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128), nn.ReLU(True),
            # 8x8 -> 16x16
            nn.ConvTranspose2d(128, 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(64), nn.ReLU(True),
            # 16x16 -> 32x32
            nn.ConvTranspose2d(64, 1, 4, 2, 1, bias=False),
            nn.Tanh()
        )
    def forward(self, z): return self.net(z)

class DCDiscriminator(nn.Module):
    def __init__(self):
        super().__init__()
        # Spectral norm on every conv layer — prevents D from becoming too powerful
        self.net = nn.Sequential(
            nn.utils.spectral_norm(nn.Conv2d(1, 64, 4, 2, 1, bias=False)),
            nn.LeakyReLU(0.2, inplace=True),
            nn.utils.spectral_norm(nn.Conv2d(64, 128, 4, 2, 1, bias=False)),
            nn.LeakyReLU(0.2, inplace=True),
            nn.utils.spectral_norm(nn.Conv2d(128, 256, 4, 2, 1, bias=False)),
            nn.LeakyReLU(0.2, inplace=True),
            nn.utils.spectral_norm(nn.Conv2d(256, 1, 4, 1, 0, bias=False)),
            nn.Sigmoid()
        )
    def forward(self, x): return self.net(x).view(-1, 1)

def train_dcgan(generator, discriminator, loader, epochs, g_opt, d_opt, label):
    criterion = nn.BCELoss()
    g_losses, d_losses = [], []
    print(f"\n{'='*50}\nTraining: {label}\n{'='*50}")
    for epoch in range(epochs):
        g_ep = d_ep = 0
        for real_images, _ in loader:
            bs = real_images.size(0)
            real_images = real_images.to(device)
            real_labels = torch.full((bs, 1), 0.9).to(device)
            fake_labels = torch.zeros(bs, 1).to(device)

            noise = torch.randn(bs, 100, 1, 1).to(device)
            fakes = generator(noise)

            # Train D once
            d_opt.zero_grad()
            d_loss = criterion(discriminator(real_images), real_labels) + \
                     criterion(discriminator(fakes.detach()), fake_labels)
            d_loss.backward(); d_opt.step()

            # Train G twice
            for _ in range(2):
                g_opt.zero_grad()
                noise2 = torch.randn(bs, 100, 1, 1).to(device)
                g_loss = criterion(discriminator(generator(noise2)),
                                   torch.ones(bs, 1).to(device))
                g_loss.backward(); g_opt.step()

            g_ep += g_loss.item(); d_ep += d_loss.item()

        avg_g = g_ep / len(loader); avg_d = d_ep / len(loader)
        g_losses.append(avg_g); d_losses.append(avg_d)
        print(f"Epoch [{epoch+1:3d}/{epochs}] | D Loss: {avg_d:.4f} | G Loss: {avg_g:.4f}")
    return g_losses, d_losses

dc_gen = DCGenerator().to(device)
dc_dis = DCDiscriminator().to(device)
dc_gen.apply(weights_init)
# Note: spectral norm layers skip weights_init (handled internally)

g_opt3 = optim.Adam(dc_gen.parameters(), lr=0.0002, betas=(0.5, 0.999))
d_opt3 = optim.Adam(dc_dis.parameters(), lr=0.0001, betas=(0.5, 0.999))

g_dc, d_dc = train_dcgan(dc_gen, dc_dis, train_ld_dc, epochs=50,
    g_opt=g_opt3, d_opt=d_opt3, label="DCGAN Convolutional 50 Epochs")
plot_losses(g_dc, d_dc, "DCGAN Loss Curve Task 2")
visualize_images(dc_gen, 100, "DCGAN Generated Images Task 2", dc=True)

print("\nAll done!")

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])
train_dataset = datasets.MNIST(root="./data", train=True, transform=transform, download=True)
train_loader  = DataLoader(train_dataset, batch_size=128, shuffle=True, drop_last=True)
print(f"Dataset: {len(train_dataset)} images\n")

# ============================================================
# MODEL — Deeper layers + BatchNorm
# ============================================================
class GeneratorDeep(nn.Module):
    def __init__(self, latent_dim):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(latent_dim, 256), nn.LeakyReLU(0.2), nn.BatchNorm1d(256),
            nn.Linear(256, 512),        nn.LeakyReLU(0.2), nn.BatchNorm1d(512),
            nn.Linear(512, 1024),       nn.LeakyReLU(0.2), nn.BatchNorm1d(1024),
            nn.Linear(1024, 784),       nn.Tanh()
        )
    def forward(self, z): return self.model(z).view(z.size(0), 1, 28, 28)

class DiscriminatorDeep(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(784, 512), nn.LeakyReLU(0.2), nn.Dropout(0.3),
            nn.Linear(512, 256), nn.LeakyReLU(0.2), nn.Dropout(0.3),
            nn.Linear(256, 1),   nn.Sigmoid()
        )
    def forward(self, x): return self.model(x.view(x.size(0), -1))

# ============================================================
# TRAINING
# ============================================================
latent_dim = 100
gen = GeneratorDeep(latent_dim).to(device)
dis = DiscriminatorDeep().to(device)
g_opt = optim.Adam(gen.parameters(), lr=0.0003, betas=(0.5, 0.999))
d_opt = optim.Adam(dis.parameters(), lr=0.0001, betas=(0.5, 0.999))
criterion = nn.BCELoss()

g_losses, d_losses = [], []
epochs = 50

print(f"{'='*50}\nTraining: Deep GAN (More Layers, 50 Epochs)\n{'='*50}")
for epoch in range(epochs):
    g_ep = d_ep = 0
    for real_images, _ in train_loader:
        bs = real_images.size(0)
        real_images = real_images.to(device)
        real_labels = torch.full((bs, 1), 0.9).to(device)
        fake_labels = torch.zeros(bs, 1).to(device)

        # Train D once
        d_opt.zero_grad()
        noise = torch.randn(bs, latent_dim).to(device)
        fakes = gen(noise)
        d_loss = criterion(dis(real_images), real_labels) + \
                 criterion(dis(fakes.detach()), fake_labels)
        d_loss.backward(); d_opt.step()

        # Train G twice
        for _ in range(2):
            g_opt.zero_grad()
            noise2 = torch.randn(bs, latent_dim).to(device)
            g_loss = criterion(dis(gen(noise2)), torch.ones(bs, 1).to(device))
            g_loss.backward(); g_opt.step()

        g_ep += g_loss.item(); d_ep += d_loss.item()

    avg_g = g_ep / len(train_loader)
    avg_d = d_ep / len(train_loader)
    g_losses.append(avg_g); d_losses.append(avg_d)
    print(f"Epoch [{epoch+1:3d}/{epochs}] | D Loss: {avg_d:.4f} | G Loss: {avg_g:.4f}")

# ============================================================
# PLOTS
# ============================================================
plt.figure(figsize=(8, 4))
plt.plot(g_losses, label='Generator Loss',     color='blue')
plt.plot(d_losses, label='Discriminator Loss', color='red')
plt.title('Deep GAN Loss Curve (Task 1)')
plt.xlabel('Epoch'); plt.ylabel('Loss')
plt.ylim(0, 2.5); plt.legend(); plt.tight_layout()
plt.savefig("Deep_GAN_Loss_Curve_Task_1.png", dpi=150, bbox_inches='tight')
plt.show()

gen.eval()
with torch.no_grad():
    noise = torch.randn(16, latent_dim).to(device)
    imgs  = gen(noise).cpu()
fig, axes = plt.subplots(2, 8, figsize=(16, 4))
for i, ax in enumerate(axes.flatten()):
    ax.imshow(imgs[i].squeeze(), cmap="gray"); ax.axis("off")
fig.suptitle("Deep GAN Generated Images (Task 1)", fontsize=13)
plt.tight_layout()
plt.savefig("Deep_GAN_Generated_Images_Task_1.png", dpi=150, bbox_inches='tight')
plt.show()

print("\nDone!")

import matplotlib.pyplot as plt

# Just run this in the SAME notebook cell after the interruption
# The gen, g_losses, d_losses variables are still in memory

# Plot loss curve
plt.figure(figsize=(8, 4))
plt.plot(g_losses, label='Generator Loss',     color='blue')
plt.plot(d_losses, label='Discriminator Loss', color='red')
plt.title('Deep GAN Loss Curve (Task 1)')
plt.xlabel('Epoch'); plt.ylabel('Loss')
plt.ylim(0, 2.5); plt.legend(); plt.tight_layout()
plt.savefig("Deep_GAN_Loss_Curve_Task_1.png", dpi=150, bbox_inches='tight')
plt.show()

# Plot generated images
gen.eval()
import torch
noise = torch.randn(16, 100).to(device)
with torch.no_grad():
    imgs = gen(noise).cpu()
fig, axes = plt.subplots(2, 8, figsize=(16, 4))
for i, ax in enumerate(axes.flatten()):
    ax.imshow(imgs[i].squeeze(), cmap="gray"); ax.axis("off")
fig.suptitle("Deep GAN Generated Images (Task 1)", fontsize=13)
plt.tight_layout()
plt.savefig("Deep_GAN_Generated_Images_Task_1.png", dpi=150, bbox_inches='tight')
plt.show()

print("Done!")