# -*- coding: utf-8 -*-
"""Faster Rcnn pre trained model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vp8rGPi02ojYsh6LtaWJSyJarXXN1px8
"""

!pip install roboflow pycocotools -q

from roboflow import Roboflow

rf      = Roboflow(api_key="A2YllykE6xoTtfId5TZT")
project = rf.workspace("baheejs-workspace").project("guns-ldyqf")
dataset = project.version(6).download("coco")

import os
print(os.listdir("/content"))

# ================================================================
#   TUTORIAL 8 — COMPLETE CODE — SINGLE CELL
#   1. Faster RCNN on Lamborghini image
#   2. 3 Backbone Comparison (ResNet50, ResNet50V2, MobileNet)
#   3. mAP on 5 labeled Guns images
# ================================================================

import torch
import torchvision
import torchvision.transforms as transforms
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
import os, json, time

# ── COCO class labels ──────────────────────────────────────
COCO_CLASSES = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane',
    'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant',
    'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse',
    'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack',
    'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis',
    'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove',
    'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass',
    'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich',
    'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake',
    'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv',
    'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
    'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase',
    'scissors', 'teddy bear', 'hair drier', 'toothbrush'
]

def get_class_name(label):
    """Safely get class name — avoids index out of range"""
    if label < len(COCO_CLASSES):
        return COCO_CLASSES[label]
    return f"object_{label}"

transform = transforms.Compose([transforms.ToTensor()])

# ================================================================
# PART 1 — FASTER RCNN ON LAMBORGHINI IMAGE
# ================================================================
print("=" * 60)
print("  PART 1 — FASTER RCNN ON LAMBORGHINI IMAGE")
print("=" * 60)

IMAGE_PATH = '/content/IMAGE.jpg'
THRESHOLD  = 0.5

# Load model
print("Loading Faster RCNN ResNet50...")
model1 = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights="DEFAULT")
model1.eval()
print("Model loaded!")

# Run detection
image = Image.open(IMAGE_PATH).convert("RGB")
img_t = transform(image).unsqueeze(0)
W, H  = image.size

with torch.no_grad():
    preds = model1(img_t)

boxes  = preds[0]['boxes'].numpy()
scores = preds[0]['scores'].numpy()
labels = preds[0]['labels'].numpy()
keep   = scores >= THRESHOLD
boxes  = boxes[keep]; scores = scores[keep]; labels = labels[keep]

print(f"\nObjects detected: {len(boxes)}")
for box, score, label in zip(boxes, scores, labels):
    print(f"  {get_class_name(label).upper():<20} | Score: {score:.2f} | Box: {box.astype(int)}")

# ── IOU calculation ────────────────────────────────────────
def calculate_iou(b1, b2):
    x1 = max(b1[0], b2[0]); y1 = max(b1[1], b2[1])
    x2 = min(b1[2], b2[2]); y2 = min(b1[3], b2[3])
    inter = max(0, x2-x1) * max(0, y2-y1)
    a1 = (b1[2]-b1[0]) * (b1[3]-b1[1])
    a2 = (b2[2]-b2[0]) * (b2[3]-b2[1])
    union = a1 + a2 - inter
    return inter/union if union else 0

# Manual ground truth box around the car
gt_box     = [int(W*0.05), int(H*0.30), int(W*0.95), int(H*0.90)]
iou_scores = [calculate_iou(b.tolist(), gt_box) for b in boxes]

print(f"\nGround Truth Box: {gt_box}")
print("\nIOU per detection:")
for box, score, label, iou in zip(boxes, scores, labels, iou_scores):
    status = " GOOD" if iou >= 0.5 else " BAD"
    print(f"  {get_class_name(label).upper():<20} | Conf: {score:.2f} | IOU: {iou:.2f} {status}")

# ── Precision / Recall ─────────────────────────────────────
sorted_idx = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)
tp, fp, matched = 0, 0, set()
for i in sorted_idx:
    iou = calculate_iou(boxes[i].tolist(), gt_box)
    if iou >= 0.5 and 0 not in matched:
        tp += 1; matched.add(0)
    else:
        fp += 1

fn        = 1 - len(matched)
precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall    = tp / (tp + max(fn, 0) + 1e-6)
mAP_lamb  = precision * recall

print(f"\n  TP={tp} | FP={fp} | Precision={precision:.2f} | Recall={recall:.2f} | mAP={mAP_lamb:.2f}")

# ── Visualize Part 1 ───────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

axes[0].imshow(image)
xmin,ymin,xmax,ymax = gt_box
axes[0].add_patch(patches.Rectangle((xmin,ymin), xmax-xmin, ymax-ymin,
    linewidth=3, edgecolor='green', facecolor='none', linestyle='--'))
axes[0].text(xmin, ymin-10, "GROUND TRUTH", color='white', fontsize=9,
    fontweight='bold', bbox=dict(facecolor='green', alpha=0.8))

for box, score, label, iou in zip(boxes, scores, labels, iou_scores):
    xmin,ymin,xmax,ymax = box
    axes[0].add_patch(patches.Rectangle((xmin,ymin), xmax-xmin, ymax-ymin,
        linewidth=2, edgecolor='red', facecolor='none'))
    axes[0].text(xmin, ymin-8,
        f"{get_class_name(label)}: {score:.2f} | IOU:{iou:.2f}",
        color='white', fontsize=8, fontweight='bold',
        bbox=dict(facecolor='red', alpha=0.8))

axes[0].set_title("Faster RCNN — Lamborghini\n Ground Truth   Predictions",
                   fontsize=12, fontweight='bold')
axes[0].axis('off')

metrics = ['Precision', 'Recall', 'mAP']
values  = [precision, recall, mAP_lamb]
colors  = ['#2ecc71', '#3498db', '#9b59b6']
bars    = axes[1].bar(metrics, values, color=colors, edgecolor='black', width=0.4)
axes[1].set_ylim(0, 1.2)
axes[1].axhline(y=0.5, color='gray', linestyle='--', label='Threshold=0.5')
axes[1].set_title("Detection Metrics", fontsize=12, fontweight='bold')
axes[1].set_ylabel("Score")
axes[1].legend()
for bar, val in zip(bars, values):
    axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.02,
                 f"{val:.2f}", ha='center', fontsize=13, fontweight='bold')

plt.suptitle("Part 1 — Faster RCNN on Lamborghini Image",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()


# ================================================================
# PART 2 — 3 BACKBONE COMPARISON
# (ResNet50 + ResNet50 V2 + MobileNetV3)
# ================================================================
print("\n" + "=" * 60)
print("  PART 2 — 3 BACKBONE COMPARISON")
print("  ResNet50 | ResNet50 V2 | MobileNetV3")
print("=" * 60)

def run_detection(model, img_path, threshold=0.5):
    image = Image.open(img_path).convert("RGB")
    img_t = transform(image).unsqueeze(0)
    t0    = time.time()
    with torch.no_grad():
        preds = model(img_t)
    elapsed = time.time() - t0
    boxes  = preds[0]['boxes'].numpy()
    scores = preds[0]['scores'].numpy()
    labels = preds[0]['labels'].numpy()
    keep   = scores >= threshold
    return image, boxes[keep], scores[keep], labels[keep], elapsed

def draw_detections(ax, image, boxes, scores, labels, title):
    ax.imshow(image)
    for box, score, label in zip(boxes, scores, labels):
        xmin, ymin, xmax, ymax = box
        ax.add_patch(patches.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin,
            linewidth=2, edgecolor='lime', facecolor='none'))
        ax.text(xmin, ymin-5,
            f"{get_class_name(label)}: {score:.2f}",
            color='white', fontsize=7, fontweight='bold',
            bbox=dict(facecolor='green', alpha=0.7, pad=1))
    ax.set_title(title, fontsize=11, fontweight='bold')
    ax.axis('off')

# Load 3 models
print("Loading 3 models...")

backbone1 = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights="DEFAULT")
backbone1.eval()
print("  Backbone 1: Faster RCNN ResNet50")

backbone2 = torchvision.models.detection.fasterrcnn_resnet50_fpn_v2(weights="DEFAULT")
backbone2.eval()
print("   Backbone 2: Faster RCNN ResNet50 V2")

backbone3 = torchvision.models.detection.fasterrcnn_mobilenet_v3_large_fpn(weights="DEFAULT")
backbone3.eval()
print("   Backbone 3: Faster RCNN MobileNetV3")

# Run all 3
print("\nRunning detection on Lamborghini image...")
img1, b1, s1, l1, t1 = run_detection(backbone1, IMAGE_PATH)
img2, b2, s2, l2, t2 = run_detection(backbone2, IMAGE_PATH)
img3, b3, s3, l3, t3 = run_detection(backbone3, IMAGE_PATH)

# Plot comparison
fig, axes = plt.subplots(1, 3, figsize=(22, 7))
draw_detections(axes[0], img1, b1, s1, l1,
    f"Backbone 1: ResNet50\n{len(b1)} detections | {t1:.2f}s")
draw_detections(axes[1], img2, b2, s2, l2,
    f"Backbone 2: ResNet50 V2\n{len(b2)} detections | {t2:.2f}s")
draw_detections(axes[2], img3, b3, s3, l3,
    f"Backbone 3: MobileNetV3\n{len(b3)} detections | {t3:.2f}s")

plt.suptitle("Part 2 — 3 Backbone Comparison on Same Image",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Speed vs detections bar chart
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

names  = ['ResNet50', 'ResNet50 V2', 'MobileNetV3']
counts = [len(b1), len(b2), len(b3)]
times  = [t1, t2, t3]
colors = ['#3498db', '#e74c3c', '#2ecc71']

axes[0].bar(names, counts, color=colors, edgecolor='black')
axes[0].set_title("Detections per Backbone", fontsize=12, fontweight='bold')
axes[0].set_ylabel("Number of Detections")
for i, v in enumerate(counts):
    axes[0].text(i, v+0.05, str(v), ha='center', fontsize=13, fontweight='bold')

axes[1].bar(names, times, color=colors, edgecolor='black')
axes[1].set_title("Inference Speed per Backbone", fontsize=12, fontweight='bold')
axes[1].set_ylabel("Time (seconds)")
for i, v in enumerate(times):
    axes[1].text(i, v+0.001, f"{v:.2f}s", ha='center', fontsize=13, fontweight='bold')

plt.suptitle("Backbone Comparison — Speed vs Detections",
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

print(f"\n{'='*55}")
print("   BACKBONE COMPARISON SUMMARY")
print(f"{'='*55}")
print(f"  Backbone 1 — ResNet50    : {len(b1)} detections | {t1:.2f}s")
print(f"  Backbone 2 — ResNet50 V2 : {len(b2)} detections | {t2:.2f}s")
print(f"  Backbone 3 — MobileNetV3 : {len(b3)} detections | {t3:.2f}s")
print(f"\n  MobileNetV3 is fastest (lightweight)")
print(f"  ResNet50 V2 is most accurate (heavier)")
print(f"{'='*55}")


# ================================================================
# PART 3 — mAP ON 5 LABELED GUNS IMAGES
# ================================================================
print("\n" + "=" * 60)
print("  PART 3 — mAP ON 5 LABELED GUNS TEST IMAGES")
print("=" * 60)

TEST_DIR  = "/content/Guns-6/test"
TEST_JSON = "/content/Guns-6/test/_annotations.coco.json"

with open(TEST_JSON) as f:
    coco_data = json.load(f)

# Build ground truth lookup
ann_by_img = {}
for ann in coco_data['annotations']:
    iid = ann['image_id']
    ann_by_img.setdefault(iid, [])
    x, y, w, h = ann['bbox']
    ann_by_img[iid].append([x, y, x+w, y+h])

img_lookup = {img['id']: img['file_name'] for img in coco_data['images']}

# AP calculation
def compute_ap(pred_boxes, pred_scores, gt_boxes, iou_thr=0.5):
    if len(pred_boxes) == 0 or len(gt_boxes) == 0:
        return 0.0
    order   = np.argsort(-np.array(pred_scores))
    matched = set()
    tp_list, fp_list = [], []
    for idx in order:
        best_iou, best_j = 0, -1
        for j, gt in enumerate(gt_boxes):
            if j in matched: continue
            iou = calculate_iou(pred_boxes[idx], gt)
            if iou > best_iou:
                best_iou, best_j = iou, j
        if best_iou >= iou_thr and best_j != -1:
            tp_list.append(1); fp_list.append(0); matched.add(best_j)
        else:
            tp_list.append(0); fp_list.append(1)

    tp_cum     = np.cumsum(tp_list)
    fp_cum     = np.cumsum(fp_list)
    recalls    = tp_cum / max(len(gt_boxes), 1)
    precisions = tp_cum / (tp_cum + fp_cum + 1e-6)
    recalls    = np.concatenate([[0], recalls,    [1]])
    precisions = np.concatenate([[0], precisions, [0]])
    for i in range(len(precisions)-2, -1, -1):
        precisions[i] = max(precisions[i], precisions[i+1])
    return np.sum((recalls[1:]-recalls[:-1]) * precisions[1:])

# Run on 5 images
img_items = list(img_lookup.items())[:5]
all_ap    = []
img_names = []

print(f"Running on 5 test images using ResNet50...\n")

fig, axes = plt.subplots(1, 5, figsize=(25, 5))

for idx, (img_id, fname) in enumerate(img_items):
    img_path = os.path.join(TEST_DIR, fname)
    image_g  = Image.open(img_path).convert("RGB")
    img_t    = transform(image_g).unsqueeze(0)

    with torch.no_grad():
        preds = backbone1(img_t)

    pred_boxes  = preds[0]['boxes'].numpy().tolist()
    pred_scores = preds[0]['scores'].numpy().tolist()
    gt_boxes    = ann_by_img.get(img_id, [])

    ap = compute_ap(pred_boxes, pred_scores, gt_boxes, iou_thr=0.5)
    all_ap.append(ap)
    img_names.append(f"Img {idx+1}")

    print(f"  Image {idx+1}: {fname}")
    print(f"    GT boxes: {len(gt_boxes)} | Predictions: {len([s for s in pred_scores if s>=0.5])} | AP: {ap:.3f}")

    # Draw on subplot
    axes[idx].imshow(image_g)
    for gt in gt_boxes:
        xmin,ymin,xmax,ymax = gt
        axes[idx].add_patch(patches.Rectangle((xmin,ymin), xmax-xmin, ymax-ymin,
            linewidth=2, edgecolor='lime', facecolor='none', linestyle='--'))
    for box, score in zip(pred_boxes, pred_scores):
        if score >= 0.5:
            xmin,ymin,xmax,ymax = box
            axes[idx].add_patch(patches.Rectangle((xmin,ymin), xmax-xmin, ymax-ymin,
                linewidth=2, edgecolor='red', facecolor='none'))
    axes[idx].set_title(f"Image {idx+1}\nAP={ap:.2f}", fontsize=10, fontweight='bold')
    axes[idx].axis('off')

plt.suptitle("Part 3 — 5 Guns Images\n Ground Truth   Predicted",
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# mAP bar + pie chart
mAP = np.mean(all_ap)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

bar_colors = ['#2ecc71' if ap >= 0.5 else '#e74c3c' for ap in all_ap]
axes[0].bar(img_names, all_ap, color=bar_colors, edgecolor='black')
axes[0].axhline(y=mAP, color='blue', linestyle='--', linewidth=2,
                label=f'mAP = {mAP:.3f}')
axes[0].set_ylim(0, 1.2)
axes[0].set_title("AP per Image", fontsize=12, fontweight='bold')
axes[0].set_ylabel("Average Precision")
axes[0].legend()
for i, ap in enumerate(all_ap):
    axes[0].text(i, ap+0.02, f"{ap:.2f}", ha='center', fontsize=11, fontweight='bold')

labels_pie = ['mAP Score', 'Remaining']
sizes_pie  = [mAP, 1-mAP]
colors_pie = ['#3498db', '#ecf0f1']
axes[1].pie(sizes_pie, labels=labels_pie, colors=colors_pie,
            autopct='%1.1f%%', startangle=90,
            textprops={'fontsize': 12, 'fontweight': 'bold'})
axes[1].set_title(f"Overall mAP = {mAP*100:.1f}%", fontsize=12, fontweight='bold')

plt.suptitle("Part 3 — mAP Results on 5 Guns Images",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# ── FINAL SUMMARY ──────────────────────────────────────────
print("\n" + "="*55)
print("         FINAL SUMMARY — TUTORIAL 8")
print("="*55)
print(f"  PART 1 — Faster RCNN on Lamborghini")
print(f"    Detections : {len(boxes)}")
print(f"    Precision  : {precision:.2f}")
print(f"    Recall     : {recall:.2f}")
print(f"    mAP        : {mAP_lamb:.2f}")
print(f"\n  PART 2 — Backbone Comparison")
print(f"    ResNet50     : {len(b1)} detections | {t1:.2f}s")
print(f"    ResNet50 V2  : {len(b2)} detections | {t2:.2f}s")
print(f"    MobileNetV3  : {len(b3)} detections | {t3:.2f}s")
print(f"\n  PART 3 — mAP on 5 Guns Images")
for name, ap in zip(img_names, all_ap):
    print(f"    {name}: AP = {ap:.3f}")
print(f"\n   Overall mAP@0.50 = {mAP:.4f} ({mAP*100:.1f}%)")
print("="*55)
rating =  "Excellent!" if mAP>=0.75 else " Good" if mAP>=0.50 else " Fair" if mAP>=0.25 else " Low"
print(f"  {rating}")



