# -*- coding: utf-8 -*-
"""RNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFGYEGhGmhNxYWnTa1QlGPMN_Ds17stE
"""

from google.colab import files
uploaded = files.upload()

# ============================================================
# TASK 2 — English → Urdu RNN (Full 1000-pair Dataset)
#           WITH TRAINING LOSS CURVE
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import openpyxl
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ─────────────────────────────────────────────
# 1. LOAD DATASET FROM XLSX
# ─────────────────────────────────────────────
def load_dataset(path):
    wb = openpyxl.load_workbook(path, read_only=True)
    ws = wb.active
    english, urdu = [], []
    first = True
    for row in ws.iter_rows(values_only=True):
        if first:
            first = False
            continue
        en, ur = row[0], row[1]
        if en and ur:
            english.append(str(en).strip().lower())
            urdu.append(str(ur).strip())
    wb.close()
    return english, urdu

english_sentences, urdu_sentences = load_dataset("english_urdu_1000.xlsx")
print(f"Loaded {len(english_sentences)} sentence pairs")

urdu_sentences = ["<sos> " + s + " <eos>" for s in urdu_sentences]

# ─────────────────────────────────────────────
# 2. BUILD VOCAB
# ─────────────────────────────────────────────
def build_vocab(sentences):
    vocab = {"<pad>": 0, "<sos>": 1, "<eos>": 2, "<unk>": 3}
    idx = 4
    for sent in sentences:
        for word in sent.split():
            if word not in vocab:
                vocab[word] = idx
                idx += 1
    return vocab

vocab_en = build_vocab(english_sentences)
vocab_ur = build_vocab(urdu_sentences)
inv_vocab_ur = {v: k for k, v in vocab_ur.items()}

print(f"English vocab size : {len(vocab_en)}")
print(f"Urdu vocab size    : {len(vocab_ur)}")

# ─────────────────────────────────────────────
# 3. ENCODE & PAD
# ─────────────────────────────────────────────
def encode(sentences, vocab):
    return [[vocab.get(w, vocab["<unk>"]) for w in s.split()] for s in sentences]

X_raw = encode(english_sentences, vocab_en)
y_raw = encode(urdu_sentences,    vocab_ur)

MAX_LEN = 20

def truncate_pad(seqs, max_len):
    result = []
    for s in seqs:
        s = s[:max_len]
        s = s + [0] * (max_len - len(s))
        result.append(s)
    return result

X_pad = truncate_pad(X_raw, MAX_LEN)
y_pad = truncate_pad(y_raw, MAX_LEN)

X = torch.tensor(X_pad, dtype=torch.long)
y = torch.tensor(y_pad, dtype=torch.long)

y_shift = torch.zeros_like(y)
y_shift[:, :-1] = y[:, 1:]

dataset = TensorDataset(X, y, y_shift)
loader  = DataLoader(dataset, batch_size=32, shuffle=True)

# ─────────────────────────────────────────────
# 4. MODEL
# ─────────────────────────────────────────────
class Encoder(nn.Module):
    def __init__(self, vocab_size, embed=256, hidden=512, dropout=0.3):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed, padding_idx=0)
        self.dropout   = nn.Dropout(dropout)
        self.rnn       = nn.GRU(embed, hidden, batch_first=True)

    def forward(self, x):
        x = self.dropout(self.embedding(x))
        _, hidden = self.rnn(x)
        return hidden


class Decoder(nn.Module):
    def __init__(self, vocab_size, embed=256, hidden=512, dropout=0.3):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed, padding_idx=0)
        self.dropout   = nn.Dropout(dropout)
        self.rnn       = nn.GRU(embed, hidden, batch_first=True)
        self.fc        = nn.Linear(hidden, vocab_size)

    def forward(self, x, hidden):
        x = self.dropout(self.embedding(x))
        output, hidden = self.rnn(x, hidden)
        output = self.fc(output)
        return output, hidden


class Seq2Seq(nn.Module):
    def __init__(self, enc, dec):
        super().__init__()
        self.encoder = enc
        self.decoder = dec

    def forward(self, src, tgt):
        hidden = self.encoder(src)
        output, _ = self.decoder(tgt, hidden)
        return output


model = Seq2Seq(
    Encoder(len(vocab_en)),
    Decoder(len(vocab_ur))
).to(device)

print(f"Model parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

criterion = nn.CrossEntropyLoss(ignore_index=0)
optimizer = optim.Adam(model.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=30, gamma=0.5)

# ─────────────────────────────────────────────
# 5. TRAIN  — record loss every epoch
# ─────────────────────────────────────────────
EPOCHS = 100
epoch_losses = []   # ← stores average loss per epoch

print("\n── Training ──")
for epoch in range(EPOCHS):
    model.train()
    total_loss = 0

    for src, tgt, tgt_shift in loader:
        src, tgt, tgt_shift = src.to(device), tgt.to(device), tgt_shift.to(device)

        optimizer.zero_grad()
        output = model(src, tgt)
        output = output.view(-1, output.shape[-1])
        tgt_shift = tgt_shift.view(-1)

        loss = criterion(output, tgt_shift)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        total_loss += loss.item()

    scheduler.step()

    avg_loss = total_loss / len(loader)
    epoch_losses.append(avg_loss)          # ← record it

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d}/{EPOCHS}  Loss: {avg_loss:.4f}  LR: {scheduler.get_last_lr()[0]:.6f}")

# ─────────────────────────────────────────────
# 6. PLOT TRAINING LOSS CURVE
# ─────────────────────────────────────────────
epochs_range = list(range(1, EPOCHS + 1))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("English → Urdu RNN — Training Curves", fontsize=14, fontweight="bold")

# --- Left: full loss curve ---
ax1 = axes[0]
ax1.plot(epochs_range, epoch_losses, color="#2196F3", linewidth=2, label="Train Loss")
ax1.set_title("Loss Over All Epochs")
ax1.set_xlabel("Epoch")
ax1.set_ylabel("Cross-Entropy Loss")
ax1.legend()
ax1.grid(True, linestyle="--", alpha=0.5)

# Mark the LR drop points (every 30 epochs)
for drop_epoch in [30, 60, 90]:
    if drop_epoch <= EPOCHS:
        ax1.axvline(x=drop_epoch, color="orange", linestyle="--", alpha=0.7,
                    label=f"LR drop @ {drop_epoch}")
ax1.legend()

# --- Right: log-scale loss curve (easier to see later epochs) ---
ax2 = axes[1]
ax2.plot(epochs_range, epoch_losses, color="#E91E63", linewidth=2, label="Train Loss (log scale)")
ax2.set_yscale("log")
ax2.set_title("Loss Over All Epochs (Log Scale)")
ax2.set_xlabel("Epoch")
ax2.set_ylabel("Loss (log)")
ax2.legend()
ax2.grid(True, which="both", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.savefig("training_curves.png", dpi=150, bbox_inches="tight")
plt.show()
print("Curves saved → training_curves.png")

# ─────────────────────────────────────────────
# 7. TRANSLATE
# ─────────────────────────────────────────────
def translate(sentence, max_out=30):
    model.eval()
    tokens = [vocab_en.get(w, vocab_en["<unk>"]) for w in sentence.lower().split()]
    tokens = (tokens + [0] * MAX_LEN)[:MAX_LEN]
    src = torch.tensor(tokens).unsqueeze(0).to(device)

    with torch.no_grad():
        hidden    = model.encoder(src)
        input_tok = torch.tensor([[vocab_ur["<sos>"]]]).to(device)
        result    = []

        for _ in range(max_out):
            output, hidden = model.decoder(input_tok, hidden)
            pred  = output.argmax(-1)[:, -1]
            word  = inv_vocab_ur.get(pred.item(), "")
            if word in ("<eos>", "<pad>"):
                break
            result.append(word)
            input_tok = pred.unsqueeze(0)

    return " ".join(result)

# ─────────────────────────────────────────────
# 8. TEST
# ─────────────────────────────────────────────
print("\n── Translation Demo ──")
for en in english_sentences[:10]:
    print(f"EN: {en}")
    print(f"UR: {translate(en)}")
    print()

# ============================================================
# FIXED BASELINE RNN — English → Urdu (PyTorch)
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ─────────────────────────────────────────────
# 1. SMALL DATASET (DEBUG FIRST)
# ─────────────────────────────────────────────
english_sentences = [
    "i love programming",
    "he goes to school",
    "she reads a book",
    "it is raining",
    "we are happy"
]

urdu_sentences = [
    "میں پروگرامنگ پسند کرتا ہوں",
    "وہ اسکول جاتا ہے",
    "وہ کتاب پڑھتی ہے",
    "بارش ہو رہی ہے",
    "ہم خوش ہیں"
]

# add special tokens
urdu_sentences = ["<sos> " + s + " <eos>" for s in urdu_sentences]

# ─────────────────────────────────────────────
# 2. BUILD VOCAB
# ─────────────────────────────────────────────
def build_vocab(sentences):
    vocab = {"<pad>": 0, "<sos>": 1, "<eos>": 2}
    idx = 3
    for sent in sentences:
        for word in sent.split():
            if word not in vocab:
                vocab[word] = idx
                idx += 1
    return vocab

vocab_en = build_vocab(english_sentences)
vocab_ur = build_vocab(urdu_sentences)

inv_vocab_ur = {v:k for k,v in vocab_ur.items()}

def encode(sentences, vocab):
    return [[vocab[w] for w in s.split()] for s in sentences]

X = encode(english_sentences, vocab_en)
y = encode(urdu_sentences, vocab_ur)

max_len = max(max(len(s) for s in X), max(len(s) for s in y))

def pad(seqs):
    return [s + [0]*(max_len - len(s)) for s in seqs]

X = torch.tensor(pad(X), dtype=torch.long)
y = torch.tensor(pad(y), dtype=torch.long)

# teacher forcing target
y_shift = torch.zeros_like(y)
y_shift[:, :-1] = y[:, 1:]

dataset = TensorDataset(X, y, y_shift)
loader = DataLoader(dataset, batch_size=2, shuffle=True)

# ─────────────────────────────────────────────
# 3. MODEL
# ─────────────────────────────────────────────
class Encoder(nn.Module):
    def __init__(self, vocab_size, embed=128, hidden=256):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed)
        self.rnn = nn.RNN(embed, hidden, batch_first=True)

    def forward(self, x):
        x = self.embedding(x)
        _, hidden = self.rnn(x)
        return hidden


class Decoder(nn.Module):
    def __init__(self, vocab_size, embed=128, hidden=256):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed)
        self.rnn = nn.RNN(embed, hidden, batch_first=True)
        self.fc = nn.Linear(hidden, vocab_size)

    def forward(self, x, hidden):
        x = self.embedding(x)
        output, hidden = self.rnn(x, hidden)
        output = self.fc(output)
        return output, hidden


class Seq2Seq(nn.Module):
    def __init__(self, enc, dec):
        super().__init__()
        self.encoder = enc
        self.decoder = dec

    def forward(self, src, tgt):
        hidden = self.encoder(src)
        output, _ = self.decoder(tgt, hidden)
        return output


model = Seq2Seq(
    Encoder(len(vocab_en)),
    Decoder(len(vocab_ur))
).to(device)

criterion = nn.CrossEntropyLoss(ignore_index=0)
optimizer = optim.Adam(model.parameters(), lr=0.001)

# ─────────────────────────────────────────────
# 4. TRAIN
# ─────────────────────────────────────────────
for epoch in range(200):
    model.train()
    total_loss = 0

    for src, tgt, tgt_shift in loader:
        src, tgt, tgt_shift = src.to(device), tgt.to(device), tgt_shift.to(device)

        optimizer.zero_grad()

        output = model(src, tgt)
        output = output.view(-1, output.shape[-1])
        tgt_shift = tgt_shift.view(-1)

        loss = criterion(output, tgt_shift)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    if (epoch+1) % 20 == 0:
        print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader):.4f}")

# ─────────────────────────────────────────────
# 5. CORRECT TRANSLATION (STEP-BY-STEP)
# ─────────────────────────────────────────────
def translate(sentence):
    model.eval()

    tokens = [vocab_en.get(w, 0) for w in sentence.lower().split()]
    tokens += [0]*(max_len - len(tokens))

    src = torch.tensor(tokens).unsqueeze(0).to(device)

    with torch.no_grad():
        hidden = model.encoder(src)

        input_token = torch.tensor([[vocab_ur["<sos>"]]]).to(device)
        result = []

        for _ in range(max_len):
            output, hidden = model.decoder(input_token, hidden)
            pred = output.argmax(-1)[:, -1]

            word = inv_vocab_ur.get(pred.item(), "")

            if word == "<eos>":
                break

            result.append(word)
            input_token = pred.unsqueeze(0)

    return " ".join(result)

# ─────────────────────────────────────────────
# 6. TEST
# ─────────────────────────────────────────────
print("\n── Translation Demo ──")

tests = [
    "i love programming",
    "he goes to school",
    "she reads a book",
    "it is raining",
    "we are happy"
]

for t in tests:
    print("EN:", t)
    print("UR:", translate(t))
    print()

# ================================================================
#  TASK 3 — One-to-Many RNN: Pakistani Baby Name Generation
#  Tutorial 14_B | Deep Learning Lab
# ================================================================
#
#  ONE-TO-MANY ARCHITECTURE:
#
#   One input (start token / seed letter)
#       |
#       v
#   [RNN cell] --h1--> [RNN cell] --h2--> [RNN cell] --h3--> ...
#       |                   |                   |
#       v                   v                   v
#      'f'                 'a'                 't'     -->  "fatima"
#
#  At each step the model predicts ONE next character.
#  That character is fed back as input to produce the next one.
#  This is the "one-to-many" pattern: one seed -> many outputs.
#
# ================================================================

import torch
import torch.nn as nn
import torch.optim as optim
import string
import random
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ────────────────────────────────────────────────────────────────
# SECTION 1 — DATASET
# Pakistani baby names (boys + girls)
# ────────────────────────────────────────────────────────────────
baby_names = [
    # Boys
    "ali", "ahmed", "usman", "hassan", "hussain", "zain", "bilal", "hamza",
    "omar", "rayan", "ibrahim", "yusuf", "tariq", "imran", "kamran", "salman",
    "faisal", "adnan", "danish", "waqar", "umer", "talha", "saad", "asad",
    "shahid", "nabeel", "farhan", "rehan", "aqib", "wahab", "junaid", "shoaib",
    "aamir", "arshad", "babar", "daud", "ehsan", "fahad", "haroon",
    "ijaz", "jalal", "khurram", "luqman", "mubashir", "nauman", "owais",
    "qasim", "rafiq", "sajid", "uzair", "waseem", "yasin",
    "zafar", "zubair", "zahid", "zeeshan", "zia", "zaid", "zaeem",
    "amir", "anwar", "akram", "arif", "asif", "atif",
    "azhar", "azan", "afzal", "ahsan", "ajmal", "amjad",
    "basit", "burhan", "daniyal", "farrukh", "fawad",
    "haider", "hammad", "humayun", "ilyas", "irfan", "ismail",
    "kashif", "khalid", "mansoor", "murad", "mustafa", "murtaza",
    "nasir", "naveed", "noman", "nouman", "raees",
    "ramzan", "rashid", "rizwan", "saeed", "shaheen",
    "shahzad", "shakeel", "siraj", "sohail", "subhan",
    "taimur", "tanveer", "tahir", "umar", "usama",
    "wajid", "waleed", "yasir", "zaheer", "zakir", "zaman",
    # Girls
    "sara", "hira", "maria", "aisha", "fatima", "zainab", "maryam", "sana",
    "noor", "amna", "hana", "laiba", "mahnoor", "eman", "areeba", "minahil",
    "nimra", "ramsha", "aliza", "rabia", "khadija", "asma", "nadia", "saima",
    "bushra", "fariha", "gulnaz", "humaira", "iram", "javeria",
    "lubna", "mahvish", "naila", "rida", "shabana", "tabassum",
    "uzma", "warda", "yasmeen", "zara", "zahra", "zahira",
    "zoya", "zoha", "zimal", "zeynep",
    "aqsa", "anisa", "azka", "afra", "alia", "anum", "ayesha",
    "ambreen", "abeera", "abeer", "arwa", "aina", "amira",
    "bakhtawar", "bisma", "farah", "fareeda", "farida", "fauzia",
    "ghazala", "gulshan", "hajra", "haleema", "hamna",
    "inaya", "iqra", "isra", "kainaat", "kinza",
    "maha", "maheen", "madiha", "malika", "marwa",
    "mehwish", "memoona", "muniba", "muskan",
    "nabeela", "nabila", "nafeesa", "najma", "nasreen",
    "palwasha", "qudsia", "rohma", "roohi",
    "rubab", "rukhsar", "sahar", "sahira",
    "samia", "samina", "sehar", "shabnam", "shaista",
    "sobia", "soha", "sumbal", "sumera", "sundas",
    "tahira", "tooba", "urooj", "wajiha",
    "wardah", "yumna", "zeba", "zeenat", "zunaira",
]

baby_names = list(set(baby_names))
print(f"Total unique names  : {len(baby_names)}")

# ────────────────────────────────────────────────────────────────
# SECTION 2 — CHARACTER VOCABULARY
#
#  CHARS = ['<eos>', 'a', 'b', ..., 'z']  (27 tokens total)
#  <eos> is the special end-of-name token (index 0)
# ────────────────────────────────────────────────────────────────
CHARS      = ["<eos>"] + list(string.ascii_lowercase)
ch2idx     = {c: i for i, c in enumerate(CHARS)}
idx2ch     = {i: c for c, i in ch2idx.items()}
EOS_IDX    = ch2idx["<eos>"]
VOCAB_SIZE = len(CHARS)       # 27
print(f"Vocabulary size     : {VOCAB_SIZE}  {CHARS}")

# ────────────────────────────────────────────────────────────────
# SECTION 3 — BUILD TRAINING SAMPLES
#
#  For each name every (prefix → next_char) pair is one sample.
#  Example for "sara":
#    []          -> s
#    [s]         -> a
#    [s, a]      -> r
#    [s, a, r]   -> a
#    [s, a, r, a]-> <eos>
#
#  ~240 names × ~6 chars ≈ 1500 training pairs
# ────────────────────────────────────────────────────────────────
def make_samples(names):
    xs, ys = [], []
    for name in names:
        encoded = [ch2idx[c] for c in name.lower() if c in ch2idx]
        targets = encoded + [EOS_IDX]
        for i, target in enumerate(targets):
            xs.append(encoded[:i])   # prefix (may be empty)
            ys.append(target)        # next character to predict
    return xs, ys

raw_xs, raw_ys = make_samples(baby_names)
pairs = list(zip(raw_xs, raw_ys))
print(f"Training pairs      : {len(pairs)}")

# ────────────────────────────────────────────────────────────────
# SECTION 4 — MODEL DEFINITION
#
#  Input → Embedding → GRU → Dropout → Linear → Next-char logits
#
#  Why GRU instead of SimpleRNN?
#    GRU has gating (reset + update gates) so it remembers longer
#    patterns without vanishing gradients.
#
#  Dropout (0.4) + L2 weight_decay prevent the model from
#  memorising only the training names (the "Aaaaaa" repeating bug).
# ────────────────────────────────────────────────────────────────
class NameRNN(nn.Module):
    def __init__(self, vocab_size, embed_dim=16, hidden_dim=128):
        super().__init__()
        # Extra embedding slot for the learnable START token
        self.START_IDX = vocab_size
        self.embedding = nn.Embedding(vocab_size + 1, embed_dim)
        self.rnn       = nn.GRU(embed_dim, hidden_dim, batch_first=True)
        self.drop      = nn.Dropout(0.4)
        self.fc        = nn.Linear(hidden_dim, vocab_size)

    def forward(self, bx):
        """Training mode: full prefix sequence -> next char logit."""
        emb    = self.embedding(bx)           # (B, T, embed_dim)
        out, _ = self.rnn(emb)               # (B, T, hidden_dim)
        last   = self.drop(out[:, -1, :])    # take last time-step
        return self.fc(last)                  # (B, vocab_size)

    def forward_single(self, prefix_indices):
        """Generation mode: predict next char from current prefix."""
        tokens = [self.START_IDX] + list(prefix_indices)
        x      = torch.tensor([tokens], dtype=torch.long,
                               device=next(self.parameters()).device)
        emb    = self.embedding(x)
        out, _ = self.rnn(emb)
        last   = self.drop(out[:, -1, :])
        return self.fc(last)

model     = NameRNN(VOCAB_SIZE).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.002, weight_decay=1e-3)

print(f"Model parameters    : {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

# ────────────────────────────────────────────────────────────────
# SECTION 5 — TRAINING LOOP
# ────────────────────────────────────────────────────────────────
EPOCHS       = 200
BATCH_SIZE   = 64
epoch_losses = []

print("\n── Training ──")
for epoch in range(EPOCHS):
    model.train()
    random.shuffle(pairs)
    total_loss, steps = 0, 0

    for i in range(0, len(pairs), BATCH_SIZE):
        batch = pairs[i : i + BATCH_SIZE]
        # Pad all prefixes in the batch to the same length
        max_t = max(len(x) for x, _ in batch) + 1

        batch_x, batch_y = [], []
        for x_seq, y in batch:
            tokens = [model.START_IDX] + list(x_seq)
            # Left-pad with START token so all sequences = max_t
            padded = [model.START_IDX] * (max_t - len(tokens)) + tokens
            batch_x.append(padded)
            batch_y.append(y)

        bx = torch.tensor(batch_x, dtype=torch.long).to(device)
        by = torch.tensor(batch_y, dtype=torch.long).to(device)

        optimizer.zero_grad()
        logits = model(bx)
        loss   = criterion(logits, by)
        loss.backward()
        # Gradient clipping prevents exploding gradients
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        total_loss += loss.item()
        steps      += 1

    avg = total_loss / steps
    epoch_losses.append(avg)
    if (epoch + 1) % 25 == 0:
        print(f"Epoch {epoch+1:3d}/{EPOCHS}   Loss: {avg:.4f}")

# ────────────────────────────────────────────────────────────────
# SECTION 6 — NAME GENERATION  (One-to-Many inference)
#
#  HOW IT WORKS:
#    1. User provides ONE seed letter  (the "one" input)
#    2. Model outputs next-character probabilities
#    3. Sample from the distribution using temperature scaling
#    4. Feed that character back as input  (the "many" loop)
#    5. Stop when <eos> is predicted or max_len is reached
#
#  TEMPERATURE controls creativity:
#    Low  (0.4) → conservative, sounds like real names
#    High (1.1) → creative and novel, may be unusual
# ────────────────────────────────────────────────────────────────
def generate_name(seed_char=None, temperature=0.8, max_len=12):
    """
    Generate a baby name.

    Args:
        seed_char   : starting letter, e.g. 'a'. None = random start.
        temperature : creativity (0.4 = safe, 1.1 = creative).
        max_len     : maximum name length.

    Returns:
        Capitalised name string.
    """
    model.eval()
    with torch.no_grad():
        generated = []

        # If a seed letter is given, start with it
        if seed_char and seed_char.lower() in ch2idx:
            generated.append(ch2idx[seed_char.lower()])

        for _ in range(max_len):
            logits = model.forward_single(generated)[0] / temperature
            probs  = torch.softmax(logits, dim=-1)
            nxt    = torch.multinomial(probs, 1).item()
            if nxt == EOS_IDX:
                break
            generated.append(nxt)

    name = "".join(idx2ch[i] for i in generated)
    return name.capitalize() if name else "???"

# ────────────────────────────────────────────────────────────────
# SECTION 7 — DEMO: ask the user for a letter then generate names
# ────────────────────────────────────────────────────────────────
print("\n" + "="*55)
print("  PAKISTANI BABY NAME GENERATOR")
print("="*55)

# --- Interactive mode -------------------------------------------
while True:
    user_input = input(
        "\nEnter a starting letter (a-z) or press ENTER for random, Q to quit: "
    ).strip().lower()

    if user_input == 'q':
        print("Goodbye!")
        break

    seed = user_input[0] if user_input and user_input[0].isalpha() else None

    try:
        temp_input = input("Enter temperature (0.4=safe, 0.8=default, 1.1=creative): ").strip()
        temperature = float(temp_input) if temp_input else 0.8
        temperature = max(0.1, min(2.0, temperature))   # clamp to safe range
    except ValueError:
        temperature = 0.8

    print(f"\n  Generating names starting with "
          f"'{seed.upper() if seed else 'random'}' "
          f"at temperature {temperature:.1f}:\n")

    for i in range(10):
        name = generate_name(seed_char=seed, temperature=temperature)
        print(f"    {i+1:2d}. {name}")

# ────────────────────────────────────────────────────────────────
# SECTION 8 — TRAINING CURVES
# ────────────────────────────────────────────────────────────────
epochs_range = list(range(1, EPOCHS + 1))
fig, axes = plt.subplots(1, 2, figsize=(13, 4))
fig.suptitle("Task 3 — Baby Name RNN Training Curves",
             fontsize=13, fontweight="bold")

axes[0].plot(epochs_range, epoch_losses, color="#e91e63", linewidth=1.8)
axes[0].set_title("Training Loss (Linear Scale)")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Cross-Entropy Loss")
axes[0].grid(True, linestyle="--", alpha=0.4)

axes[1].plot(epochs_range, epoch_losses, color="#9c27b0", linewidth=1.8)
axes[1].set_yscale("log")
axes[1].set_title("Training Loss (Log Scale)")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Loss (log)")
axes[1].grid(True, which="both", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.savefig("baby_name_training_curves.png", dpi=150, bbox_inches="tight")
plt.show()
print("Training curves saved → baby_name_training_curves.png")