# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjIxARxNAojBz2CpKiKauQbqyU0cK1SS
"""

"""
Tutorial 15 - LSTM Stock Price Prediction (PyTorch)
Dataset: Google (GOOGL) stock from Yahoo Finance
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import MinMaxScaler

torch.manual_seed(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ── 1. FETCH DATA ─────────────────────────────────────────────
df = yf.download('GOOGL', start='2010-01-01', end='2024-12-01')
print(df.head())

data = df['Close'].values.reshape(-1, 1)
print(f"Total data points: {len(data)}")

# ── 2. PREPROCESS ─────────────────────────────────────────────
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)

train_size = int(len(scaled_data) * 0.8)
train_data = scaled_data[:train_size]
test_data  = scaled_data[train_size:]

def create_sequences(data, sequence_length):
    X, y = [], []
    for i in range(len(data) - sequence_length):
        X.append(data[i : i + sequence_length])
        y.append(data[i + sequence_length])
    return np.array(X), np.array(y)

sequence_length = 60
X_train, y_train = create_sequences(train_data, sequence_length)
X_test,  y_test  = create_sequences(test_data,  sequence_length)
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")

# Convert to tensors
X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_t = torch.tensor(y_train, dtype=torch.float32).to(device)
X_test_t  = torch.tensor(X_test,  dtype=torch.float32).to(device)
y_test_t  = torch.tensor(y_test,  dtype=torch.float32).to(device)

train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=32, shuffle=True)

# ── 3. BUILD LSTM MODEL ───────────────────────────────────────
class LSTMModel(nn.Module):
    def __init__(self, input_size=1, hidden_size=50, num_layers=2, output_size=1):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers,
                            batch_first=True, dropout=0.2)
        self.fc1  = nn.Linear(hidden_size, 25)
        self.fc2  = nn.Linear(25, output_size)
        self.relu = nn.ReLU()

    def forward(self, x):
        out, _ = self.lstm(x)
        out = out[:, -1, :]          # take last timestep
        out = self.relu(self.fc1(out))
        out = self.fc2(out)
        return out

model     = LSTMModel().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()
print(model)

# ── 4. TRAIN ──────────────────────────────────────────────────
EPOCHS = 10
for epoch in range(EPOCHS):
    model.train()
    epoch_loss = 0.0
    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        preds = model(X_batch)
        loss  = criterion(preds, y_batch)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item() * len(X_batch)
    epoch_loss /= len(X_train_t)

    model.eval()
    with torch.no_grad():
        val_loss = criterion(model(X_test_t), y_test_t).item()

    print(f"Epoch {epoch+1}/{EPOCHS} | Train Loss: {epoch_loss:.6f} | Val Loss: {val_loss:.6f}")

# ── 5. EVALUATE & VISUALIZE ───────────────────────────────────
model.eval()
with torch.no_grad():
    predictions = model(X_test_t).cpu().numpy()

predictions_rescaled = scaler.inverse_transform(predictions)
y_test_rescaled      = scaler.inverse_transform(y_test.reshape(-1, 1))

plt.figure(figsize=(14, 6))
plt.plot(y_test_rescaled,      label='Actual Price',    color='blue')
plt.plot(predictions_rescaled, label='Predicted Price', color='red')
plt.title('GOOGL Stock Price Prediction — LSTM')
plt.xlabel('Days')
plt.ylabel('Price (USD)')
plt.legend()
plt.tight_layout()
plt.savefig('lstm_stock_prediction.png', dpi=150)
plt.show()

# ── 6. PREDICT NEXT DAY ───────────────────────────────────────
last_sequence   = scaled_data[-sequence_length:].reshape(1, sequence_length, 1)
last_seq_tensor = torch.tensor(last_sequence, dtype=torch.float32).to(device)

model.eval()
with torch.no_grad():
    next_scaled = model(last_seq_tensor).cpu().numpy()

next_day_price = scaler.inverse_transform(next_scaled)
print(f"\nPredicted next day's price for GOOGL: ${next_day_price[0][0]:.2f}")

"""
Task 1 - Compare LSTM vs Simple RNN on Stock Price Prediction (PyTorch)
Run task1_lstm_stock.py first so the LSTM results are available to compare.
This file trains a Simple RNN on the SAME data and plots both side by side.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

torch.manual_seed(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ── 1. DATA (same as tutorial) ────────────────────────────────
df          = yf.download('GOOGL', start='2010-01-01', end='2024-12-01')
data        = df['Close'].values.reshape(-1, 1)
scaler      = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)

train_size  = int(len(scaled_data) * 0.8)
train_data  = scaled_data[:train_size]
test_data   = scaled_data[train_size:]

def create_sequences(data, seq_len):
    X, y = [], []
    for i in range(len(data) - seq_len):
        X.append(data[i : i + seq_len])
        y.append(data[i + seq_len])
    return np.array(X), np.array(y)

SEQ_LEN = 60
X_train, y_train = create_sequences(train_data, SEQ_LEN)
X_test,  y_test  = create_sequences(test_data,  SEQ_LEN)

X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_t = torch.tensor(y_train, dtype=torch.float32).to(device)
X_test_t  = torch.tensor(X_test,  dtype=torch.float32).to(device)
y_test_t  = torch.tensor(y_test,  dtype=torch.float32).to(device)

train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=32, shuffle=True)

# ── 2. MODELS ─────────────────────────────────────────────────
class LSTMModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(1, 50, 2, batch_first=True, dropout=0.2)
        self.fc1  = nn.Linear(50, 25)
        self.fc2  = nn.Linear(25, 1)
        self.relu = nn.ReLU()
    def forward(self, x):
        out, _ = self.lstm(x)
        return self.fc2(self.relu(self.fc1(out[:, -1, :])))

class SimpleRNNModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.rnn = nn.RNN(1, 50, 2, batch_first=True, dropout=0.2)
        self.fc1 = nn.Linear(50, 25)
        self.fc2 = nn.Linear(25, 1)
        self.relu= nn.ReLU()
    def forward(self, x):
        out, _ = self.rnn(x)
        return self.fc2(self.relu(self.fc1(out[:, -1, :])))

criterion = nn.MSELoss()
EPOCHS    = 10

# ── 3. TRAIN FUNCTION ─────────────────────────────────────────
def train_model(model, name):
    model     = model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    tr_losses, val_losses = [], []

    print(f"\n{'='*50}\nTraining {name}\n{'='*50}")
    for epoch in range(EPOCHS):
        model.train()
        ep_loss = 0.0
        for Xb, yb in train_loader:
            optimizer.zero_grad()
            loss = criterion(model(Xb), yb)
            loss.backward()
            optimizer.step()
            ep_loss += loss.item() * len(Xb)
        ep_loss /= len(X_train_t)
        tr_losses.append(ep_loss)

        model.eval()
        with torch.no_grad():
            v_loss = criterion(model(X_test_t), y_test_t).item()
        val_losses.append(v_loss)
        print(f"Epoch {epoch+1}/{EPOCHS} | Train: {ep_loss:.6f} | Val: {v_loss:.6f}")

    return model, tr_losses, val_losses

lstm_model, lstm_tl, lstm_vl = train_model(LSTMModel(),     "LSTM")
rnn_model,  rnn_tl,  rnn_vl  = train_model(SimpleRNNModel(), "Simple RNN")

# ── 4. EVALUATE BOTH ──────────────────────────────────────────
def get_predictions(model):
    model.eval()
    with torch.no_grad():
        preds = model(X_test_t).cpu().numpy()
    return scaler.inverse_transform(preds)

y_actual         = scaler.inverse_transform(y_test.reshape(-1, 1))
lstm_preds       = get_predictions(lstm_model)
rnn_preds        = get_predictions(rnn_model)

lstm_rmse = np.sqrt(mean_squared_error(y_actual, lstm_preds))
rnn_rmse  = np.sqrt(mean_squared_error(y_actual, rnn_preds))
print(f"\nLSTM RMSE: {lstm_rmse:.4f}")
print(f"RNN  RMSE: {rnn_rmse:.4f}")
print(f"Winner: {'LSTM' if lstm_rmse < rnn_rmse else 'Simple RNN'}")

# ── 5. PLOTS ──────────────────────────────────────────────────
# Side-by-side predictions
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

axes[0].plot(y_actual,    label='Actual', color='blue')
axes[0].plot(rnn_preds,   label='Predicted', color='orange')
axes[0].set_title(f'Simple RNN  (RMSE: {rnn_rmse:.2f})')
axes[0].set_xlabel('Days'); axes[0].set_ylabel('Price (USD)'); axes[0].legend()

axes[1].plot(y_actual,    label='Actual', color='blue')
axes[1].plot(lstm_preds,  label='Predicted', color='red')
axes[1].set_title(f'LSTM  (RMSE: {lstm_rmse:.2f})')
axes[1].set_xlabel('Days'); axes[1].set_ylabel('Price (USD)'); axes[1].legend()

plt.suptitle('GOOGL Stock Price: Simple RNN vs LSTM', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('rnn_vs_lstm_stock.png', dpi=150)
plt.show()

# Loss curves comparison
plt.figure(figsize=(10, 4))
ep = range(1, EPOCHS + 1)
plt.plot(ep, rnn_tl,  'r--', label='RNN  Train Loss')
plt.plot(ep, rnn_vl,  'r-',  label='RNN  Val Loss')
plt.plot(ep, lstm_tl, 'b--', label='LSTM Train Loss')
plt.plot(ep, lstm_vl, 'b-',  label='LSTM Val Loss')
plt.title('Training & Validation Loss: RNN vs LSTM')
plt.xlabel('Epoch'); plt.ylabel('MSE Loss')
plt.legend(); plt.tight_layout()
plt.savefig('rnn_vs_lstm_loss.png', dpi=150)
plt.show()

# RMSE bar chart
plt.figure(figsize=(6, 4))
bars = plt.bar(['Simple RNN', 'LSTM'], [rnn_rmse, lstm_rmse],
               color=['#e74c3c', '#2980b9'], edgecolor='black', width=0.4)
for bar, v in zip(bars, [rnn_rmse, lstm_rmse]):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
             f'{v:.2f}', ha='center', fontweight='bold')
plt.title('RMSE Comparison: Simple RNN vs LSTM')
plt.ylabel('RMSE'); plt.tight_layout()
plt.savefig('rnn_vs_lstm_rmse.png', dpi=150)
plt.show()

"""
Task 2 - LSTM for Sentiment Analysis (PyTorch)
Dataset: IMDB Movie Reviews (via Keras built-in — 25,000 reviews)
Labels:  1 = Positive  |  0 = Negative
"""

import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences

torch.manual_seed(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ── 1. LOAD IMDB DATA ─────────────────────────────────────────
VOCAB_SIZE = 10000
MAX_LEN    = 200

print("Loading IMDB dataset...")
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=VOCAB_SIZE)
print(f"Train: {len(X_train)} reviews | Test: {len(X_test)} reviews")
print(f"Sample (encoded): {X_train[0][:10]} ... Label: {y_train[0]}")

# Pad sequences to same length
X_train = pad_sequences(X_train, maxlen=MAX_LEN, padding='post', truncating='post')
X_test  = pad_sequences(X_test,  maxlen=MAX_LEN, padding='post', truncating='post')
print(f"\nAfter padding — X_train: {X_train.shape} | X_test: {X_test.shape}")

# Convert to tensors
X_train_t = torch.tensor(X_train, dtype=torch.long)
y_train_t = torch.tensor(y_train, dtype=torch.float32)
X_test_t  = torch.tensor(X_test,  dtype=torch.long)
y_test_t  = torch.tensor(y_test,  dtype=torch.float32)

train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=64, shuffle=True)
test_loader  = DataLoader(TensorDataset(X_test_t,  y_test_t),  batch_size=64, shuffle=False)

# ── 2. LSTM SENTIMENT MODEL ───────────────────────────────────
class LSTMSentiment(nn.Module):
    def __init__(self, vocab_size=VOCAB_SIZE, embed_dim=64,
                 hidden_size=128, num_layers=2):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.lstm      = nn.LSTM(embed_dim, hidden_size, num_layers,
                                 batch_first=True, dropout=0.3)
        self.dropout   = nn.Dropout(0.4)
        self.fc        = nn.Linear(hidden_size, 1)

    def forward(self, x):
        emb = self.embedding(x)
        _, (hn, _) = self.lstm(emb)   # hn: [num_layers, batch, hidden]
        out = self.dropout(hn[-1])    # take last layer hidden state
        return self.fc(out).squeeze(1)

model     = LSTMSentiment().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.BCEWithLogitsLoss()
print(f"\nModel:\n{model}")

# ── 3. TRAIN ──────────────────────────────────────────────────
EPOCHS = 10
train_losses, val_losses = [], []
train_accs,   val_accs   = [], []

for epoch in range(EPOCHS):
    # Train
    model.train()
    t_loss = correct = total = 0
    for Xb, yb in train_loader:
        Xb, yb = Xb.to(device), yb.to(device)
        optimizer.zero_grad()
        logits = model(Xb)
        loss   = criterion(logits, yb)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        t_loss  += loss.item() * len(yb)
        preds    = (torch.sigmoid(logits) >= 0.5).long()
        correct += (preds == yb.long()).sum().item()
        total   += len(yb)
    train_losses.append(t_loss / total)
    train_accs.append(correct / total)

    # Validate
    model.eval()
    v_loss = correct = total = 0
    with torch.no_grad():
        for Xb, yb in test_loader:
            Xb, yb = Xb.to(device), yb.to(device)
            logits  = model(Xb)
            v_loss += criterion(logits, yb).item() * len(yb)
            preds   = (torch.sigmoid(logits) >= 0.5).long()
            correct+= (preds == yb.long()).sum().item()
            total  += len(yb)
    val_losses.append(v_loss / total)
    val_accs.append(correct / total)

    print(f"Epoch {epoch+1}/{EPOCHS} | "
          f"Train Loss: {train_losses[-1]:.4f}  Acc: {train_accs[-1]*100:.2f}% | "
          f"Val Loss: {val_losses[-1]:.4f}  Acc: {val_accs[-1]*100:.2f}%")

# ── 4. VISUALIZE ──────────────────────────────────────────────
ep = range(1, EPOCHS + 1)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(ep, train_losses, 'b-o', label='Train Loss')
axes[0].plot(ep, val_losses,   'r-o', label='Val Loss')
axes[0].set_title('Loss over Epochs'); axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('BCE Loss'); axes[0].legend(); axes[0].grid(True)

axes[1].plot(ep, [a*100 for a in train_accs], 'b-o', label='Train Acc')
axes[1].plot(ep, [a*100 for a in val_accs],   'r-o', label='Val Acc')
axes[1].set_title('Accuracy over Epochs'); axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy (%)'); axes[1].legend(); axes[1].grid(True)

plt.suptitle('LSTM Sentiment Analysis — IMDB Reviews', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('lstm_sentiment.png', dpi=150)
plt.show()

print(f"\nFinal Test Accuracy: {val_accs[-1]*100:.2f}%")

# ── 5. INFERENCE ON CUSTOM REVIEWS ───────────────────────────
word_index = imdb.get_word_index()

def predict_sentiment(text, model, word_index, max_len=MAX_LEN):
    model.eval()
    tokens = text.lower().split()
    ids    = [word_index.get(w, 2) + 3 for w in tokens]   # +3 IMDB offset
    ids    = [i if i < VOCAB_SIZE else 2 for i in ids]
    ids   += [0] * (max_len - len(ids))
    ids    = ids[:max_len]
    tensor = torch.tensor([ids], dtype=torch.long).to(device)
    with torch.no_grad():
        prob = torch.sigmoid(model(tensor)).item()
    label = "POSITIVE " if prob >= 0.5 else "NEGATIVE "
    return label, prob

reviews = [
    "This movie was absolutely brilliant I loved every moment",
    "Terrible film complete waste of time boring and awful",
    "One of the best films I have seen in years highly recommend",
    "I walked out halfway through it was that bad",
    "The acting was decent but the story felt a bit slow",
]

print("\n--- Custom Review Predictions ---")
for review in reviews:
    label, prob = predict_sentiment(review, model, word_index)
    print(f"Review : '{review}'")
    print(f"Result : {label}  (confidence: {prob:.2f})\n")