# -*- coding: utf-8 -*-
"""Scratch Models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2H8DLVyhJSfBqJFzWxgzQfI8659m3Rj
"""

!pip install roboflow ultralytics pycocotools -q

from roboflow import Roboflow
rf = Roboflow(api_key="A2YllykE6xoTtfId5TZT")
project = rf.workspace("baheejs-workspace").project("guns-ldyqf")
dataset = project.version(9).download("coco")
print("Done!")

import os
print(os.listdir("/content/Guns-9/train"))

# ================================================================
#   RELOAD SAVED MODELS + FIXED VISUALIZATION ONLY
#   (No retraining — just load saved weights)
# ================================================================

import torch
import torch.nn as nn
import torchvision.transforms as T
from torch.utils.data import Dataset, DataLoader
from PIL import Image
from pycocotools.coco import COCO
import os, json, cv2
import numpy as np
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ── Paths ──────────────────────────────────────────────────
DATASET_ROOT = "/content/Guns-9"
TRAIN_DIR    = os.path.join(DATASET_ROOT, "train")
VALID_DIR    = os.path.join(DATASET_ROOT, "valid")
TEST_DIR     = os.path.join(DATASET_ROOT, "test")
TRAIN_JSON   = os.path.join(TRAIN_DIR, "_annotations.coco.json")
VALID_JSON   = os.path.join(VALID_DIR, "_annotations.coco.json")
TEST_JSON    = os.path.join(TEST_DIR,  "_annotations.coco.json")
RESULTS_DIR  = "/content/results_scratch"

SSD_SAVE  = f"{RESULTS_DIR}/ssd_scratch.pth"
YOLO_SAVE = f"{RESULTS_DIR}/yolo_scratch.pth"

# ── Check saved models exist ───────────────────────────────
print(f"SSD model exists : {os.path.exists(SSD_SAVE)}")
print(f"YOLO model exists: {os.path.exists(YOLO_SAVE)}")

# ── Dataset ────────────────────────────────────────────────
class GunsDataset(Dataset):
    def __init__(self, img_dir, ann_file, img_size=300):
        self.img_dir  = img_dir
        self.img_size = img_size
        self.coco     = COCO(ann_file)
        self.img_ids  = list(self.coco.imgs.keys())
        self.tf       = T.Compose([T.Resize((img_size, img_size)), T.ToTensor()])
        print(f"  Loaded {len(self.img_ids)} images")

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_id   = self.img_ids[idx]
        img_info = self.coco.imgs[img_id]
        image    = Image.open(os.path.join(self.img_dir,
                    img_info["file_name"])).convert("RGB")
        W0, H0   = image.size
        image    = self.tf(image)
        anns = self.coco.loadAnns(self.coco.getAnnIds(imgIds=img_id))
        boxes, labels = [], []
        for ann in anns:
            x, y, w, h = ann["bbox"]
            x1 = x/W0; y1 = y/H0
            x2 = (x+w)/W0; y2 = (y+h)/H0
            if w > 1 and h > 1:
                boxes.append([x1, y1, x2, y2])
                labels.append(1)
        if len(boxes) == 0:
            boxes  = torch.zeros((0,4), dtype=torch.float32)
            labels = torch.zeros((0,),  dtype=torch.int64)
        else:
            boxes  = torch.tensor(boxes,  dtype=torch.float32)
            labels = torch.tensor(labels, dtype=torch.int64)
        return image, {"boxes": boxes, "labels": labels,
                       "image_id": torch.tensor([img_id])}

def collate_fn(batch):
    return tuple(zip(*batch))

test_ds      = GunsDataset(TEST_DIR, TEST_JSON, img_size=300)
test_ds_yolo = GunsDataset(TEST_DIR, TEST_JSON, img_size=416)

# ── Rebuild SSD model ──────────────────────────────────────
class SSDBackbone(nn.Module):
    def __init__(self):
        super().__init__()
        self.block1 = nn.Sequential(nn.Conv2d(3,32,3,padding=1),nn.BatchNorm2d(32),nn.ReLU(),nn.MaxPool2d(2,2))
        self.block2 = nn.Sequential(nn.Conv2d(32,64,3,padding=1),nn.BatchNorm2d(64),nn.ReLU(),nn.MaxPool2d(2,2))
        self.block3 = nn.Sequential(nn.Conv2d(64,128,3,padding=1),nn.BatchNorm2d(128),nn.ReLU())
    def forward(self, x):
        return self.block3(self.block2(self.block1(x)))

class SSDHead(nn.Module):
    def __init__(self, in_ch, num_classes, num_boxes):
        super().__init__()
        self.num_classes = num_classes
        self.num_boxes   = num_boxes
        self.cls = nn.Conv2d(in_ch, num_boxes*num_classes, 3, padding=1)
        self.box = nn.Conv2d(in_ch, num_boxes*4, 3, padding=1)
    def forward(self, x):
        b = x.size(0)
        cls = self.cls(x).permute(0,2,3,1).contiguous().view(b,-1,self.num_classes)
        box = self.box(x).permute(0,2,3,1).contiguous().view(b,-1,4)
        return cls, box

class SSDScratch(nn.Module):
    def __init__(self, num_classes=2, num_boxes=4):
        super().__init__()
        self.backbone = SSDBackbone()
        self.down1 = nn.Sequential(nn.Conv2d(128,128,3,stride=2,padding=1),nn.ReLU())
        self.down2 = nn.Sequential(nn.Conv2d(128,128,3,stride=2,padding=1),nn.ReLU())
        self.head1 = SSDHead(128, num_classes, num_boxes)
        self.head2 = SSDHead(128, num_classes, num_boxes)
        self.head3 = SSDHead(128, num_classes, num_boxes)
    def forward(self, x):
        f1 = self.backbone(x)
        f2 = self.down1(f1)
        f3 = self.down2(f2)
        c1,b1 = self.head1(f1)
        c2,b2 = self.head2(f2)
        c3,b3 = self.head3(f3)
        return torch.cat([c1,c2,c3],dim=1), torch.cat([b1,b2,b3],dim=1)

# ── Rebuild YOLO model ─────────────────────────────────────
class YOLOBackbone(nn.Module):
    def __init__(self):
        super().__init__()
        def block(cin, cout):
            return nn.Sequential(nn.Conv2d(cin,cout,3,padding=1),nn.BatchNorm2d(cout),nn.LeakyReLU(0.1),nn.MaxPool2d(2,2))
        self.b1=block(3,32); self.b2=block(32,64); self.b3=block(64,128)
        self.b4=block(128,256); self.b5=block(256,512)
    def forward(self, x):
        return self.b5(self.b4(self.b3(self.b2(self.b1(x)))))

class YOLOHead(nn.Module):
    def __init__(self, in_ch=512, num_classes=1, num_boxes=3):
        super().__init__()
        self.num_classes = num_classes
        self.num_boxes   = num_boxes
        self.detect = nn.Conv2d(in_ch, num_boxes*(5+num_classes), 1)
    def forward(self, x):
        b = x.size(0)
        out = self.detect(x).permute(0,2,3,1).contiguous()
        return out.view(b, 13, 13, self.num_boxes, 5+self.num_classes)

class YOLOScratch(nn.Module):
    def __init__(self, num_classes=1, num_boxes=3):
        super().__init__()
        self.backbone = YOLOBackbone()
        self.head     = YOLOHead(512, num_classes, num_boxes)
    def forward(self, x):
        return self.head(self.backbone(x))

# ── Load saved weights ─────────────────────────────────────
ssd = SSDScratch(num_classes=2, num_boxes=4).to(device)
ssd.load_state_dict(torch.load(SSD_SAVE, map_location=device))
ssd.eval()
print("✅ SSD model loaded!")

yolo = YOLOScratch(num_classes=1, num_boxes=3).to(device)
yolo.load_state_dict(torch.load(YOLO_SAVE, map_location=device))
yolo.eval()
print("✅ YOLO model loaded!")

# ── NMS helper ─────────────────────────────────────────────
def iou(box1, box2):
    x1=max(box1[0],box2[0]); y1=max(box1[1],box2[1])
    x2=min(box1[2],box2[2]); y2=min(box1[3],box2[3])
    inter=max(0,x2-x1)*max(0,y2-y1)
    area1=(box1[2]-box1[0])*(box1[3]-box1[1])
    area2=(box2[2]-box2[0])*(box2[3]-box2[1])
    union=area1+area2-inter
    return inter/union if union > 0 else 0

def apply_nms(boxes, scores, iou_thresh=0.3):
    if len(scores) == 0:
        return boxes, scores
    indices = np.argsort(scores)[::-1].tolist()
    keep = []
    while len(indices) > 0:
        current = indices[0]
        keep.append(current)
        indices = indices[1:]
        indices = [i for i in indices if iou(boxes[current], boxes[i]) < iou_thresh]
    return boxes[keep], scores[keep]

# ================================================================
#   FIXED SSD VISUALIZATION
# ================================================================
print("\nVisualizing SSD Scratch (Fixed)...")
NUM_SHOW = min(6, len(test_ds))
fig, axes = plt.subplots(2, 3, figsize=(18,12))
axes = axes.flatten()

for idx in range(NUM_SHOW):
    img_t, _ = test_ds[idx]
    with torch.no_grad():
        pred_cls, pred_box = ssd(img_t.unsqueeze(0).to(device))

    cls_probs  = torch.softmax(pred_cls[0], dim=-1)
    gun_scores = cls_probs[:, 1].cpu().numpy()
    pred_boxes = pred_box[0].cpu().numpy()

    mask       = gun_scores >= 0.95        # ✅ high threshold
    sel_boxes  = pred_boxes[mask]
    sel_scores = gun_scores[mask]

    if len(sel_scores) > 5:               # ✅ top 5 only
        top_idx    = np.argsort(sel_scores)[::-1][:5]
        sel_boxes  = sel_boxes[top_idx]
        sel_scores = sel_scores[top_idx]

    sel_boxes, sel_scores = apply_nms(sel_boxes, sel_scores)  # ✅ NMS

    img_np = (img_t.permute(1,2,0).numpy()*255).astype(np.uint8).copy()
    img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
    H, W   = img_np.shape[:2]

    for box, score in zip(sel_boxes, sel_scores):
        x1=int(box[0]*W); y1=int(box[1]*H)
        x2=int(box[2]*W); y2=int(box[3]*H)
        if x2<=x1 or y2<=y1: continue
        cv2.rectangle(img_np,(x1,y1),(x2,y2),(0,220,0),2)
        cv2.putText(img_np,f"Gun:{score:.2f}",(x1,max(y1-5,10)),
                    cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2)

    img_rgb = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)
    axes[idx].imshow(img_rgb)
    axes[idx].set_title(f"SSD Scratch — Img {idx+1} | {len(sel_boxes)} det", fontweight='bold')
    axes[idx].axis('off')

for idx in range(NUM_SHOW, len(axes)):
    axes[idx].axis('off')

plt.suptitle("SSD From Scratch — Fixed Detection Results", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/ssd_scratch_results_fixed.png", dpi=150)
plt.show()

# ================================================================
#   FIXED YOLO VISUALIZATION
# ================================================================
print("\nVisualizing YOLO Scratch (Fixed)...")
NUM_SHOW = min(6, len(test_ds_yolo))
fig, axes = plt.subplots(2, 3, figsize=(18,12))
axes = axes.flatten()

for idx in range(NUM_SHOW):
    img_t, _ = test_ds_yolo[idx]
    with torch.no_grad():
        pred = yolo(img_t.unsqueeze(0).to(device))

    img_np = (img_t.permute(1,2,0).numpy()*255).astype(np.uint8).copy()
    img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
    H, W   = img_np.shape[:2]

    obj_scores = torch.sigmoid(pred[0, :, :, :, 4]).cpu().numpy()
    box_preds  = torch.sigmoid(pred[0, :, :, :, :4]).cpu().numpy()

    all_boxes  = []
    all_scores = []

    for gy in range(13):
        for gx in range(13):
            for nb in range(3):
                score = obj_scores[gy, gx, nb]
                if score >= 0.90:          # ✅ high threshold
                    cx, cy, bw, bh = box_preds[gy, gx, nb]
                    cx_px = int((gx+cx)/13*W)
                    cy_px = int((gy+cy)/13*H)
                    bw_px = int(bw*W)
                    bh_px = int(bh*H)
                    x1=max(cx_px-bw_px//2,0); y1=max(cy_px-bh_px//2,0)
                    x2=min(cx_px+bw_px//2,W); y2=min(cy_px+bh_px//2,H)
                    if x2>x1 and y2>y1:
                        all_boxes.append([x1,y1,x2,y2])
                        all_scores.append(score)

    det_count = 0
    if len(all_boxes) > 0:
        all_boxes  = np.array(all_boxes,  dtype=float)
        all_scores = np.array(all_scores, dtype=float)

        if len(all_scores) > 10:           # ✅ top 10 only
            top_idx    = np.argsort(all_scores)[::-1][:10]
            all_boxes  = all_boxes[top_idx]
            all_scores = all_scores[top_idx]

        # NMS
        norm = np.array([W,H,W,H], dtype=float)
        keep = []
        indices = np.argsort(all_scores)[::-1].tolist()
        while len(indices) > 0:
            current = indices[0]
            keep.append(current)
            indices = indices[1:]
            indices = [i for i in indices if iou(
                all_boxes[current]/norm, all_boxes[i]/norm) < 0.3]

        for k in keep:
            x1,y1,x2,y2 = map(int, all_boxes[k])
            score = all_scores[k]
            cv2.rectangle(img_np,(x1,y1),(x2,y2),(0,220,0),2)
            cv2.putText(img_np,f"Gun:{score:.2f}",(x1,max(y1-5,10)),
                        cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2)
            det_count += 1

    img_rgb = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)
    axes[idx].imshow(img_rgb)
    axes[idx].set_title(f"YOLO Scratch — Img {idx+1} | {det_count} det", fontweight='bold')
    axes[idx].axis('off')

for idx in range(NUM_SHOW, len(axes)):
    axes[idx].axis('off')

plt.suptitle("YOLO From Scratch — Fixed Detection Results", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/yolo_scratch_results_fixed.png", dpi=150)
plt.show()
print("✅ Done! Both visualizations fixed.")

# ================================================================
#   TUTORIAL 9 — SCRATCH MODELS ON GUNS DATASET
#   SSD from Scratch → trained on Guns
#   YOLO from Scratch → trained on Guns
#   PyTorch — Single Cell
# ================================================================

import torch
import torch.nn as nn
import torchvision.transforms as T
from torch.utils.data import Dataset, DataLoader
from PIL import Image
from pycocotools.coco import COCO
import os, json, time, cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ── Paths ──────────────────────────────────────────────────
DATASET_ROOT = "/content/Guns-9"          # ✅ FIXED
TRAIN_DIR    = os.path.join(DATASET_ROOT, "train")
VALID_DIR    = os.path.join(DATASET_ROOT, "valid")
TEST_DIR     = os.path.join(DATASET_ROOT, "test")
TRAIN_JSON   = os.path.join(TRAIN_DIR, "_annotations.coco.json")
VALID_JSON   = os.path.join(VALID_DIR, "_annotations.coco.json")
TEST_JSON    = os.path.join(TEST_DIR,  "_annotations.coco.json")
RESULTS_DIR  = "/content/results_scratch"
os.makedirs(RESULTS_DIR, exist_ok=True)

CLASS_NAMES = ["__background__", "Guns"]
NUM_CLASSES = 2

def fix_annotations(path):
    with open(path) as f:
        data = json.load(f)
    data["categories"] = [{"id": 1, "name": "Guns", "supercategory": "none"}]
    for ann in data["annotations"]:
        ann["category_id"] = 1
    with open(path, "w") as f:
        json.dump(data, f)
    print(f"   Fixed: {path}")

print("Fixing annotations to Guns only...")
fix_annotations(TRAIN_JSON)
fix_annotations(VALID_JSON)
fix_annotations(TEST_JSON)

class GunsDataset(Dataset):
    def __init__(self, img_dir, ann_file, img_size=300):
        self.img_dir  = img_dir
        self.img_size = img_size
        self.coco     = COCO(ann_file)
        self.img_ids  = list(self.coco.imgs.keys())
        self.tf       = T.Compose([
            T.Resize((img_size, img_size)),
            T.ToTensor(),
        ])
        print(f"  Loaded {len(self.img_ids)} images")

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_id   = self.img_ids[idx]
        img_info = self.coco.imgs[img_id]
        image    = Image.open(os.path.join(self.img_dir,
                    img_info["file_name"])).convert("RGB")
        W0, H0   = image.size
        image    = self.tf(image)

        anns = self.coco.loadAnns(self.coco.getAnnIds(imgIds=img_id))
        boxes, labels = [], []
        for ann in anns:
            x, y, w, h = ann["bbox"]
            x1 = x / W0;  y1 = y / H0
            x2 = (x+w)/W0; y2 = (y+h)/H0
            if w > 1 and h > 1:
                boxes.append([x1, y1, x2, y2])
                labels.append(1)

        if len(boxes) == 0:
            boxes  = torch.zeros((0,4), dtype=torch.float32)
            labels = torch.zeros((0,),  dtype=torch.int64)
        else:
            boxes  = torch.tensor(boxes,  dtype=torch.float32)
            labels = torch.tensor(labels, dtype=torch.int64)

        return image, {"boxes": boxes, "labels": labels,
                       "image_id": torch.tensor([img_id])}

def collate_fn(batch):
    return tuple(zip(*batch))

print("\nLoading datasets...")
train_ds = GunsDataset(TRAIN_DIR, TRAIN_JSON, img_size=300)
valid_ds = GunsDataset(VALID_DIR, VALID_JSON, img_size=300)
test_ds  = GunsDataset(TEST_DIR,  TEST_JSON,  img_size=300)

train_loader = DataLoader(train_ds, batch_size=8, shuffle=True,
                          num_workers=2, collate_fn=collate_fn)
test_loader  = DataLoader(test_ds,  batch_size=1, shuffle=False,
                          num_workers=2, collate_fn=collate_fn)

print(f"Train:{len(train_ds)} | Valid:{len(valid_ds)} | Test:{len(test_ds)}")

print("\n" + "="*60)
print("   PART 1 — SSD FROM SCRATCH ON GUNS DATASET")
print("="*60)

class SSDBackbone(nn.Module):
    def __init__(self):
        super().__init__()
        self.block1 = nn.Sequential(
            nn.Conv2d(3,  32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(),
            nn.MaxPool2d(2,2))
        self.block2 = nn.Sequential(
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),
            nn.MaxPool2d(2,2))
        self.block3 = nn.Sequential(
            nn.Conv2d(64,128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU())

    def forward(self, x):
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        return x

class SSDHead(nn.Module):
    def __init__(self, in_ch, num_classes, num_boxes):
        super().__init__()
        self.num_classes = num_classes
        self.num_boxes   = num_boxes
        self.cls = nn.Conv2d(in_ch, num_boxes*num_classes, 3, padding=1)
        self.box = nn.Conv2d(in_ch, num_boxes*4,           3, padding=1)

    def forward(self, x):
        b   = x.size(0)
        cls = self.cls(x).permute(0,2,3,1).contiguous().view(b,-1,self.num_classes)
        box = self.box(x).permute(0,2,3,1).contiguous().view(b,-1,4)
        return cls, box

class SSDScratch(nn.Module):
    def __init__(self, num_classes=2, num_boxes=4):
        super().__init__()
        self.backbone = SSDBackbone()
        self.down1    = nn.Sequential(
            nn.Conv2d(128,128,3,stride=2,padding=1), nn.ReLU())
        self.down2    = nn.Sequential(
            nn.Conv2d(128,128,3,stride=2,padding=1), nn.ReLU())
        self.head1    = SSDHead(128, num_classes, num_boxes)
        self.head2    = SSDHead(128, num_classes, num_boxes)
        self.head3    = SSDHead(128, num_classes, num_boxes)

    def forward(self, x):
        f1 = self.backbone(x)
        f2 = self.down1(f1)
        f3 = self.down2(f2)
        c1,b1 = self.head1(f1)
        c2,b2 = self.head2(f2)
        c3,b3 = self.head3(f3)
        cls = torch.cat([c1,c2,c3], dim=1)
        box = torch.cat([b1,b2,b3], dim=1)
        return cls, box

class SSDLoss(nn.Module):
    def __init__(self):
        super().__init__()
        self.cls_loss = nn.CrossEntropyLoss()
        self.box_loss = nn.SmoothL1Loss()

    def forward(self, pred_cls, pred_box, targets):
        batch_cls_loss = 0.0
        batch_box_loss = 0.0
        count = 0
        for i in range(len(targets)):
            gt_boxes  = targets[i]["boxes"].to(pred_cls.device)
            gt_labels = targets[i]["labels"].to(pred_cls.device)
            if len(gt_boxes) == 0:
                continue
            num_gt = min(len(gt_boxes), pred_cls.shape[1])
            pred_c = pred_cls[i, :num_gt, :]
            pred_b = pred_box[i, :num_gt, :]
            cls_t = gt_labels[:num_gt]
            box_t = gt_boxes[:num_gt]
            batch_cls_loss += self.cls_loss(pred_c, cls_t)
            batch_box_loss += self.box_loss(pred_b, box_t)
            count += 1
        if count == 0:
            return torch.tensor(0.0, requires_grad=True)
        return (batch_cls_loss + batch_box_loss) / count

ssd = SSDScratch(num_classes=NUM_CLASSES, num_boxes=4).to(device)
ssd_criterion = SSDLoss()
ssd_optimizer = torch.optim.Adam(ssd.parameters(), lr=0.001)
ssd_scheduler = torch.optim.lr_scheduler.StepLR(ssd_optimizer, step_size=5, gamma=0.5)

SSD_EPOCHS  = 15
SSD_SAVE    = f"{RESULTS_DIR}/ssd_scratch.pth"
ssd_losses  = []
ssd_best    = float("inf")

print(f"\n🚀 Training SSD from Scratch for {SSD_EPOCHS} epochs...")
print("="*55)

for epoch in range(1, SSD_EPOCHS+1):
    ssd.train()
    total, count = 0.0, 0
    t0 = time.time()
    for i, (images, targets) in enumerate(train_loader):
        images = torch.stack(images).to(device)
        pred_cls, pred_box = ssd(images)
        loss = ssd_criterion(pred_cls, pred_box, targets)
        if torch.isnan(loss):
            continue
        ssd_optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(ssd.parameters(), max_norm=2.0)
        ssd_optimizer.step()
        total += loss.item(); count += 1
        if (i+1) % 10 == 0:
            print(f"  Ep {epoch}/{SSD_EPOCHS} | Batch {i+1}/{len(train_loader)} | Loss: {loss.item():.4f}")
    ssd_scheduler.step()
    if count == 0:
        continue
    avg = total / count
    ssd_losses.append(avg)
    marker = ""
    if avg < ssd_best:
        ssd_best = avg
        torch.save(ssd.state_dict(), SSD_SAVE)
        marker = "  SAVED"
    print(f"\n── Epoch {epoch} | Avg Loss: {avg:.4f} | Time: {time.time()-t0:.0f}s{marker}\n")

print(f" SSD Scratch Training done! Best loss: {ssd_best:.4f}")

plt.figure(figsize=(10,4))
plt.plot(range(1,len(ssd_losses)+1), ssd_losses, marker='o', color='crimson', linewidth=2.5, markersize=7)
plt.axhline(y=ssd_best, color='green', linestyle='--', label=f'Best: {ssd_best:.4f}')
plt.fill_between(range(1,len(ssd_losses)+1), ssd_losses, alpha=0.15, color='crimson')
plt.title('SSD Scratch — Training Loss Curve', fontsize=13, fontweight='bold')
plt.xlabel('Epoch'); plt.ylabel('Loss')
plt.legend(); plt.grid(alpha=0.3); plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/ssd_scratch_loss.png", dpi=150)
plt.show()

ssd.load_state_dict(torch.load(SSD_SAVE, map_location=device))
ssd.eval()
print(" Best SSD scratch model loaded!")

def draw_boxes_scratch(img_tensor, boxes_norm, scores, color=(0,220,0)):
    img = (img_tensor.permute(1,2,0).numpy()*255).astype(np.uint8).copy()
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    H, W = img.shape[:2]
    for box, score in zip(boxes_norm, scores):
        x1 = int(box[0]*W); y1 = int(box[1]*H)
        x2 = int(box[2]*W); y2 = int(box[3]*H)
        cv2.rectangle(img, (x1,y1), (x2,y2), color, 2)
        cv2.putText(img, f"Gun:{score:.2f}", (x1,max(y1-5,10)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 2)
    return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

print("\nVisualizing SSD Scratch on test images...")
NUM_SHOW = min(6, len(test_ds))
fig, axes = plt.subplots(2, 3, figsize=(18,12))
axes = axes.flatten()

for idx in range(NUM_SHOW):
    img_t, target = test_ds[idx]
    with torch.no_grad():
        pred_cls, pred_box = ssd(img_t.unsqueeze(0).to(device))
    cls_probs  = torch.softmax(pred_cls[0], dim=-1)
    gun_scores = cls_probs[:, 1].cpu().numpy()
    pred_boxes = pred_box[0].cpu().numpy()
    mask = gun_scores >= 0.5
    sel_boxes  = pred_boxes[mask]
    sel_scores = gun_scores[mask]
    annotated = draw_boxes_scratch(img_t, sel_boxes, sel_scores)
    axes[idx].imshow(annotated)
    axes[idx].set_title(f"SSD Scratch — Img {idx+1} | {len(sel_boxes)} det", fontweight='bold')
    axes[idx].axis('off')

for idx in range(NUM_SHOW, len(axes)):
    axes[idx].axis('off')

plt.suptitle("SSD From Scratch — Guns Detection", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/ssd_scratch_results.png", dpi=150)
plt.show()

print("\n" + "="*60)
print("   PART 2 — YOLO FROM SCRATCH ON GUNS DATASET")
print("="*60)

print("\nLoading datasets for YOLO (416x416)...")
train_ds_yolo = GunsDataset(TRAIN_DIR, TRAIN_JSON, img_size=416)
test_ds_yolo  = GunsDataset(TEST_DIR,  TEST_JSON,  img_size=416)
train_loader_yolo = DataLoader(train_ds_yolo, batch_size=8, shuffle=True,
                               num_workers=2, collate_fn=collate_fn)

class YOLOBackbone(nn.Module):
    def __init__(self):
        super().__init__()
        def block(cin, cout):
            return nn.Sequential(
                nn.Conv2d(cin, cout, 3, padding=1),
                nn.BatchNorm2d(cout),
                nn.LeakyReLU(0.1),
                nn.MaxPool2d(2,2)
            )
        self.b1 = block(3,   32)
        self.b2 = block(32,  64)
        self.b3 = block(64,  128)
        self.b4 = block(128, 256)
        self.b5 = block(256, 512)

    def forward(self, x):
        x = self.b1(x); x = self.b2(x)
        x = self.b3(x); x = self.b4(x)
        x = self.b5(x)
        return x

class YOLOHead(nn.Module):
    def __init__(self, in_ch=512, num_classes=1, num_boxes=3):
        super().__init__()
        self.num_classes = num_classes
        self.num_boxes   = num_boxes
        self.detect = nn.Conv2d(in_ch, num_boxes*(5+num_classes), 1)

    def forward(self, x):
        b   = x.size(0)
        out = self.detect(x)
        out = out.permute(0,2,3,1).contiguous()
        out = out.view(b, 13, 13, self.num_boxes, 5+self.num_classes)
        return out

class YOLOScratch(nn.Module):
    def __init__(self, num_classes=1, num_boxes=3):
        super().__init__()
        self.backbone = YOLOBackbone()
        self.head     = YOLOHead(512, num_classes, num_boxes)

    def forward(self, x):
        features = self.backbone(x)
        return self.head(features)

class YOLOLoss(nn.Module):
    def __init__(self):
        super().__init__()
        self.bce = nn.BCEWithLogitsLoss()
        self.mse = nn.MSELoss()

    def forward(self, pred, targets):
        B = pred.size(0)
        obj_loss  = 0.0
        box_loss  = 0.0
        count     = 0
        obj_pred  = pred[..., 4]
        no_obj_target = torch.zeros_like(obj_pred)
        obj_loss += self.bce(obj_pred, no_obj_target) * 0.5
        for b in range(B):
            gt_boxes = targets[b]["boxes"].to(pred.device)
            if len(gt_boxes) == 0:
                continue
            for gt_box in gt_boxes:
                cx = ((gt_box[0] + gt_box[2]) / 2 * 13).long().clamp(0, 12)
                cy = ((gt_box[1] + gt_box[3]) / 2 * 13).long().clamp(0, 12)
                obj_loss += self.bce(
                    pred[b, cy, cx, 0, 4].unsqueeze(0),
                    torch.ones(1).to(pred.device)
                )
                pred_box = torch.sigmoid(pred[b, cy, cx, 0, :4])
                box_loss += self.mse(pred_box,
                    torch.stack([
                        (gt_box[0]+gt_box[2])/2,
                        (gt_box[1]+gt_box[3])/2,
                        gt_box[2]-gt_box[0],
                        gt_box[3]-gt_box[1]
                    ]).to(pred.device))
                count += 1
        total = obj_loss + (box_loss / max(count,1))
        return total

yolo = YOLOScratch(num_classes=1, num_boxes=3).to(device)
yolo_criterion = YOLOLoss()
yolo_optimizer = torch.optim.Adam(yolo.parameters(), lr=0.001)
yolo_scheduler = torch.optim.lr_scheduler.StepLR(yolo_optimizer, step_size=5, gamma=0.5)

YOLO_EPOCHS = 15
YOLO_SAVE   = f"{RESULTS_DIR}/yolo_scratch.pth"
yolo_losses = []
yolo_best   = float("inf")

print(f"\n🚀 Training YOLO from Scratch for {YOLO_EPOCHS} epochs...")
print("="*55)

for epoch in range(1, YOLO_EPOCHS+1):
    yolo.train()
    total, count = 0.0, 0
    t0 = time.time()
    for i, (images, targets) in enumerate(train_loader_yolo):
        images = torch.stack(images).to(device)
        pred   = yolo(images)
        loss   = yolo_criterion(pred, targets)
        if torch.isnan(loss):
            continue
        yolo_optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(yolo.parameters(), max_norm=2.0)
        yolo_optimizer.step()
        total += loss.item(); count += 1
        if (i+1) % 10 == 0:
            print(f"  Ep {epoch}/{YOLO_EPOCHS} | Batch {i+1}/{len(train_loader_yolo)} | Loss: {loss.item():.4f}")
    yolo_scheduler.step()
    if count == 0:
        continue
    avg = total / count
    yolo_losses.append(avg)
    marker = ""
    if avg < yolo_best:
        yolo_best = avg
        torch.save(yolo.state_dict(), YOLO_SAVE)
        marker = "  SAVED"
    print(f"\n── Epoch {epoch} | Avg Loss: {avg:.4f} | Time: {time.time()-t0:.0f}s{marker}\n")

print(f"YOLO Scratch Training done! Best loss: {yolo_best:.4f}")

plt.figure(figsize=(10,4))
plt.plot(range(1,len(yolo_losses)+1), yolo_losses, marker='o', color='steelblue', linewidth=2.5, markersize=7)
plt.axhline(y=yolo_best, color='green', linestyle='--', label=f'Best: {yolo_best:.4f}')
plt.fill_between(range(1,len(yolo_losses)+1), yolo_losses, alpha=0.15, color='steelblue')
plt.title('YOLO Scratch — Training Loss Curve', fontsize=13, fontweight='bold')
plt.xlabel('Epoch'); plt.ylabel('Loss')
plt.legend(); plt.grid(alpha=0.3); plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/yolo_scratch_loss.png", dpi=150)
plt.show()

yolo.load_state_dict(torch.load(YOLO_SAVE, map_location=device))
yolo.eval()
print(" Best YOLO scratch model loaded!")

print("\nVisualizing YOLO Scratch on test images...")
NUM_SHOW = min(6, len(test_ds_yolo))
fig, axes = plt.subplots(2, 3, figsize=(18,12))
axes = axes.flatten()

for idx in range(NUM_SHOW):
    img_t, target = test_ds_yolo[idx]
    with torch.no_grad():
        pred = yolo(img_t.unsqueeze(0).to(device))
    img_np = (img_t.permute(1,2,0).numpy()*255).astype(np.uint8).copy()
    img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
    H, W   = img_np.shape[:2]
    obj_scores = torch.sigmoid(pred[0, :, :, :, 4]).cpu().numpy()
    box_preds  = torch.sigmoid(pred[0, :, :, :, :4]).cpu().numpy()
    det_count = 0
    for gy in range(13):
        for gx in range(13):
            for nb in range(3):
                score = obj_scores[gy, gx, nb]
                if score >= 0.5:
                    cx, cy, bw, bh = box_preds[gy, gx, nb]
                    cx_px = int((gx + cx) / 13 * W)
                    cy_px = int((gy + cy) / 13 * H)
                    bw_px = int(bw * W)
                    bh_px = int(bh * H)
                    x1 = max(cx_px - bw_px//2, 0)
                    y1 = max(cy_px - bh_px//2, 0)
                    x2 = min(cx_px + bw_px//2, W)
                    y2 = min(cy_px + bh_px//2, H)
                    cv2.rectangle(img_np, (x1,y1), (x2,y2), (0,220,0), 2)
                    cv2.putText(img_np, f"Gun:{score:.2f}", (x1,max(y1-5,10)),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 2)
                    det_count += 1
    img_rgb = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)
    axes[idx].imshow(img_rgb)
    axes[idx].set_title(f"YOLO Scratch — Img {idx+1} | {det_count} det", fontweight='bold')
    axes[idx].axis('off')

for idx in range(NUM_SHOW, len(axes)):
    axes[idx].axis('off')

plt.suptitle("YOLO From Scratch — Guns Detection", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/yolo_scratch_results.png", dpi=150)
plt.show()

# ================================================================
#   FINAL SUMMARY
# ================================================================
fig, axes = plt.subplots(1, 2, figsize=(14,5))
axes[0].plot(range(1,len(ssd_losses)+1),  ssd_losses, marker='o', color='crimson',   linewidth=2.5, label='SSD Scratch')
axes[0].plot(range(1,len(yolo_losses)+1), yolo_losses, marker='s', color='steelblue', linewidth=2.5, label='YOLO Scratch')
axes[0].set_title("Loss Comparison — SSD vs YOLO Scratch", fontsize=12, fontweight='bold')
axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Loss")
axes[0].legend(); axes[0].grid(alpha=0.3)

models    = ['SSD\nScratch', 'YOLO\nScratch']
best_vals = [ssd_best, yolo_best]
colors    = ['crimson', 'steelblue']
axes[1].bar(models, best_vals, color=colors, edgecolor='black', width=0.4)
axes[1].set_title("Best Loss Comparison", fontsize=12, fontweight='bold')
axes[1].set_ylabel("Best Loss")
for i,v in enumerate(best_vals):
    axes[1].text(i, v+0.005, f"{v:.4f}", ha='center', fontsize=12, fontweight='bold')

plt.suptitle("Tutorial 9 — Scratch Models on Guns Dataset", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/scratch_comparison.png", dpi=150)
plt.show()

print("\n" + "="*55)
print("   TUTORIAL 9 — SCRATCH MODELS SUMMARY")
print("="*55)
print(f"  Dataset : Guns-9 | Train:{len(train_ds)} Test:{len(test_ds)}")
print(f"  Classes : {CLASS_NAMES}")
print(f"\n  SSD from Scratch:")
print(f"    Epochs    : {SSD_EPOCHS}")
print(f"    Best Loss : {ssd_best:.4f}")
print(f"    Saved to  : {SSD_SAVE}")
print(f"\n  YOLO from Scratch:")
print(f"    Epochs    : {YOLO_EPOCHS}")
print(f"    Best Loss : {yolo_best:.4f}")
print(f"    Saved to  : {YOLO_SAVE}")
print(f"\n   Both scratch models trained on Guns dataset!")
print(f"   Next: Run Part B for Pretrained SSD + YOLO")
print("="*55)