# -*- coding: utf-8 -*-
"""YOLO NAD SSD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YQnFhCUjYmZkR83p2fkxAg5nKtmixqV
"""

# ================================================================
#   TUTORIAL 9 — PART A
#   SSD from Scratch + YOLO from Scratch
#   PyTorch — Single Cell — Copy into Colab
# ================================================================

import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ================================================================
#   PART 1 — SSD FROM SCRATCH
# ================================================================
print("\n" + "=" * 60)
print("   PART 1 — SSD (Single Shot Detector) FROM SCRATCH")
print("=" * 60)

# ────────────────────────────────────────────────────────────────
# SSD STEP 1 — BACKBONE NETWORK
# Extracts features from input image
# Conv layers learn to detect edges → shapes → objects
# ────────────────────────────────────────────────────────────────
print("\n── SSD Step 1: Building Backbone Network...")

class SSDBackbone(nn.Module):
    def __init__(self):
        super(SSDBackbone, self).__init__()
        self.block1 = nn.Sequential(
            nn.Conv2d(3,   32,  kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)          # 300 → 150
        )
        self.block2 = nn.Sequential(
            nn.Conv2d(32,  64,  kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)          # 150 → 75
        )
        self.block3 = nn.Sequential(
            nn.Conv2d(64,  128, kernel_size=3, padding=1),
            nn.ReLU()
                                        # 75 → 75 (no pooling, keep resolution)
        )

    def forward(self, x):
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        return x

backbone = SSDBackbone().to(device)
dummy    = torch.randn(1, 3, 300, 300).to(device)
out      = backbone(dummy)

print(f"  Backbone built!")
print(f"     Input  shape : {dummy.shape}")
print(f"     Output shape : {out.shape}")
print(f"\n  Backbone Architecture:")
print(backbone)


# ────────────────────────────────────────────────────────────────
# SSD STEP 2 — PREDICTION HEAD
# Two heads attached to each feature map:
#   Classification head → what is the object?
#   Bounding box head   → where is the object? (x, y, w, h)
# ────────────────────────────────────────────────────────────────
print("\n── SSD Step 2: Building Prediction Head...")

class SSDHead(nn.Module):
    def __init__(self, in_channels, num_classes, num_boxes):
        super(SSDHead, self).__init__()
        self.num_classes = num_classes
        self.num_boxes   = num_boxes

        # Classification head — predicts class scores
        self.cls_head = nn.Conv2d(
            in_channels, num_boxes * num_classes,
            kernel_size=3, padding=1
        )

        # Bounding box head — predicts (x, y, w, h)
        self.box_head = nn.Conv2d(
            in_channels, num_boxes * 4,
            kernel_size=3, padding=1
        )

    def forward(self, x):
        batch = x.size(0)

        # Class predictions
        cls = self.cls_head(x)                          # (B, num_boxes*num_classes, H, W)
        cls = cls.permute(0, 2, 3, 1).contiguous()     # (B, H, W, num_boxes*num_classes)
        cls = cls.view(batch, -1, self.num_classes)     # (B, H*W*num_boxes, num_classes)

        # Box predictions
        box = self.box_head(x)                          # (B, num_boxes*4, H, W)
        box = box.permute(0, 2, 3, 1).contiguous()     # (B, H, W, num_boxes*4)
        box = box.view(batch, -1, 4)                    # (B, H*W*num_boxes, 4)

        return cls, box

print("  SSD Prediction Head defined!")
print("     Classification head → predicts object class")
print("     Bounding box head   → predicts (x, y, w, h)")


# ────────────────────────────────────────────────────────────────
# SSD STEP 3 — FULL SSD MODEL WITH MULTI-SCALE FEATURE MAPS
# Detects objects at 3 different scales:
#   Scale 1 → large feature map  → finds small objects
#   Scale 2 → medium feature map → finds medium objects
#   Scale 3 → small feature map  → finds large objects
# ────────────────────────────────────────────────────────────────
print("\n── SSD Step 3: Building Full SSD with Multi-Scale Feature Maps...")

class SSDModel(nn.Module):
    def __init__(self, num_classes=21, num_boxes=6):
        super(SSDModel, self).__init__()
        self.num_classes = num_classes
        self.num_boxes   = num_boxes

        # Backbone
        self.backbone = SSDBackbone()

        # Downsample layers for multi-scale (stride=2 halves the map)
        self.scale2 = nn.Conv2d(128, 128, kernel_size=3, stride=2, padding=1)
        self.scale3 = nn.Conv2d(128, 128, kernel_size=3, stride=2, padding=1)

        # One prediction head per scale
        self.head1 = SSDHead(128, num_classes, num_boxes)  # scale 1
        self.head2 = SSDHead(128, num_classes, num_boxes)  # scale 2
        self.head3 = SSDHead(128, num_classes, num_boxes)  # scale 3

    def forward(self, x):
        # Backbone features
        f1 = self.backbone(x)           # Scale 1 — large  (75×75)
        f2 = torch.relu(self.scale2(f1))  # Scale 2 — medium (38×38)
        f3 = torch.relu(self.scale3(f2))  # Scale 3 — small  (19×19)

        # Predictions at each scale
        cls1, box1 = self.head1(f1)
        cls2, box2 = self.head2(f2)
        cls3, box3 = self.head3(f3)

        # Concatenate all scale predictions
        all_cls = torch.cat([cls1, cls2, cls3], dim=1)  # (B, total_anchors, num_classes)
        all_box = torch.cat([box1, box2, box3], dim=1)  # (B, total_anchors, 4)

        return all_cls, all_box

ssd_model = SSDModel(num_classes=21, num_boxes=6).to(device)
print("   Full SSD Model built!")
print(f"\n  SSD Architecture:")
print(ssd_model)


# ────────────────────────────────────────────────────────────────
# SSD STEP 4 — DUMMY DATA TEST
# ────────────────────────────────────────────────────────────────
print("\n── SSD Step 4: Testing with Dummy Data...")

ssd_model.eval()
with torch.no_grad():
    dummy_img                    = torch.randn(1, 3, 300, 300).to(device)
    ssd_class_pred, ssd_box_pred = ssd_model(dummy_img)

print(f"\n  Input shape               : {dummy_img.shape}")
print(f"  SSD Class Prediction Shape: {ssd_class_pred.shape}")
print(f"  SSD Box   Prediction Shape: {ssd_box_pred.shape}")
print(f"\n   {ssd_class_pred.shape[1]} total anchor boxes predicted")
print(f"   Each box has {ssd_class_pred.shape[2]} class scores")
print(f"  Each box has {ssd_box_pred.shape[2]} coordinates (x, y, w, h)")

# ── Visualize SSD architecture ─────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# Architecture flow diagram
axes[0].axis('off')
ssd_parts = [
    ("Input\n300×300×3",       0.08, '#3498db'),
    ("Backbone\nBlock1 32f",   0.22, '#e74c3c'),
    ("Backbone\nBlock2 64f",   0.36, '#e74c3c'),
    ("Backbone\nBlock3 128f",  0.50, '#e74c3c'),
    ("Scale 1\n75×75",         0.64, '#2ecc71'),
    ("Scale 2\n38×38",         0.76, '#f39c12'),
    ("Scale 3\n19×19",         0.88, '#9b59b6'),
]
for label, y_pos, color in ssd_parts:
    axes[0].add_patch(patches.FancyBboxPatch(
        (0.20, y_pos-0.045), 0.60, 0.08,
        boxstyle="round,pad=0.01",
        facecolor=color, alpha=0.85, edgecolor='black'))
    axes[0].text(0.50, y_pos, label, ha='center', va='center',
                fontsize=9, fontweight='bold', color='white')
    if y_pos < 0.88:
        axes[0].annotate("", xy=(0.50, y_pos+0.045),
                         xytext=(0.50, y_pos-0.046),
                         arrowprops=dict(arrowstyle='->', color='black', lw=1.5))

axes[0].set_xlim(0,1); axes[0].set_ylim(0,1)
axes[0].set_title("SSD Architecture Flow", fontsize=12, fontweight='bold')

# Multi-scale visualization
axes[1].axis('off')
scales = [
    (0.15, 0.5, 0.70, 0.70, '#2ecc71', "Scale 1\n75×75\nSmall objects"),
    (0.45, 0.5, 0.40, 0.40, '#f39c12', "Scale 2\n38×38\nMedium objects"),
    (0.75, 0.5, 0.20, 0.20, '#9b59b6', "Scale 3\n19×19\nLarge objects"),
]
for cx, cy, w, h, color, label in scales:
    axes[1].add_patch(patches.Rectangle(
        (cx-w/2, cy-h/2), w, h,
        facecolor=color, alpha=0.5, edgecolor='black', linewidth=2))
    axes[1].text(cx, cy, label, ha='center', va='center',
                fontsize=9, fontweight='bold')

axes[1].set_xlim(0,1); axes[1].set_ylim(0,1)
axes[1].set_title("SSD Multi-Scale Detection\nLarger map = smaller objects detected",
                   fontsize=12, fontweight='bold')

plt.suptitle("SSD — Single Shot Detector Architecture", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print("\n SSD from Scratch — COMPLETE!")


# ================================================================
#   PART 2 — YOLO FROM SCRATCH
# ================================================================
print("\n" + "=" * 60)
print("   PART 2 — YOLO (You Only Look Once) FROM SCRATCH")
print("=" * 60)


# ────────────────────────────────────────────────────────────────
# YOLO STEP 1 — BACKBONE (Darknet-style)
# Deeper than SSD backbone — 5 blocks instead of 3
# Goes from 32 → 512 filters
# ────────────────────────────────────────────────────────────────
print("\n── YOLO Step 1: Building Backbone (Darknet-style)...")

class YOLOBackbone(nn.Module):
    def __init__(self):
        super(YOLOBackbone, self).__init__()
        self.block1 = nn.Sequential(
            nn.Conv2d(3,   32,  kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)          # 416 → 208
        )
        self.block2 = nn.Sequential(
            nn.Conv2d(32,  64,  kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)          # 208 → 104
        )
        self.block3 = nn.Sequential(
            nn.Conv2d(64,  128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)          # 104 → 52
        )
        self.block4 = nn.Sequential(
            nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)          # 52 → 26
        )
        self.block5 = nn.Sequential(
            nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)          # 26 → 13
        )

    def forward(self, x):
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        x = self.block4(x)
        x = self.block5(x)
        return x                        # Output: (B, 512, 13, 13)

yolo_backbone = YOLOBackbone().to(device)
dummy_yolo    = torch.randn(1, 3, 416, 416).to(device)
yolo_feat     = yolo_backbone(dummy_yolo)

print(f"   YOLO Backbone built!")
print(f"     Input  shape : {dummy_yolo.shape}")
print(f"     Output shape : {yolo_feat.shape}")
print(f"\n  YOLO Backbone Architecture:")
print(yolo_backbone)


# ────────────────────────────────────────────────────────────────
# YOLO STEP 2 — DETECTION HEAD
# Divides image into 13×13 grid
# Each cell predicts 3 boxes
# Each box = 4 coords + 1 confidence + 20 class probs = 25
# Total output = 13×13×3×25
# ────────────────────────────────────────────────────────────────
print("\n── YOLO Step 2: Building Detection Head...")

class YOLOHead(nn.Module):
    def __init__(self, in_channels=512, num_classes=20, num_boxes=3):
        super(YOLOHead, self).__init__()
        self.num_classes = num_classes
        self.num_boxes   = num_boxes

        # 5 = 4 coords + 1 confidence
        num_outputs = num_boxes * (num_classes + 5)

        self.detection = nn.Conv2d(
            in_channels, num_outputs,
            kernel_size=1, padding=0
        )

    def forward(self, x):
        batch    = x.size(0)
        out      = self.detection(x)    # (B, num_boxes*(20+5), 13, 13)

        # Reshape to (B, 13, 13, num_boxes, 20+5)
        out = out.permute(0, 2, 3, 1).contiguous()
        out = out.view(batch, 13, 13, self.num_boxes, self.num_classes + 5)

        return out

print("   YOLO Detection Head defined!")
print("     Grid size      : 13 × 13")
print("     Boxes per cell : 3")
print("     Per box output : 4 coords + 1 confidence + 20 classes = 25")
print("     Total per cell : 3 × 25 = 75 values")


# ────────────────────────────────────────────────────────────────
# YOLO STEP 3 — FULL YOLO MODEL
# ────────────────────────────────────────────────────────────────
print("\n── YOLO Step 3: Combining Backbone + Head...")

class YOLOModel(nn.Module):
    def __init__(self, num_classes=20, num_boxes=3):
        super(YOLOModel, self).__init__()
        self.backbone = YOLOBackbone()
        self.head     = YOLOHead(
            in_channels=512,
            num_classes=num_classes,
            num_boxes=num_boxes
        )

    def forward(self, x):
        features = self.backbone(x)
        output   = self.head(features)
        return output

yolo_model = YOLOModel(num_classes=20, num_boxes=3).to(device)
print("  Full YOLO Model built!")
print(f"\n  YOLO Full Architecture:")
print(yolo_model)


# ────────────────────────────────────────────────────────────────
# YOLO STEP 4 — DUMMY DATA TEST
# ────────────────────────────────────────────────────────────────
print("\n── YOLO Step 4: Testing with Dummy Data...")

yolo_model.eval()
with torch.no_grad():
    dummy_input = torch.randn(1, 3, 416, 416).to(device)
    yolo_pred   = yolo_model(dummy_input)

print(f"\n  Input shape          : {dummy_input.shape}")
print(f"  YOLO Prediction Shape: {yolo_pred.shape}")
print(f"\n   Shape: (batch=1, grid_H=13, grid_W=13, boxes=3, values=25)")
print(f"   13×13 = {13*13} grid cells covering the entire image")
print(f"  3     = bounding boxes predicted per cell")
print(f"  25    = x,y,w,h(4) + confidence(1) + classes(20)")

# ── Visualize YOLO grid ────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Left — YOLO 13x13 grid
axes[0].set_xlim(0, 13); axes[0].set_ylim(0, 13)
for i in range(14):
    axes[0].axhline(i, color='lightgray', linewidth=0.5)
    axes[0].axvline(i, color='lightgray', linewidth=0.5)

# Highlight one grid cell and its 3 predicted boxes
sample_boxes = [
    (5.5, 7.0, 3.0, 2.0, 'red',   'Box 1'),
    (5.8, 7.3, 2.0, 1.5, 'blue',  'Box 2'),
    (5.2, 6.8, 1.5, 1.2, 'green', 'Box 3'),
]
for cx, cy, bw, bh, color, label in sample_boxes:
    axes[0].add_patch(patches.Rectangle(
        (cx-bw/2, cy-bh/2), bw, bh,
        linewidth=2, edgecolor=color, facecolor='none', label=label))

axes[0].add_patch(patches.Rectangle(
    (5, 7), 1, 1,
    linewidth=2, edgecolor='black', facecolor='yellow', alpha=0.3))
axes[0].text(5.5, 7.5, "Cell", ha='center', va='center',
             fontsize=7, fontweight='bold')
axes[0].set_title("YOLO 13×13 Grid\nEach cell predicts 3 boxes",
                   fontsize=11, fontweight='bold')
axes[0].legend(fontsize=8, loc='upper right')
axes[0].set_xlabel("Grid X"); axes[0].set_ylabel("Grid Y")

# Right — architecture
axes[1].axis('off')
yolo_parts = [
    ("Input  416×416×3",    0.92, '#3498db'),
    ("Block1  32 filters",  0.80, '#e74c3c'),
    ("Block2  64 filters",  0.68, '#e74c3c'),
    ("Block3 128 filters",  0.56, '#e74c3c'),
    ("Block4 256 filters",  0.44, '#e74c3c'),
    ("Block5 512 filters",  0.32, '#e74c3c'),
    ("YOLO Head 13×13×75",  0.18, '#2ecc71'),
    ("Output 13×13×3×25",   0.06, '#9b59b6'),
]
for label, y_pos, color in yolo_parts:
    axes[1].add_patch(patches.FancyBboxPatch(
        (0.10, y_pos-0.04), 0.80, 0.08,
        boxstyle="round,pad=0.01",
        facecolor=color, alpha=0.85, edgecolor='black'))
    axes[1].text(0.50, y_pos, label, ha='center', va='center',
                fontsize=9, fontweight='bold', color='white')

axes[1].set_xlim(0,1); axes[1].set_ylim(0,1)
axes[1].set_title("YOLO Architecture\nBackbone + Head",
                   fontsize=11, fontweight='bold')

plt.suptitle("YOLO — You Only Look Once Architecture",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print("\n YOLO from Scratch — COMPLETE!")


# ================================================================
#   FINAL — SSD vs YOLO COMPARISON TABLE
# ================================================================
print("\n" + "=" * 60)
print("   SSD vs YOLO — COMPARISON")
print("=" * 60)

fig, ax = plt.subplots(figsize=(12, 5))
ax.axis('off')

rows = [
    ("Feature",         "SSD",                     "YOLO"),
    ("Framework",       "PyTorch",                 "PyTorch"),
    ("Input Size",      "300×300",                 "416×416"),
    ("Detection Type",  "Multi-scale (3 scales)",  "Single grid (13×13)"),
    ("Backbone",        "3 Conv blocks",            "5 Conv blocks (Darknet)"),
    ("Anchor Boxes",    "6 per location",           "3 per grid cell"),
    ("Classes",         "21",                       "20"),
    ("Output Classes",  str(ssd_class_pred.shape),  str(yolo_pred.shape)),
    ("Speed",           "Fast",                     "Faster"),
]

col_colors = ['#2c3e50', '#e74c3c', '#3498db']
for r, row in enumerate(rows):
    for c, val in enumerate(row):
        bg = col_colors[c] if r == 0 else ('#ecf0f1' if r%2==0 else 'white')
        fc = 'white' if r == 0 else 'black'
        ax.add_patch(patches.Rectangle(
            (c*0.33, 1 - r*0.105), 0.33, 0.10,
            facecolor=bg, edgecolor='gray', linewidth=0.5))
        ax.text(c*0.33+0.165, 1 - r*0.105 + 0.050,
                val, ha='center', va='center',
                fontsize=8.5,
                fontweight='bold' if r==0 else 'normal',
                color=fc)

ax.set_xlim(0,1); ax.set_ylim(0,1)
ax.set_title("SSD vs YOLO — Architecture Comparison",
             fontsize=13, fontweight='bold', pad=15)
plt.tight_layout()
plt.show()

print("\n" + "="*60)
print("   TUTORIAL 9 PART A — COMPLETE SUMMARY")
print("="*60)
print(f"  SSD Model:")
print(f"     Backbone : 3 Conv blocks (32→64→128)")
print(f"     Scales   : 3 (75×75, 38×38, 19×19)")
print(f"     Classes  : 21 | Anchor boxes: 6")
print(f"     Output   → Class: {ssd_class_pred.shape} | Box: {ssd_box_pred.shape}")
print(f"\n   YOLO Model:")
print(f"     Backbone : 5 Conv blocks (32→64→128→256→512)")
print(f"     Grid     : 13×13 | Boxes/cell: 3 | Classes: 20")
print(f"     Output   → {yolo_pred.shape}")
print("="*60)

import gdown, zipfile, os
from roboflow import Roboflow

!pip install roboflow -q

rf = Roboflow(api_key="A2YllykE6xoTtfId5TZT")
project = rf.workspace("baheejs-workspace").project("guns-ldyqf")
dataset = project.version(9).download("coco")
print("Done!", dataset.location)

import os
print(os.listdir("/content/Guns-9/train"))

# Find this line:
DATASET_ROOT = "/content/Guns-6"

# Replace with:
DATASET_ROOT = "/content/Guns-9"

# ================================================================
#   TUTORIAL 9 — PART B (FIXED)
#   Task 1: Pretrained SSD on Guns Dataset
#   Task 2: Pretrained YOLO on Guns Dataset
#   PyTorch — Single Cell — Copy into Colab
# ================================================================

import torch
import torchvision
import torchvision.transforms as T
from torchvision.models.detection import ssd300_vgg16, SSD300_VGG16_Weights
from torchvision.models.detection.ssd import SSDClassificationHead
from torchvision.models.detection._utils import retrieve_out_channels
from torch.utils.data import Dataset, DataLoader
from PIL import Image
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
from ultralytics import YOLO

import os, json, time, cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ── Paths ──────────────────────────────────────────────────
DATASET_ROOT = "/content/Guns-6"
TRAIN_DIR    = os.path.join(DATASET_ROOT, "train")
VALID_DIR    = os.path.join(DATASET_ROOT, "valid")
TEST_DIR     = os.path.join(DATASET_ROOT, "test")
TRAIN_JSON   = os.path.join(TRAIN_DIR, "_annotations.coco.json")
VALID_JSON   = os.path.join(VALID_DIR, "_annotations.coco.json")
TEST_JSON    = os.path.join(TEST_DIR,  "_annotations.coco.json")
RESULTS_DIR  = "/content/results_t9"
os.makedirs(RESULTS_DIR, exist_ok=True)

CLASS_NAMES = ["__background__", "Guns"]
NUM_CLASSES = 2

# ── Fix annotations to 1 class ─────────────────────────────
def fix_annotations(path):
    with open(path) as f:
        data = json.load(f)
    data["categories"] = [{"id": 1, "name": "Guns", "supercategory": "none"}]
    for ann in data["annotations"]:
        ann["category_id"] = 1
    with open(path, "w") as f:
        json.dump(data, f)
    print(f"   Fixed: {path}")

print("Fixing annotations to Guns only...")
fix_annotations(TRAIN_JSON)
fix_annotations(VALID_JSON)
fix_annotations(TEST_JSON)


# ================================================================
#   SHARED DATASET CLASS
# ================================================================
class GunsDataset(Dataset):
    def __init__(self, img_dir, ann_file):
        self.img_dir = img_dir
        self.coco    = COCO(ann_file)
        self.img_ids = list(self.coco.imgs.keys())
        self.tf      = T.Compose([T.ToTensor()])
        print(f"  Loaded {len(self.img_ids)} images")

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_id   = self.img_ids[idx]
        img_info = self.coco.imgs[img_id]
        image    = Image.open(os.path.join(self.img_dir,
                    img_info["file_name"])).convert("RGB")
        anns     = self.coco.loadAnns(self.coco.getAnnIds(imgIds=img_id))

        boxes, labels = [], []
        for ann in anns:
            x, y, w, h = ann["bbox"]
            if w > 1 and h > 1:
                boxes.append([x, y, x+w, y+h])
                labels.append(1)

        if len(boxes) == 0:
            boxes  = torch.zeros((0,4), dtype=torch.float32)
            labels = torch.zeros((0,),  dtype=torch.int64)
        else:
            boxes  = torch.tensor(boxes,  dtype=torch.float32)
            labels = torch.tensor(labels, dtype=torch.int64)

        target = {
            "boxes"   : boxes,
            "labels"  : labels,
            "image_id": torch.tensor([img_id]),
            "area"    : (boxes[:,3]-boxes[:,1])*(boxes[:,2]-boxes[:,0]) if len(boxes) else torch.zeros(0),
            "iscrowd" : torch.zeros(len(labels), dtype=torch.int64)
        }
        return self.tf(image), target

def collate_fn(batch):
    return tuple(zip(*batch))

print("\nLoading datasets...")
train_ds = GunsDataset(TRAIN_DIR, TRAIN_JSON)
valid_ds = GunsDataset(VALID_DIR, VALID_JSON)
test_ds  = GunsDataset(TEST_DIR,  TEST_JSON)

train_loader = DataLoader(train_ds, batch_size=4, shuffle=True,
                          num_workers=2, collate_fn=collate_fn)
valid_loader = DataLoader(valid_ds, batch_size=2, shuffle=False,
                          num_workers=2, collate_fn=collate_fn)
test_loader  = DataLoader(test_ds,  batch_size=1, shuffle=False,
                          num_workers=2, collate_fn=collate_fn)

print(f"\nTrain: {len(train_ds)} | Valid: {len(valid_ds)} | Test: {len(test_ds)}")


# ================================================================
#   PART 1 — PRETRAINED SSD ON GUNS DATASET
# ================================================================
print("\n" + "=" * 60)
print("   PART 1 — PRETRAINED SSD300 (VGG16) ON GUNS DATASET")
print("=" * 60)

# ── Build SSD model ────────────────────────────────────────
print("\nLoading pretrained SSD300 VGG16...")
ssd_model = ssd300_vgg16(weights=SSD300_VGG16_Weights.DEFAULT)

# Replace classification head for 2 classes (background + Guns)
in_channels = retrieve_out_channels(ssd_model.backbone, (300, 300))
num_anchors = ssd_model.anchor_generator.num_anchors_per_location()
ssd_model.head.classification_head = SSDClassificationHead(
    in_channels, num_anchors, NUM_CLASSES
)
ssd_model = ssd_model.to(device)
print(f"   SSD300 loaded | Classes: {NUM_CLASSES} | Device: {device}")

# ── FIX: Separate LR — low for backbone, higher for new head ──
params = [
    {"params": ssd_model.backbone.parameters(), "lr": 0.0001},
    {"params": ssd_model.head.parameters(),     "lr": 0.001},
]
ssd_optim  = torch.optim.SGD(params, momentum=0.9, weight_decay=0.0005)
ssd_sched  = torch.optim.lr_scheduler.StepLR(ssd_optim, step_size=4, gamma=0.5)

SSD_EPOCHS = 10
SSD_SAVE   = "/content/best_ssd.pth"
ssd_losses = []
ssd_best   = float("inf")

print(f"\n Training SSD for {SSD_EPOCHS} epochs...")
print("=" * 55)

for epoch in range(1, SSD_EPOCHS+1):
    ssd_model.train()
    total, count = 0.0, 0
    t0 = time.time()

    for i, (images, targets) in enumerate(train_loader):
        images  = [img.to(device) for img in images]
        targets = [{k: v.to(device) for k,v in t.items()} for t in targets]

        loss_dict = ssd_model(images, targets)
        losses    = sum(loss_dict.values())

        # ── FIX: Skip NaN batches ──────────────────────────
        if torch.isnan(losses):
            continue

        ssd_optim.zero_grad()
        losses.backward()
        # ── FIX: Gradient clipping stops exploding gradients
        torch.nn.utils.clip_grad_norm_(ssd_model.parameters(), max_norm=1.0)
        ssd_optim.step()

        total += losses.item()
        count += 1

        if (i+1) % 10 == 0:
            print(f"  Ep {epoch}/{SSD_EPOCHS} | Batch {i+1}/{len(train_loader)} "
                  f"| Loss: {losses.item():.4f}")

    ssd_sched.step()

    if count == 0:
        print(f"\n── Epoch {epoch} | All batches NaN — skipping\n")
        continue

    avg = total / count
    ssd_losses.append(avg)
    marker = ""
    if avg < ssd_best:
        ssd_best = avg
        torch.save(ssd_model.state_dict(), SSD_SAVE)
        marker = "  SAVED"

    print(f"\n── Epoch {epoch} | Avg Loss: {avg:.4f} | "
          f"Time: {time.time()-t0:.0f}s{marker}\n")

print(f" SSD Training done! Best loss: {ssd_best:.4f}")

# ── SSD Loss curve ─────────────────────────────────────────
if ssd_losses:
    plt.figure(figsize=(10, 4))
    plt.plot(range(1, len(ssd_losses)+1), ssd_losses,
             marker='o', color='crimson', linewidth=2.5, markersize=7)
    plt.axhline(y=ssd_best, color='green', linestyle='--',
                label=f'Best: {ssd_best:.4f}')
    plt.fill_between(range(1, len(ssd_losses)+1), ssd_losses,
                     alpha=0.15, color='crimson')
    plt.title('SSD — Training Loss Curve', fontsize=13, fontweight='bold')
    plt.xlabel('Epoch'); plt.ylabel('Loss')
    plt.legend(); plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(f"{RESULTS_DIR}/ssd_loss.png", dpi=150)
    plt.show()

# ── Load best SSD ──────────────────────────────────────────
if os.path.exists(SSD_SAVE):
    ssd_model.load_state_dict(torch.load(SSD_SAVE, map_location=device))
    print(" Best SSD model loaded!")
else:
    print(" No saved model — using current weights")

ssd_model.eval()

# ── Detection + draw functions ─────────────────────────────
def detect_ssd(img_tensor, threshold=0.3):
    ssd_model.eval()
    with torch.no_grad():
        out = ssd_model([img_tensor.to(device)])[0]
    boxes  = out['boxes'].cpu().numpy()
    labels = out['labels'].cpu().numpy()
    scores = out['scores'].cpu().numpy()
    mask   = scores >= threshold
    return boxes[mask], labels[mask], scores[mask]

def draw_boxes(img_tensor, boxes, labels, scores, color=(0,220,0)):
    img = (img_tensor.permute(1,2,0).numpy()*255).astype(np.uint8)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    for box, label, score in zip(boxes, labels, scores):
        x1,y1,x2,y2 = map(int, box)
        name = CLASS_NAMES[label] if label < len(CLASS_NAMES) else f"obj_{label}"
        text = f"{name}: {score:.2f}"
        cv2.rectangle(img, (x1,y1), (x2,y2), color, 3)
        (tw,th),_ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(img, (x1,y1-th-8), (x1+tw+4,y1), color, -1)
        cv2.putText(img, text, (x1+2,y1-4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,0), 2)
    return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# ── SSD: show 6 test images ────────────────────────────────
print("\nRunning SSD on test images...")
NUM_SHOW = min(6, len(test_ds))
fig, axes = plt.subplots(2, 3, figsize=(18, 12))
axes = axes.flatten()

for idx in range(NUM_SHOW):
    img_t, target = test_ds[idx]
    boxes, labels, scores = detect_ssd(img_t, threshold=0.3)
    annotated = draw_boxes(img_t, boxes, labels, scores, color=(0,220,0))
    axes[idx].imshow(annotated)
    axes[idx].set_title(f"SSD — Image {idx+1} | {len(boxes)} gun(s)",
                        fontweight='bold')
    axes[idx].axis('off')

for idx in range(NUM_SHOW, len(axes)):
    axes[idx].axis('off')

plt.suptitle("SSD300 VGG16 — Guns Detection Results",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/ssd_results.png", dpi=150)
plt.show()

# ── SSD mAP ────────────────────────────────────────────────
print("\nComputing SSD mAP...")
coco_gt      = COCO(TEST_JSON)
coco_results = []
ssd_model.eval()

with torch.no_grad():
    for images, targets in test_loader:
        images  = [img.to(device) for img in images]
        outputs = ssd_model(images)
        for out, tgt in zip(outputs, targets):
            img_id = tgt['image_id'].item()
            for box, score, label in zip(
                out['boxes'].cpu().numpy(),
                out['scores'].cpu().numpy(),
                out['labels'].cpu().numpy()
            ):
                x1,y1,x2,y2 = box
                coco_results.append({
                    "image_id"   : img_id,
                    "category_id": int(label),
                    "bbox"       : [float(x1),float(y1),
                                    float(x2-x1),float(y2-y1)],
                    "score"      : float(score)
                })

ssd_map50   = 0
ssd_map5095 = 0
if coco_results:
    coco_dt   = coco_gt.loadRes(coco_results)
    coco_eval = COCOeval(coco_gt, coco_dt, 'bbox')
    coco_eval.evaluate()
    coco_eval.accumulate()
    coco_eval.summarize()
    ssd_map50   = coco_eval.stats[1]
    ssd_map5095 = coco_eval.stats[0]
    print(f"\n   SSD mAP@0.50      = {ssd_map50*100:.1f}%")
    print(f"  SSD mAP@0.50:0.95 = {ssd_map5095*100:.1f}%")


# ================================================================
#   PART 2 — PRETRAINED YOLO ON GUNS DATASET
# ================================================================
print("\n" + "=" * 60)
print("   PART 2 — PRETRAINED YOLOv8 ON GUNS DATASET")
print("=" * 60)

# ── Convert dataset to YOLO format ─────────────────────────
YOLO_DIR = "/content/yolo_guns"
for split in ['train', 'valid', 'test']:
    os.makedirs(f"{YOLO_DIR}/{split}/images", exist_ok=True)
    os.makedirs(f"{YOLO_DIR}/{split}/labels", exist_ok=True)

def coco_to_yolo(json_path, img_dir, out_img_dir, out_lbl_dir):
    with open(json_path) as f:
        data = json.load(f)
    img_lookup = {img['id']: img for img in data['images']}
    ann_by_img = {}
    for ann in data['annotations']:
        ann_by_img.setdefault(ann['image_id'], []).append(ann)

    import shutil
    for img_id, img_info in img_lookup.items():
        fname    = img_info['file_name']
        src_path = os.path.join(img_dir, fname)
        dst_path = os.path.join(out_img_dir, fname)
        if os.path.exists(src_path):
            shutil.copy(src_path, dst_path)

        W, H     = img_info['width'], img_info['height']
        anns     = ann_by_img.get(img_id, [])
        lbl_path = os.path.join(out_lbl_dir,
                    fname.replace('.jpg','.txt').replace('.png','.txt'))
        with open(lbl_path, 'w') as f:
            for ann in anns:
                x, y, w, h = ann['bbox']
                cx = (x + w/2) / W
                cy = (y + h/2) / H
                nw = w / W
                nh = h / H
                f.write(f"0 {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}\n")

print("Converting dataset to YOLO format...")
coco_to_yolo(TRAIN_JSON, TRAIN_DIR,
             f"{YOLO_DIR}/train/images", f"{YOLO_DIR}/train/labels")
coco_to_yolo(VALID_JSON, VALID_DIR,
             f"{YOLO_DIR}/valid/images", f"{YOLO_DIR}/valid/labels")
coco_to_yolo(TEST_JSON,  TEST_DIR,
             f"{YOLO_DIR}/test/images",  f"{YOLO_DIR}/test/labels")
print("   Dataset converted to YOLO format!")

# ── Write YOLO yaml config ─────────────────────────────────
yaml_content = f"""path: {YOLO_DIR}
train: train/images
val:   valid/images
test:  test/images
nc: 1
names: ['Guns']
"""
yaml_path = f"{YOLO_DIR}/guns.yaml"
with open(yaml_path, 'w') as f:
    f.write(yaml_content)
print(f"   YAML config written!")

# ── Load pretrained YOLOv8 and train ──────────────────────
print("\nLoading pretrained YOLOv8n...")
yolo_model = YOLO('yolov8n.pt')
print("   YOLOv8n loaded!")

print(f"\n🚀 Training YOLOv8 for 10 epochs...")
results = yolo_model.train(
    data    = yaml_path,
    epochs  = 10,
    imgsz   = 416,
    batch   = 8,
    device  = 0 if torch.cuda.is_available() else 'cpu',
    project = RESULTS_DIR,
    name    = 'yolo_guns',
    verbose = True
)
print(" YOLO Training done!")

# ── YOLO: show 6 test images ───────────────────────────────
print("\nRunning YOLO on test images...")
test_images = [
    os.path.join(f"{YOLO_DIR}/test/images", f)
    for f in os.listdir(f"{YOLO_DIR}/test/images")
    if f.endswith('.jpg') or f.endswith('.png')
][:6]

best_yolo   = YOLO(f"{RESULTS_DIR}/yolo_guns/weights/best.pt")

fig, axes = plt.subplots(2, 3, figsize=(18, 12))
axes = axes.flatten()

for idx, img_path in enumerate(test_images):
    result = best_yolo(img_path, conf=0.3, verbose=False)[0]
    img    = cv2.imread(img_path)
    img    = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    for box in result.boxes:
        x1,y1,x2,y2 = map(int, box.xyxy[0])
        score = float(box.conf[0])
        cv2.rectangle(img, (x1,y1), (x2,y2), (0,220,0), 3)
        (tw,th),_ = cv2.getTextSize(f"Gun:{score:.2f}",
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(img, (x1,y1-th-8), (x1+tw+4,y1), (0,220,0), -1)
        cv2.putText(img, f"Gun:{score:.2f}", (x1+2,y1-4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,0), 2)

    axes[idx].imshow(img)
    axes[idx].set_title(f"YOLO — Image {idx+1} | {len(result.boxes)} gun(s)",
                        fontweight='bold')
    axes[idx].axis('off')

for idx in range(len(test_images), len(axes)):
    axes[idx].axis('off')

plt.suptitle("YOLOv8n — Guns Detection Results",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/yolo_results.png", dpi=150)
plt.show()

# ── YOLO mAP ───────────────────────────────────────────────
print("\nComputing YOLO mAP on test set...")
yolo_metrics = best_yolo.val(
    data    = yaml_path,
    split   = 'test',
    verbose = False
)
yolo_map50   = yolo_metrics.box.map50
yolo_map5095 = yolo_metrics.box.map
print(f"\n   YOLO mAP@0.50      = {yolo_map50*100:.1f}%")
print(f"   YOLO mAP@0.50:0.95 = {yolo_map5095*100:.1f}%")


# ================================================================
#   FINAL COMPARISON — SSD vs YOLO
# ================================================================
print("\n" + "=" * 60)
print("   FINAL COMPARISON — SSD vs YOLO ON GUNS DATASET")
print("=" * 60)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# mAP comparison
models = ['SSD300\nVGG16', 'YOLOv8n']
map50s = [ssd_map50*100, yolo_map50*100]
colors = ['#e74c3c', '#3498db']

axes[0].bar(models, map50s, color=colors, edgecolor='black', width=0.4)
axes[0].set_ylim(0, 110)
axes[0].set_title("mAP@0.50 Comparison", fontsize=12, fontweight='bold')
axes[0].set_ylabel("mAP@0.50 (%)")
axes[0].axhline(y=50, color='gray', linestyle='--', alpha=0.5, label='50% line')
axes[0].legend()
for i, v in enumerate(map50s):
    axes[0].text(i, v+1, f"{v:.1f}%", ha='center',
                fontsize=13, fontweight='bold')

# SSD loss curve
if ssd_losses:
    axes[1].plot(range(1, len(ssd_losses)+1), ssd_losses,
                 marker='o', color='#e74c3c', linewidth=2.5,
                 markersize=7, label='SSD Loss')
    axes[1].set_title("SSD Training Loss Curve", fontsize=12, fontweight='bold')
    axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Loss")
    axes[1].legend(); axes[1].grid(alpha=0.3)

plt.suptitle("Tutorial 9 Part B — SSD vs YOLO on Guns Dataset",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/comparison.png", dpi=150)
plt.show()

# ── Final summary ──────────────────────────────────────────
print("\n" + "="*55)
print("   TUTORIAL 9 PART B — FINAL SUMMARY")
print("="*55)
print(f"  Dataset : Guns-6")
print(f"  Train   : {len(train_ds)} | Valid: {len(valid_ds)} | Test: {len(test_ds)}")
print(f"  Classes : {CLASS_NAMES}")
print(f"\n  SSD300 VGG16:")
print(f"    Epochs    : {SSD_EPOCHS}")
print(f"    Best Loss : {ssd_best:.4f}")
print(f"    mAP@0.50  : {ssd_map50*100:.1f}%")
print(f"\n  YOLOv8n:")
print(f"    Epochs    : 10")
print(f"    mAP@0.50  : {yolo_map50*100:.1f}%")
print(f"\n  Winner : {'SSD ' if ssd_map50 > yolo_map50 else 'YOLO'}")
print("="*55)