# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXIiy9Kj9Xb1CkGol7UfInXK0VPtJ0jt
"""

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║         INSTANCE SEGMENTATION — FULL PIPELINE (FIXED)                      ║
# ║         Dataset : Guns Detection (Roboflow COCO-Segmentation)               ║
# ║         Model   : Mask R-CNN (ResNet-50 + FPN backbone)                     ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 0 ── INSTALL PACKAGES                                                  │
# └─────────────────────────────────────────────────────────────────────────────┘
# !pip install roboflow pycocotools opencv-python matplotlib -q

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 1 ── IMPORTS                                                           │
# └─────────────────────────────────────────────────────────────────────────────┘
import os, json, time, warnings
warnings.filterwarnings("ignore")

import torch, torchvision
import torchvision.transforms.functional as TF
from torchvision.models.detection          import maskrcnn_resnet50_fpn
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn   import MaskRCNNPredictor
from torch.utils.data import Dataset, DataLoader

import numpy as np
import cv2
import matplotlib.pyplot   as plt
import matplotlib.patches  as mpatches
import matplotlib.gridspec as gridspec
from PIL              import Image
from pycocotools.coco import COCO

print("=" * 65)
print("  INSTANCE SEGMENTATION PIPELINE — Guns Detection (FIXED)")
print("=" * 65)
print(f"\n✅ STEP 1 COMPLETE")
print(f"   PyTorch     : {torch.__version__}")
print(f"   Torchvision : {torchvision.__version__}")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 2 ── DEVICE                                                            │
# └─────────────────────────────────────────────────────────────────────────────┘
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\n✅ STEP 2 COMPLETE — Device: {device}")
if torch.cuda.is_available():
    print(f"   GPU : {torch.cuda.get_device_name(0)}")
    print(f"   VRAM: {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 3 ── DOWNLOAD DATASET                                                  │
# └─────────────────────────────────────────────────────────────────────────────┘
from roboflow import Roboflow

print("\n⏳ STEP 3 — Downloading dataset from Roboflow...")
rf      = Roboflow(api_key="cyGDeK8mgvw7ZFBtmJ9I")
project = rf.workspace("emans-workspace-bczzy").project("guns-vhehj")
version = project.version(1)
dataset = version.download("coco-segmentation")

DATASET_ROOT = dataset.location
print(f"\n   Raw dataset root: {DATASET_ROOT}")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ *** FIX: AUTO-DETECT CORRECT PATHS ***                                      │
# │                                                                             │
# │ Roboflow sometimes nests folders differently depending on the project.      │
# │ We scan the downloaded folder and find the actual image directories         │
# │ and annotation files automatically — no hardcoded paths.                    │
# └─────────────────────────────────────────────────────────────────────────────┘

def find_split_paths(root):
    """
    Recursively search `root` for train/valid/test splits.
    Returns dict: { 'train': (img_dir, ann_file), 'valid': ..., 'test': ... }

    Handles all Roboflow folder layouts:
      Layout A:  root/train/images/*.jpg  +  root/train/_annotations.coco.json
      Layout B:  root/train/*.jpg         +  root/train/_annotations.coco.json
      Layout C:  root/images/train/*.jpg  +  root/annotations/train.json
    """
    splits   = {}
    keywords = ["train", "valid", "test"]

    # Walk every subdirectory
    for dirpath, dirnames, filenames in os.walk(root):
        # Check if this folder name matches a split keyword
        folder_name = os.path.basename(dirpath).lower()

        for kw in keywords:
            if kw in folder_name and kw not in splits:

                # ── Find annotation JSON ───────────────────────────────────
                ann_file = None
                for fname in filenames:
                    if fname.endswith(".json"):
                        ann_file = os.path.join(dirpath, fname)
                        break

                # Also check one level up for the JSON
                if ann_file is None:
                    parent = os.path.dirname(dirpath)
                    for fname in os.listdir(parent):
                        if fname.endswith(".json") and kw in fname.lower():
                            ann_file = os.path.join(parent, fname)
                            break

                if ann_file is None:
                    continue  # No annotation file found for this split

                # ── Find image directory ───────────────────────────────────
                # Check for an "images" subfolder inside this split folder
                img_dir = None
                images_sub = os.path.join(dirpath, "images")
                if os.path.isdir(images_sub):
                    img_dir = images_sub
                else:
                    # Images are directly in this folder
                    img_exts = {".jpg", ".jpeg", ".png", ".bmp"}
                    has_imgs = any(
                        os.path.splitext(f)[1].lower() in img_exts
                        for f in filenames
                    )
                    if has_imgs:
                        img_dir = dirpath

                if img_dir is None:
                    continue

                # ── Verify annotation filenames match actual files ─────────
                # Read JSON, check if first image filename exists
                try:
                    with open(ann_file) as f:
                        ann_data = json.load(f)
                    if ann_data.get("images"):
                        sample_fname = ann_data["images"][0]["file_name"]
                        # Strip any subdirectory prefix Roboflow may have added
                        sample_fname = os.path.basename(sample_fname)
                        candidate    = os.path.join(img_dir, sample_fname)
                        if not os.path.exists(candidate):
                            # Try parent directory
                            candidate2 = os.path.join(dirpath, sample_fname)
                            if os.path.exists(candidate2):
                                img_dir = dirpath
                except Exception:
                    pass

                splits[kw] = (img_dir, ann_file)
                print(f"   [{kw}] images → {img_dir}")
                print(f"   [{kw}] labels → {ann_file}")

    return splits


print("\n   🔍 Auto-detecting split paths...")
splits = find_split_paths(DATASET_ROOT)

if "train" not in splits:
    raise RuntimeError(
        f"Could not find training data under {DATASET_ROOT}\n"
        f"Contents: {os.listdir(DATASET_ROOT)}"
    )

TRAIN_IMG_DIR,  TRAIN_ANN_FILE = splits["train"]
VALID_IMG_DIR,  VALID_ANN_FILE = splits.get("valid", splits["train"])
TEST_IMG_DIR,   TEST_ANN_FILE  = splits.get("test",  splits["train"])

# ── Patch annotation filenames to use ONLY basenames (fixes path mismatch) ──
def patch_annotation_file(ann_file):
    """
    Roboflow sometimes stores file_name as 'train/images/foo.jpg'
    but the actual file is at img_dir/foo.jpg.
    This function rewrites all file_name entries to use only the basename.
    Returns path to patched file (or original if no change needed).
    """
    with open(ann_file) as f:
        data = json.load(f)

    changed = False
    for img_entry in data.get("images", []):
        original = img_entry["file_name"]
        cleaned  = os.path.basename(original)
        if cleaned != original:
            img_entry["file_name"] = cleaned
            changed = True

    if changed:
        patched_path = ann_file.replace(".json", "_patched.json")
        with open(patched_path, "w") as f:
            json.dump(data, f)
        print(f"   ✔ Patched annotation paths → {os.path.basename(patched_path)}")
        return patched_path
    else:
        print(f"   ✔ Annotation paths already clean — no patching needed")
        return ann_file


print("\n   🔧 Checking and patching annotation file paths...")
TRAIN_ANN_FILE = patch_annotation_file(TRAIN_ANN_FILE)
VALID_ANN_FILE = patch_annotation_file(VALID_ANN_FILE)
TEST_ANN_FILE  = patch_annotation_file(TEST_ANN_FILE)

# ── Dataset stats ────────────────────────────────────────────────────────────
with open(TRAIN_ANN_FILE) as f:
    meta = json.load(f)

print(f"\n✅ STEP 3 COMPLETE — Dataset ready")
print(f"\n   📊 DATASET STATISTICS")
print(f"   {'─'*45}")
print(f"   Training images     : {len(meta['images'])}")
print(f"   Training annotations: {len(meta['annotations'])}")
print(f"   Number of classes   : {len(meta['categories'])}")
print(f"\n   Classes found:")
for cat in meta["categories"]:
    count = sum(1 for a in meta["annotations"] if a["category_id"] == cat["id"])
    print(f"     • [{cat['id']:2d}] {cat['name']:<22} — {count:3d} instances")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 4 ── VISUALIZE GROUND TRUTH LABELS                                     │
# └─────────────────────────────────────────────────────────────────────────────┘
def visualize_ground_truth(img_dir, ann_file, num_samples=6, save_path=None):
    """
    Show sample images with ground-truth masks and bounding boxes.
    Uses only the basename of each filename to avoid path mismatch.
    """
    coco    = COCO(ann_file)
    img_ids = coco.getImgIds()
    img_ids = [i for i in img_ids if len(coco.getAnnIds(imgIds=i)) > 0]
    img_ids = img_ids[:num_samples]

    cols  = min(3, len(img_ids))
    rows  = (len(img_ids) + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(6 * cols, 5 * rows))
    axes  = np.array(axes).flatten() if rows * cols > 1 else [axes]
    fig.patch.set_facecolor("#0f0f0f")
    fig.suptitle("Ground Truth Labels — Your Guns Dataset",
                 fontsize=15, fontweight="bold", color="white", y=1.01)

    for ax, img_id in zip(axes, img_ids):
        info = coco.loadImgs(img_id)[0]

        # ── KEY FIX: always use basename ──────────────────────────────────
        fname    = os.path.basename(info["file_name"])
        img_path = os.path.join(img_dir, fname)

        if not os.path.exists(img_path):
            ax.set_title(f"Missing: {fname}", color="red", fontsize=8)
            ax.axis("off")
            continue

        image   = np.array(Image.open(img_path).convert("RGB"))
        ann_ids = coco.getAnnIds(imgIds=img_id)
        anns    = coco.loadAnns(ann_ids)

        ax.imshow(image)
        ax.set_facecolor("#0f0f0f")
        np.random.seed(img_id)

        for ann in anns:
            color = np.random.rand(3)

            if ann.get("segmentation"):
                mask = coco.annToMask(ann)
                rgba = np.zeros((*mask.shape, 4))
                rgba[mask == 1] = [*color, 0.45]
                ax.imshow(rgba)

                contours, _ = cv2.findContours(
                    mask.astype(np.uint8),
                    cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
                )
                for cnt in contours:
                    pts = cnt.squeeze()
                    if pts.ndim == 2:
                        ax.plot(pts[:, 0], pts[:, 1],
                                color=color, linewidth=1.5)

            x, y, w, h = ann["bbox"]
            ax.add_patch(plt.Rectangle(
                (x, y), w, h, linewidth=2,
                edgecolor=color, facecolor="none"
            ))
            cat_name = coco.loadCats(ann["category_id"])[0]["name"]
            ax.text(x, y - 4, cat_name, color="white", fontsize=8,
                    fontweight="bold",
                    bbox=dict(facecolor=color, alpha=0.7,
                              pad=2, edgecolor="none"))

        ax.set_title(f"ID {img_id} — {len(anns)} object(s)",
                     fontsize=10, color="white")
        ax.axis("off")

    for ax in axes[len(img_ids):]:
        ax.set_visible(False)

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight",
                    facecolor=fig.get_facecolor())
        print(f"   Saved → {save_path}")
    plt.show()


print("\n⏳ STEP 4 — Visualizing ground truth labels...")
visualize_ground_truth(TRAIN_IMG_DIR, TRAIN_ANN_FILE,
                       num_samples=6, save_path="ground_truth_labels.png")
print("✅ STEP 4 COMPLETE")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 5 ── CUSTOM DATASET CLASS                                              │
# └─────────────────────────────────────────────────────────────────────────────┘
class GunSegmentationDataset(Dataset):

    def __init__(self, img_dir, ann_file, augment=False):
        self.img_dir  = img_dir
        self.augment  = augment
        self.coco     = COCO(ann_file)

        all_ids      = self.coco.getImgIds()
        self.img_ids = [i for i in all_ids
                        if len(self.coco.getAnnIds(imgIds=i)) > 0]

        cats = self.coco.loadCats(self.coco.getCatIds())
        # Map COCO category id → model label (1-based; 0 = background)
        self.cat_to_label = {cat["id"]: idx + 1 for idx, cat in enumerate(cats)}
        self.class_names  = ["background"] + [cat["name"] for cat in cats]

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_id   = self.img_ids[idx]
        img_info = self.coco.loadImgs(img_id)[0]

        # ── KEY FIX: always resolve to basename ───────────────────────────
        fname    = os.path.basename(img_info["file_name"])
        img_path = os.path.join(self.img_dir, fname)

        image    = Image.open(img_path).convert("RGB")
        W, H     = image.size

        ann_ids = self.coco.getAnnIds(imgIds=img_id)
        anns    = self.coco.loadAnns(ann_ids)

        boxes, labels, masks = [], [], []

        for ann in anns:
            x, y, w, h     = ann["bbox"]
            x1,y1,x2,y2    = x, y, x+w, y+h
            if x2 <= x1 or y2 <= y1:
                continue
            boxes.append([x1, y1, x2, y2])
            labels.append(self.cat_to_label[ann["category_id"]])
            masks.append(self.coco.annToMask(ann))

        if len(boxes) == 0:
            boxes   = torch.zeros((0, 4),    dtype=torch.float32)
            labels  = torch.zeros((0,),      dtype=torch.int64)
            masks   = torch.zeros((0, H, W), dtype=torch.uint8)
            area    = torch.zeros((0,),      dtype=torch.float32)
            iscrowd = torch.zeros((0,),      dtype=torch.uint8)
        else:
            boxes   = torch.as_tensor(boxes,           dtype=torch.float32)
            labels  = torch.as_tensor(labels,          dtype=torch.int64)
            masks   = torch.as_tensor(np.stack(masks), dtype=torch.uint8)
            area    = (boxes[:,3]-boxes[:,1]) * (boxes[:,2]-boxes[:,0])
            iscrowd = torch.zeros((len(boxes),),        dtype=torch.uint8)

        target = {
            "boxes":    boxes,
            "labels":   labels,
            "masks":    masks,
            "image_id": torch.tensor([img_id]),
            "area":     area,
            "iscrowd":  iscrowd,
        }

        img_tensor = TF.to_tensor(image)

        # Horizontal flip augmentation (training only)
        if self.augment and torch.rand(1).item() > 0.5:
            img_tensor = TF.hflip(img_tensor)
            _, H_t, W_t = img_tensor.shape
            if len(target["boxes"]) > 0:
                fb = target["boxes"].clone()
                fb[:, 0] = W_t - target["boxes"][:, 2]
                fb[:, 2] = W_t - target["boxes"][:, 0]
                target["boxes"] = fb
            if len(target["masks"]) > 0:
                target["masks"] = torch.flip(target["masks"], dims=[2])

        return img_tensor, target


print("\n⏳ STEP 5 — Creating dataset objects...")
train_dataset = GunSegmentationDataset(TRAIN_IMG_DIR, TRAIN_ANN_FILE, augment=True)
valid_dataset = GunSegmentationDataset(VALID_IMG_DIR, VALID_ANN_FILE, augment=False)
test_dataset  = GunSegmentationDataset(TEST_IMG_DIR,  TEST_ANN_FILE,  augment=False)

NUM_CLASSES = len(train_dataset.class_names)
CLASS_NAMES = train_dataset.class_names

print(f"\n✅ STEP 5 COMPLETE")
print(f"   Train : {len(train_dataset)} images")
print(f"   Valid : {len(valid_dataset)} images")
print(f"   Test  : {len(test_dataset)}  images")
print(f"   Classes ({NUM_CLASSES}): {CLASS_NAMES}")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 6 ── DATALOADERS                                                       │
# └─────────────────────────────────────────────────────────────────────────────┘
def collate_fn(batch):
    return tuple(zip(*batch))

BATCH_SIZE   = 2   # reduce to 1 if CUDA out-of-memory

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE,
                          shuffle=True,  num_workers=2,
                          collate_fn=collate_fn, pin_memory=True)
valid_loader = DataLoader(valid_dataset, batch_size=1,
                          shuffle=False, num_workers=2,
                          collate_fn=collate_fn, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=1,
                          shuffle=False, num_workers=2,
                          collate_fn=collate_fn, pin_memory=True)

print(f"\n✅ STEP 6 COMPLETE — DataLoaders ready")
print(f"   Train batches : {len(train_loader)}")
print(f"   Valid batches : {len(valid_loader)}")
print(f"   Test batches  : {len(test_loader)}")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 7 ── BUILD MODEL                                                       │
# └─────────────────────────────────────────────────────────────────────────────┘
def build_maskrcnn(num_classes):
    model = maskrcnn_resnet50_fpn(pretrained=True)

    # Replace box/classification head
    in_box = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_box, num_classes)

    # Replace mask head
    in_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
    model.roi_heads.mask_predictor = MaskRCNNPredictor(in_mask, 256, num_classes)

    return model


print("\n⏳ STEP 7 — Building Mask R-CNN...")
model = build_maskrcnn(NUM_CLASSES).to(device)

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\n✅ STEP 7 COMPLETE")
print(f"   Output classes    : {NUM_CLASSES}  →  {CLASS_NAMES}")
print(f"   Trainable params  : {trainable:,}")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 8 ── OPTIMIZER & SCHEDULER                                             │
# └─────────────────────────────────────────────────────────────────────────────┘
params       = [p for p in model.parameters() if p.requires_grad]
optimizer    = torch.optim.SGD(params, lr=0.005, momentum=0.9, weight_decay=0.0005)
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.1)

print(f"\n✅ STEP 8 COMPLETE — SGD lr=0.005 | StepLR step=3 gamma=0.1")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 9 ── TRAIN & VALIDATE FUNCTIONS                                        │
# └─────────────────────────────────────────────────────────────────────────────┘
def train_one_epoch(model, optimizer, loader, device, epoch, num_epochs):
    model.train()
    total_loss = 0.0
    t0 = time.time()
    print(f"\n  {'─'*60}")
    print(f"  📌 EPOCH {epoch}/{num_epochs}  —  TRAINING")
    print(f"  {'─'*60}")

    for i, (images, targets) in enumerate(loader):
        images  = [img.to(device) for img in images]
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        loss_dict = model(images, targets)
        losses    = sum(loss for loss in loss_dict.values())

        optimizer.zero_grad()
        losses.backward()
        optimizer.step()
        total_loss += losses.item()

        if i % 5 == 0 or i == len(loader) - 1:
            print(f"    [{i+1:3d}/{len(loader)}] "
                  f"total={losses.item():.4f} | "
                  f"cls={loss_dict['loss_classifier'].item():.4f} | "
                  f"box={loss_dict['loss_box_reg'].item():.4f} | "
                  f"mask={loss_dict['loss_mask'].item():.4f} | "
                  f"rpn={loss_dict['loss_objectness'].item():.4f} "
                  f"({time.time()-t0:.1f}s)")

    avg = total_loss / len(loader)
    print(f"\n   Epoch {epoch} TRAIN avg loss: {avg:.5f}")
    return avg


def validate_one_epoch(model, loader, device, epoch):
    model.train()   # train mode needed to get loss dict
    total_loss = 0.0
    print(f"\n   EPOCH {epoch}  —  VALIDATION")

    with torch.no_grad():
        for images, targets in loader:
            images  = [img.to(device) for img in images]
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
            loss_dict = model(images, targets)
            total_loss += sum(loss for loss in loss_dict.values()).item()

    avg = total_loss / len(loader)
    print(f"  Epoch {epoch} VALID avg loss: {avg:.5f}")
    return avg

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 10 ── TRAINING LOOP                                                    │
# └─────────────────────────────────────────────────────────────────────────────┘
NUM_EPOCHS    = 10
best_val_loss = float("inf")
train_losses, val_losses = [], []
os.makedirs("checkpoints", exist_ok=True)

print("\n" + "=" * 65)
print("  STARTING TRAINING")
print(f"  Epochs     : {NUM_EPOCHS}")
print(f"  Batch size : {BATCH_SIZE}")
print(f"  Device     : {device}")
print(f"  Classes    : {CLASS_NAMES}")
print("=" * 65)

for epoch in range(1, NUM_EPOCHS + 1):
    tl = train_one_epoch(model, optimizer, train_loader, device, epoch, NUM_EPOCHS)
    vl = validate_one_epoch(model, valid_loader, device, epoch)
    lr_scheduler.step()

    train_losses.append(tl)
    val_losses.append(vl)

    print(f"\n  📊 Epoch {epoch:2d}  train={tl:.5f}  valid={vl:.5f}  "
          f"lr={optimizer.param_groups[0]['lr']:.6f}")

    if vl < best_val_loss:
        best_val_loss = vl
        torch.save({
            "epoch":                epoch,
            "model_state_dict":     model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "val_loss":             vl,
            "class_names":          CLASS_NAMES,
            "num_classes":          NUM_CLASSES,
        }, "checkpoints/best_model.pth")
        print(f"  💾 Best model saved! val_loss={vl:.5f}")

    torch.save({"epoch": epoch, "model_state_dict": model.state_dict(),
                "val_loss": vl}, f"checkpoints/epoch_{epoch:02d}.pth")

print(f"\n🎉 TRAINING COMPLETE — Best val loss: {best_val_loss:.5f}")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 11 ── PLOT LOSS CURVES                                                 │
# └─────────────────────────────────────────────────────────────────────────────┘
fig, ax = plt.subplots(figsize=(10, 5))
fig.patch.set_facecolor("#0d0d0d")
ax.set_facecolor("#0d0d0d")

ep = range(1, NUM_EPOCHS + 1)
ax.plot(ep, train_losses, "o-", color="#00d4ff", lw=2.5, ms=7, label="Train Loss")
ax.plot(ep, val_losses,   "o-", color="#ff6b35", lw=2.5, ms=7, label="Valid Loss")

best_ep = val_losses.index(min(val_losses)) + 1
ax.axvline(best_ep, color="#ffcc00", ls="--", alpha=0.6, lw=1.5)
ax.annotate(f"Best\nEpoch {best_ep}",
            xy=(best_ep, min(val_losses)),
            xytext=(best_ep + 0.3, min(val_losses) + 0.02),
            color="#ffcc00", fontsize=9)

ax.set_xlabel("Epoch", color="white", fontsize=12)
ax.set_ylabel("Loss",  color="white", fontsize=12)
ax.set_title("Mask R-CNN — Guns Detection Training", color="white",
             fontsize=14, fontweight="bold", pad=15)
ax.tick_params(colors="white")
ax.spines[:].set_color("#333")
ax.legend(facecolor="#1a1a1a", labelcolor="white", fontsize=11)
ax.grid(True, alpha=0.15, color="white")
ax.set_xticks(list(ep))
plt.tight_layout()
plt.savefig("training_loss_curves.png", dpi=150,
            bbox_inches="tight", facecolor=fig.get_facecolor())
plt.show()
print("✅ STEP 11 COMPLETE — Loss curves saved")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 12 ── LOAD BEST MODEL & INFERENCE                                      │
# └─────────────────────────────────────────────────────────────────────────────┘
print("\n⏳ STEP 12 — Loading best model for inference...")
ckpt = torch.load("checkpoints/best_model.pth", map_location=device)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()
print(f"✅ Best model loaded (epoch {ckpt['epoch']}, val_loss={ckpt['val_loss']:.5f})")


def run_inference(model, image_input, device, conf_threshold=0.5):
    if isinstance(image_input, str):
        image_pil = Image.open(image_input).convert("RGB")
    else:
        image_pil = image_input

    img_t = TF.to_tensor(image_pil).to(device)
    with torch.no_grad():
        pred = model([img_t])[0]

    keep = pred["scores"] > conf_threshold
    return {
        "image":  image_pil,
        "boxes":  pred["boxes"][keep].cpu().numpy(),
        "labels": pred["labels"][keep].cpu().numpy(),
        "scores": pred["scores"][keep].cpu().numpy(),
        "masks":  pred["masks"][keep].cpu().numpy(),
    }


def draw_predictions(result, class_names, mask_threshold=0.5,
                     title="Predictions", save_path=None):
    image_np = np.array(result["image"]).copy()
    overlay  = image_np.copy()
    n        = len(result["boxes"])

    np.random.seed(99)
    legend_patches = []

    for i in range(n):
        color        = tuple(np.random.randint(80, 240, 3).tolist())
        x1,y1,x2,y2 = result["boxes"][i].astype(int)
        cls_id       = result["labels"][i]
        score        = result["scores"][i]
        mask         = result["masks"][i, 0] > mask_threshold
        cls_name     = (class_names[cls_id]
                        if cls_id < len(class_names) else f"cls_{cls_id}")

        # Fill mask
        overlay[mask] = (overlay[mask] * 0.4 +
                         np.array(color, dtype=np.uint8) * 0.6).astype(np.uint8)

        # Mask outline
        contours, _ = cv2.findContours(mask.astype(np.uint8),
                                       cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        cv2.drawContours(image_np, contours, -1, color, 2)

        # Box + label
        cv2.rectangle(image_np, (x1, y1), (x2, y2), color, 2)
        label_text  = f"{cls_name}: {score:.2f}"
        (tw, th), _ = cv2.getTextSize(label_text, cv2.FONT_HERSHEY_SIMPLEX, 0.55, 2)
        cv2.rectangle(image_np, (x1, y1-th-10), (x1+tw+4, y1), color, -1)
        cv2.putText(image_np, label_text, (x1+2, y1-4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255,255,255), 2)

        legend_patches.append(mpatches.Patch(
            color=[c/255 for c in color],
            label=f"#{i+1} {cls_name} ({score:.2f})"
        ))

    final = cv2.addWeighted(overlay, 0.55, image_np, 0.45, 0)

    fig = plt.figure(figsize=(14, 6), facecolor="#0d0d0d")
    gs  = gridspec.GridSpec(1, 2, figure=fig, wspace=0.04)

    ax1 = fig.add_subplot(gs[0])
    ax1.imshow(result["image"]); ax1.axis("off")
    ax1.set_title("Original", color="white", fontsize=12)
    ax1.set_facecolor("#0d0d0d")

    ax2 = fig.add_subplot(gs[1])
    ax2.imshow(final); ax2.axis("off")
    ax2.set_title(f"{n} Detection(s)", color="white", fontsize=12)
    ax2.set_facecolor("#0d0d0d")
    if legend_patches:
        ax2.legend(handles=legend_patches, loc="upper right",
                   fontsize=9, framealpha=0.85,
                   facecolor="#1a1a1a", labelcolor="white")

    fig.suptitle(title, color="white", fontsize=13, fontweight="bold", y=1.01)
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight",
                    facecolor=fig.get_facecolor())
    plt.show()
    return final


# ── Run on test images ───────────────────────────────────────────────────────
test_imgs = sorted([
    os.path.join(TEST_IMG_DIR, f) for f in os.listdir(TEST_IMG_DIR)
    if f.lower().endswith((".jpg",".jpeg",".png"))
])

print(f"\n   Found {len(test_imgs)} test images")
os.makedirs("results", exist_ok=True)
all_results = []

for i, img_path in enumerate(test_imgs):
    result  = run_inference(model, img_path, device, conf_threshold=0.5)
    n_det   = len(result["boxes"])
    all_results.append(result)

    print(f"   [{i+1:2d}/{len(test_imgs)}] "
          f"{os.path.basename(img_path):<40} → {n_det} detection(s)")
    for j in range(n_det):
        cid  = result["labels"][j]
        name = CLASS_NAMES[cid] if cid < len(CLASS_NAMES) else f"cls_{cid}"
        print(f"          • {name:<22} score={result['scores'][j]:.3f}")

    draw_predictions(
        result, CLASS_NAMES,
        title=f"Test {i+1}: {os.path.basename(img_path)}",
        save_path=f"results/pred_{i+1:03d}.png"
    )

print(f"\n✅ STEP 12 COMPLETE — Results saved to results/")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ STEP 13 ── SUMMARY GRID                                                     │
# └─────────────────────────────────────────────────────────────────────────────┘
n     = min(len(all_results), 9)
cols  = 3
rows  = (n + cols - 1) // cols
fig, axes = plt.subplots(rows, cols, figsize=(6*cols, 5*rows))
axes  = np.array(axes).flatten() if rows*cols > 1 else [axes]
fig.patch.set_facecolor("#0a0a0a")
fig.suptitle("Instance Segmentation Results — Guns Detection",
             color="white", fontsize=16, fontweight="bold", y=1.01)

for idx in range(n):
    r     = all_results[idx]
    img   = np.array(r["image"]).copy()
    np.random.seed(99)
    for j in range(len(r["boxes"])):
        color = tuple(np.random.randint(80, 240, 3).tolist())
        mask  = r["masks"][j, 0] > 0.5
        x1,y1,x2,y2 = r["boxes"][j].astype(int)
        img[mask] = (img[mask]*0.45 + np.array(color)*0.55).astype(np.uint8)
        cv2.rectangle(img, (x1,y1), (x2,y2), color, 2)
        cv2.putText(img, f"{r['scores'][j]:.2f}", (x1, max(y1-5,15)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255,255,255), 2)

    axes[idx].imshow(img)
    axes[idx].set_title(f"Image {idx+1} — {len(r['boxes'])} det.",
                        color="white", fontsize=10)
    axes[idx].axis("off")
    axes[idx].set_facecolor("#0a0a0a")

for ax in axes[n:]:
    ax.set_visible(False)

plt.tight_layout()
plt.savefig("results/summary_grid.png", dpi=150,
            bbox_inches="tight", facecolor=fig.get_facecolor())
plt.show()
print("✅ STEP 13 COMPLETE — Summary grid saved")

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ FINAL SUMMARY                                                               │
# └─────────────────────────────────────────────────────────────────────────────┘
total_det = sum(len(r["boxes"]) for r in all_results)
print("\n" + "=" * 65)
print("  ✅  FULL PIPELINE COMPLETE")
print("=" * 65)
print(f"""
  📁  OUTPUT FILES:
      ground_truth_labels.png     ← your labeled data preview
      training_loss_curves.png    ← train vs validation loss
      results/pred_*.png          ← per-image inference
      results/summary_grid.png    ← all results in one grid
      checkpoints/best_model.pth  ← best model weights

  📊  STATS:
      Classes     : {CLASS_NAMES[1:]}
      Best val loss: {best_val_loss:.5f}
      Test images  : {len(all_results)}
      Total dets   : {total_det}
      Avg/image    : {total_det/max(len(all_results),1):.1f}

  🔁  TO RELOAD MODEL LATER:
      ckpt  = torch.load("checkpoints/best_model.pth")
      model = build_maskrcnn(ckpt["num_classes"])
      model.load_state_dict(ckpt["model_state_dict"])
      model.eval()
""")