# -*- coding: utf-8 -*-
"""faster rcnn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YQnFhCUjYmZkR83p2fkxAg5nKtmixqV
"""

!pip install roboflow -q
!pip install pycocotools -q

import torch

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print("Using device:", device)

if device.type == 'cuda':
    print("GPU Name:", torch.cuda.get_device_name(0))
    print("GPU is ready!")
else:
    print("WARNING: No GPU found!")
    print("Go to Runtime > Change Runtime Type > T4 GPU > Save")
    print("Then run all cells again from the top")

import torch
import torchvision
from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
import torchvision.transforms as T

import os
import json
import time
import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

print("All libraries imported successfully!")
print("PyTorch version:", torch.__version__)
print("Torchvision version:", torchvision.__version__)

from roboflow import Roboflow

rf = Roboflow(api_key="A2YllykE6xoTtfId5TZT")

# This prints your exact workspace name
workspace = rf.workspace()
print(workspace)

from roboflow import Roboflow

rf      = Roboflow(api_key="A2YllykE6xoTtfId5TZT")
project = rf.workspace("baheejs-workspace").project("guns-ldyqf")
dataset = project.version(1).download("coco")

import os
print("\nFolders created in /content:")
for f in os.listdir("/content"):
    print(" ", f)
print("\nCopy the folder name above that starts with 'guns'")

from roboflow import Roboflow

rf      = Roboflow(api_key="A2YllykE6xoTtfId5TZT")
project = rf.workspace("baheejs-workspace").project("guns-ldyqf")
dataset = project.version(6).download("coco")

import os
print("\nFolders created in /content:")
for f in os.listdir("/content"):
    print(" ", f)

import os, json

DATASET_ROOT = "/content/Guns-6"

TRAIN_DIR  = os.path.join(DATASET_ROOT, "train")
VALID_DIR  = os.path.join(DATASET_ROOT, "valid")
TEST_DIR   = os.path.join(DATASET_ROOT, "test")

TRAIN_JSON = os.path.join(TRAIN_DIR, "_annotations.coco.json")
VALID_JSON = os.path.join(VALID_DIR, "_annotations.coco.json")
TEST_JSON  = os.path.join(TEST_DIR,  "_annotations.coco.json")

for path in [TRAIN_JSON, VALID_JSON, TEST_JSON]:
    exists = "FOUND" if os.path.exists(path) else "MISSING"
    print(f"{exists} → {path}")

with open(TRAIN_JSON, "r") as f:
    coco_meta = json.load(f)

CLASS_NAMES = ["__background__"] + [c["name"] for c in coco_meta["categories"]]
NUM_CLASSES = len(CLASS_NAMES)

print("\nYour classes:")
for i, name in enumerate(CLASS_NAMES):
    print(f"  {i}: {name}")
print(f"\nTotal classes     : {NUM_CLASSES}")
print(f"Training images   : {len(coco_meta['images'])}")
print(f"Training annotations: {len(coco_meta['annotations'])}")

class RoboflowDataset(Dataset):
    def __init__(self, img_dir, ann_file, transforms=None):
        self.img_dir    = img_dir
        self.transforms = transforms
        self.coco       = COCO(ann_file)
        self.img_ids    = list(self.coco.imgs.keys())
        print(f"  Loaded {len(self.img_ids)} images from {ann_file}")

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_id   = self.img_ids[idx]
        img_info = self.coco.imgs[img_id]
        img_path = os.path.join(self.img_dir, img_info["file_name"])

        # Load image
        image = Image.open(img_path).convert("RGB")

        # Get annotations for this image
        ann_ids = self.coco.getAnnIds(imgIds=img_id)
        anns    = self.coco.loadAnns(ann_ids)

        boxes, labels = [], []
        for ann in anns:
            x, y, w, h = ann["bbox"]
            if w > 1 and h > 1:                       # skip tiny bad boxes
                boxes.append([x, y, x + w, y + h])   # convert to x1,y1,x2,y2
                labels.append(ann["category_id"])

        # Handle images with no valid annotations
        if len(boxes) == 0:
            boxes  = torch.zeros((0, 4), dtype=torch.float32)
            labels = torch.zeros((0,),   dtype=torch.int64)
        else:
            boxes  = torch.tensor(boxes,  dtype=torch.float32)
            labels = torch.tensor(labels, dtype=torch.int64)

        target = {
            "boxes":    boxes,
            "labels":   labels,
            "image_id": torch.tensor([img_id]),
            "area":     (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0]) if len(boxes) else torch.zeros(0),
            "iscrowd":  torch.zeros(len(labels), dtype=torch.int64),
        }

        if self.transforms:
            image = self.transforms(image)

        return image, target


def collate_fn(batch):
    return tuple(zip(*batch))


def get_transform():
    return T.Compose([T.ToTensor()])


print("Creating datasets...")
train_dataset = RoboflowDataset(TRAIN_DIR, TRAIN_JSON, get_transform())
valid_dataset = RoboflowDataset(VALID_DIR, VALID_JSON, get_transform())
test_dataset  = RoboflowDataset(TEST_DIR,  TEST_JSON,  get_transform())

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True,
                          num_workers=2, collate_fn=collate_fn)
valid_loader = DataLoader(valid_dataset, batch_size=2, shuffle=False,
                          num_workers=2, collate_fn=collate_fn)
test_loader  = DataLoader(test_dataset,  batch_size=1, shuffle=False,
                          num_workers=2, collate_fn=collate_fn)

print(f"\nTrain batches : {len(train_loader)}")
print(f"Valid batches : {len(valid_loader)}")
print(f"Test  batches : {len(test_loader)}")
print("Datasets ready!")

def build_faster_rcnn(num_classes):
    # Load pretrained Faster RCNN (trained on COCO 91 classes)
    model = fasterrcnn_resnet50_fpn(weights="DEFAULT")

    # Replace the classifier head with one for YOUR number of classes
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

    return model


model = build_faster_rcnn(NUM_CLASSES)
model.to(device)

# Optimizer — SGD with momentum (standard for Faster RCNN)
params    = [p for p in model.parameters() if p.requires_grad]
optimizer = torch.optim.SGD(params, lr=0.005, momentum=0.9, weight_decay=0.0005)

# Learning rate scheduler — reduces LR every 3 epochs
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.1)

total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Model: Faster R-CNN with ResNet50-FPN backbone")
print(f"Number of your classes : {NUM_CLASSES}")
print(f"Trainable parameters   : {total_params:,}")
print(f"Running on             : {device}")
print("Model ready!")

!pip install roboflow pycocotools -q

from roboflow import Roboflow

rf      = Roboflow(api_key="A2YllykE6xoTtfId5TZT")
project = rf.workspace("baheejs-workspace").project("guns-ldyqf")
dataset = project.version(6).download("coco")

import os
print(os.listdir("/content"))

# ============================================================
#   FASTER RCNN — GUNS DETECTION — SINGLE CELL
# ============================================================
import os, json, time, cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

import torch
import torchvision.transforms as T
from torch.utils.data import Dataset, DataLoader
from torchvision.models.detection import fasterrcnn_resnet50_fpn, FasterRCNN_ResNet50_FPN_Weights
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print(f"Device: {device}")

# ── STEP 1: PATHS ──────────────────────────────────────────
DATASET_ROOT = "/content/Guns-6"
TRAIN_DIR    = os.path.join(DATASET_ROOT, "train")
VALID_DIR    = os.path.join(DATASET_ROOT, "valid")
TEST_DIR     = os.path.join(DATASET_ROOT, "test")
TRAIN_JSON   = os.path.join(TRAIN_DIR, "_annotations.coco.json")
VALID_JSON   = os.path.join(VALID_DIR, "_annotations.coco.json")
TEST_JSON    = os.path.join(TEST_DIR,  "_annotations.coco.json")
RESULTS_DIR  = "/content/results"
os.makedirs(RESULTS_DIR, exist_ok=True)

CLASS_NAMES  = ["__background__", "Guns"]
NUM_CLASSES  = 2

# ── STEP 2: FIX ANNOTATIONS TO 1 CLASS ────────────────────
def fix_annotations(path):
    with open(path) as f:
        data = json.load(f)
    data["categories"] = [{"id": 1, "name": "Guns", "supercategory": "none"}]
    for ann in data["annotations"]:
        ann["category_id"] = 1
    with open(path, "w") as f:
        json.dump(data, f)
    print(f"  ✅ Fixed: {path}")

print("Fixing to Guns only...")
fix_annotations(TRAIN_JSON)
fix_annotations(VALID_JSON)
fix_annotations(TEST_JSON)

# ── STEP 3: DATASET CLASS ─────────────────────────────────
class GunsDataset(Dataset):
    def __init__(self, img_dir, ann_file):
        self.img_dir = img_dir
        self.coco    = COCO(ann_file)
        self.img_ids = list(self.coco.imgs.keys())
        self.tf      = T.Compose([T.ToTensor()])
        print(f"  Loaded {len(self.img_ids)} images")

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_id   = self.img_ids[idx]
        img_info = self.coco.imgs[img_id]
        image    = Image.open(os.path.join(self.img_dir, img_info["file_name"])).convert("RGB")
        anns     = self.coco.loadAnns(self.coco.getAnnIds(imgIds=img_id))

        boxes, labels = [], []
        for ann in anns:
            x, y, w, h = ann["bbox"]
            if w > 1 and h > 1:
                boxes.append([x, y, x+w, y+h])
                labels.append(1)

        if len(boxes) == 0:
            boxes  = torch.zeros((0,4), dtype=torch.float32)
            labels = torch.zeros((0,),  dtype=torch.int64)
        else:
            boxes  = torch.tensor(boxes,  dtype=torch.float32)
            labels = torch.tensor(labels, dtype=torch.int64)

        target = {
            "boxes"   : boxes,
            "labels"  : labels,
            "image_id": torch.tensor([img_id]),
            "area"    : (boxes[:,3]-boxes[:,1])*(boxes[:,2]-boxes[:,0]) if len(boxes) else torch.zeros(0),
            "iscrowd" : torch.zeros(len(labels), dtype=torch.int64)
        }
        return self.tf(image), target

def collate_fn(batch):
    return tuple(zip(*batch))

print("\nLoading datasets...")
train_ds = GunsDataset(TRAIN_DIR, TRAIN_JSON)
valid_ds = GunsDataset(VALID_DIR, VALID_JSON)
test_ds  = GunsDataset(TEST_DIR,  TEST_JSON)

train_loader = DataLoader(train_ds, batch_size=4, shuffle=True,  num_workers=2, collate_fn=collate_fn)
valid_loader = DataLoader(valid_ds, batch_size=2, shuffle=False, num_workers=2, collate_fn=collate_fn)
test_loader  = DataLoader(test_ds,  batch_size=1, shuffle=False, num_workers=2, collate_fn=collate_fn)

# ── STEP 4: BUILD MODEL ────────────────────────────────────
print("\nBuilding model...")
model = fasterrcnn_resnet50_fpn(weights=FasterRCNN_ResNet50_FPN_Weights.DEFAULT)
in_f  = model.roi_heads.box_predictor.cls_score.in_features
model.roi_heads.box_predictor = FastRCNNPredictor(in_f, NUM_CLASSES)
model = model.to(device)
print(f"  ✅ Faster RCNN ready | Classes: {CLASS_NAMES} | Device: {device}")

# ── STEP 5: TRAIN ──────────────────────────────────────────
NUM_EPOCHS   = 15
SAVE_PATH    = "/content/best_model.pth"
optimizer    = torch.optim.SGD(model.parameters(), lr=0.005, momentum=0.9, weight_decay=0.0005)
scheduler    = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)
epoch_losses = []
best_loss    = float("inf")

print(f"\n🚀 Training {NUM_EPOCHS} epochs on {device}...")
print("=" * 60)

for epoch in range(1, NUM_EPOCHS+1):
    model.train()
    total_loss  = 0.0
    count       = 0
    t0          = time.time()

    for i, (images, targets) in enumerate(train_loader):
        images  = [img.to(device) for img in images]
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        losses = sum(model(images, targets).values())
        optimizer.zero_grad()
        losses.backward()
        optimizer.step()

        total_loss += losses.item()
        count      += 1

        if (i+1) % 10 == 0:
            print(f"  Ep {epoch}/{NUM_EPOCHS} | Batch {i+1}/{len(train_loader)} | Loss: {losses.item():.4f}")

    scheduler.step()
    avg = total_loss / count
    epoch_losses.append(avg)
    marker = ""
    if avg < best_loss:
        best_loss = avg
        torch.save(model.state_dict(), SAVE_PATH)
        marker = " ✅ SAVED"
    print(f"\n── Epoch {epoch} | Avg Loss: {avg:.4f} | Time: {time.time()-t0:.0f}s{marker}\n")

print(f"🎉 Training done! Best loss: {best_loss:.4f}")

# ── STEP 6: PLOT LOSS CURVE ────────────────────────────────
plt.figure(figsize=(10,5))
plt.plot(range(1, len(epoch_losses)+1), epoch_losses,
         marker='o', color='crimson', linewidth=2.5, markersize=7)
plt.axhline(y=best_loss, color='green', linestyle='--', label=f'Best: {best_loss:.4f}')
plt.fill_between(range(1, len(epoch_losses)+1), epoch_losses, alpha=0.15, color='crimson')
plt.title('Training Loss Curve', fontsize=14, fontweight='bold')
plt.xlabel('Epoch'); plt.ylabel('Loss')
plt.xticks(range(1, len(epoch_losses)+1))
plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/loss_curve.png", dpi=150)
plt.show()

# ── STEP 7: LOAD BEST MODEL ────────────────────────────────
model.load_state_dict(torch.load(SAVE_PATH, map_location=device))
model.eval()
print("✅ Best model loaded!")

# ── STEP 8: DETECTION FUNCTIONS ───────────────────────────
def detect(img_tensor, threshold=0.5):
    with torch.no_grad():
        out = model([img_tensor.to(device)])[0]
    b = out['boxes'].cpu().numpy()
    l = out['labels'].cpu().numpy()
    s = out['scores'].cpu().numpy()
    mask = s >= threshold
    return b[mask], l[mask], s[mask]

def draw_boxes(img_tensor, boxes, labels, scores, color=(0,220,0)):
    img = (img_tensor.permute(1,2,0).numpy()*255).astype(np.uint8)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    for box, label, score in zip(boxes, labels, scores):
        x1,y1,x2,y2 = map(int, box)
        text = f"{CLASS_NAMES[min(label, len(CLASS_NAMES)-1)]}: {score:.2f}"
        cv2.rectangle(img, (x1,y1), (x2,y2), color, 3)
        (tw,th),_ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(img, (x1,y1-th-8), (x1+tw+4,y1), color, -1)
        cv2.putText(img, text, (x1+2,y1-4), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,0), 2)
    return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# ── STEP 9: GROUND TRUTH vs PREDICTION ───────────────────
CONFIDENCE       = 0.5
img_t, target    = test_ds[0]
boxes,labels,scores = detect(img_t, CONFIDENCE)

pred_img = draw_boxes(img_t, boxes, labels, scores, color=(0,220,0))
gt_img   = draw_boxes(img_t, target['boxes'].numpy(),
                      target['labels'].numpy(),
                      np.ones(len(target['labels'])), color=(220,0,0))

fig, axes = plt.subplots(1,2, figsize=(16,7))
axes[0].imshow(gt_img);   axes[0].set_title("Ground Truth (RED)",    fontsize=13, fontweight='bold', color='red');   axes[0].axis('off')
axes[1].imshow(pred_img); axes[1].set_title("Prediction (GREEN)",    fontsize=13, fontweight='bold', color='green'); axes[1].axis('off')
plt.suptitle("Faster RCNN — Guns Detection", fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/single_result.png", dpi=150)
plt.show()

# ── STEP 10: GRID OF 9 TEST IMAGES ────────────────────────
NUM_SHOW = min(9, len(test_ds))
fig, axes = plt.subplots(3, 3, figsize=(18,18))
axes = axes.flatten()
for idx in range(NUM_SHOW):
    img_t, _ = test_ds[idx]
    b,l,s    = detect(img_t, CONFIDENCE)
    axes[idx].imshow(draw_boxes(img_t, b, l, s))
    axes[idx].set_title(f"Image {idx+1} | {len(b)} gun(s)", fontweight='bold')
    axes[idx].axis('off')
for idx in range(NUM_SHOW, 9):
    axes[idx].axis('off')
plt.suptitle("Test Grid — Guns Detection", fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/grid_results.png", dpi=150)
plt.show()

# ── STEP 11: THRESHOLD COMPARISON ─────────────────────────
img_t, _ = test_ds[0]
fig, axes = plt.subplots(1,3, figsize=(18,6))
for ax, thresh in zip(axes, [0.3, 0.5, 0.7]):
    b,l,s = detect(img_t, thresh)
    ax.imshow(draw_boxes(img_t, b, l, s))
    ax.set_title(f"Threshold={thresh} | {len(b)} detection(s)", fontweight='bold')
    ax.axis('off')
plt.suptitle("Confidence Threshold Comparison", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{RESULTS_DIR}/threshold_comparison.png", dpi=150)
plt.show()

# ── STEP 12: mAP SCORE ────────────────────────────────────
print("\nComputing mAP...")
coco_gt      = COCO(TEST_JSON)
coco_results = []
model.eval()

with torch.no_grad():
    for images, targets in test_loader:
        images  = [img.to(device) for img in images]
        outputs = model(images)
        for out, tgt in zip(outputs, targets):
            img_id = tgt['image_id'].item()
            for box, score, label in zip(out['boxes'].cpu().numpy(),
                                         out['scores'].cpu().numpy(),
                                         out['labels'].cpu().numpy()):
                x1,y1,x2,y2 = box
                coco_results.append({
                    "image_id"   : img_id,
                    "category_id": int(label),
                    "bbox"       : [float(x1),float(y1),float(x2-x1),float(y2-y1)],
                    "score"      : float(score)
                })

if coco_results:
    coco_dt   = coco_gt.loadRes(coco_results)
    coco_eval = COCOeval(coco_gt, coco_dt, 'bbox')
    coco_eval.evaluate()
    coco_eval.accumulate()
    coco_eval.summarize()
    map_50    = coco_eval.stats[1]
    map_50_95 = coco_eval.stats[0]
    print(f"\n{'='*40}")
    print(f"  📊 mAP@0.50      = {map_50*100:.1f}%")
    print(f"  📊 mAP@0.50:0.95 = {map_50_95*100:.1f}%")
    print(f"{'='*40}")

print("\n✅ ALL DONE! Results saved in /content/results/")
print("  loss_curve.png")
print("  single_result.png")
print("  grid_results.png")
print("  threshold_comparison.png")
print("  best_model.pth")