# -*- coding: utf-8 -*-
"""pre-trained faster rcnn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WUxs-8_m_sLgx4n5OYCexblqeLqEIDlc
"""

import torch
import torch.nn as nn
import torchvision
from torchvision.models.detection import FasterRCNN
from torchvision.models.detection.rpn import AnchorGenerator

# ════════════════════════════════════════════════════════════
# ORIGINAL BACKBONE — 4 Conv Layers
# ════════════════════════════════════════════════════════════
class OriginalBackbone(nn.Module):
    def __init__(self):
        super(OriginalBackbone, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3,   64,  kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2, 2),
            nn.Conv2d(64,  128, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2, 2),
            nn.Conv2d(128, 256, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2, 2),
            nn.Conv2d(256, 512, kernel_size=3, padding=1), nn.ReLU(),
        )
        self.out_channels = 512

    def forward(self, x):
        return self.features(x)

# ════════════════════════════════════════════════════════════
# CHANGED BACKBONE — 6 Conv Layers (Task 1)
# ════════════════════════════════════════════════════════════
class ChangedBackbone(nn.Module):
    def __init__(self):
        super(ChangedBackbone, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3,   32,  kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2, 2),  # NEW
            nn.Conv2d(32,  64,  kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2, 2),  # NEW
            nn.Conv2d(64,  128, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2, 2),
            nn.Conv2d(128, 256, kernel_size=3, padding=1), nn.ReLU(),
            nn.Conv2d(256, 512, kernel_size=3, padding=1), nn.ReLU(),
            nn.Conv2d(512, 512, kernel_size=3, padding=1), nn.ReLU(),  # NEW
        )
        self.out_channels = 512

    def forward(self, x):
        return self.features(x)

# ════════════════════════════════════════════════════════════
# BUILD BOTH MODELS
# ════════════════════════════════════════════════════════════
def build_model(backbone):
    anchor_generator = AnchorGenerator(
        sizes=((32, 64, 128, 256, 512),),
        aspect_ratios=((0.5, 1.0, 2.0),)
    )
    roi_pooler = torchvision.ops.MultiScaleRoIAlign(
        featmap_names=['0'], output_size=7, sampling_ratio=2
    )
    model = FasterRCNN(
        backbone=backbone,
        num_classes=2,
        rpn_anchor_generator=anchor_generator,
        box_roi_pool=roi_pooler
    )
    return model

original_model = build_model(OriginalBackbone())
changed_model  = build_model(ChangedBackbone())

# ════════════════════════════════════════════════════════════
# COUNT PARAMETERS
# ════════════════════════════════════════════════════════════
def count_params(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

orig_params    = count_params(original_model)
changed_params = count_params(changed_model)

# ════════════════════════════════════════════════════════════
# PRINT COMPARISON
# ════════════════════════════════════════════════════════════
print("=" * 55)
print("         TASK 1 — CHANGE NUMBER OF LAYERS")
print("=" * 55)

print("\n📌 ORIGINAL MODEL — 4 Conv Layers")
print("-" * 55)
print("  Layer 1:  Conv2d(3   → 64)  + ReLU + MaxPool")
print("  Layer 2:  Conv2d(64  → 128) + ReLU + MaxPool")
print("  Layer 3:  Conv2d(128 → 256) + ReLU + MaxPool")
print("  Layer 4:  Conv2d(256 → 512) + ReLU")
print(f"\n  Total Trainable Parameters: {orig_params:,}")

print("\n📌 CHANGED MODEL — 6 Conv Layers")
print("-" * 55)
print("  Layer 1:  Conv2d(3   → 32)  + ReLU + MaxPool  ← NEW")
print("  Layer 2:  Conv2d(32  → 64)  + ReLU + MaxPool  ← NEW")
print("  Layer 3:  Conv2d(64  → 128) + ReLU + MaxPool")
print("  Layer 4:  Conv2d(128 → 256) + ReLU")
print("  Layer 5:  Conv2d(256 → 512) + ReLU")
print("  Layer 6:  Conv2d(512 → 512) + ReLU            ← NEW")
print(f"\n  Total Trainable Parameters: {changed_params:,}")

print("\n" + "=" * 55)
print("  COMPARISON SUMMARY")
print("=" * 55)
print(f"  Original Layers    : 4")
print(f"  Changed  Layers    : 6")
print(f"  Extra Layers Added : 2")
print(f"  Original Params    : {orig_params:,}")
print(f"  Changed  Params    : {changed_params:,}")
print(f"  Extra Params       : {changed_params - orig_params:,}")
print("=" * 55)

# ════════════════════════════════════════════════════════════
# TEST BOTH MODELS WITH DUMMY INPUT
# ════════════════════════════════════════════════════════════
print("\n Running forward pass on both models...")

original_model.eval()
changed_model.eval()

dummy_image = [torch.rand(3, 224, 224)]  # fake image

with torch.no_grad():
    out1 = original_model(dummy_image)
    out2 = changed_model(dummy_image)

print("\n Original Model Output:")
print(f"   Boxes  detected : {len(out1[0]['boxes'])}")
print(f"   Scores detected : {len(out1[0]['scores'])}")
print(f"   Labels detected : {len(out1[0]['labels'])}")

print("\n Changed Model Output:")
print(f"   Boxes  detected : {len(out2[0]['boxes'])}")
print(f"   Scores detected : {len(out2[0]['scores'])}")
print(f"   Labels detected : {len(out2[0]['labels'])}")

print("\n Task 1 Complete!")

# ════════════════════════════════════════════════════════════
# PLOT COMPARISON CHART
# ════════════════════════════════════════════════════════════
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Left — Layer comparison
models     = ['Original\n(4 Layers)', 'Changed\n(6 Layers)']
num_layers = [4, 6]
colors     = ['#3498db', '#e74c3c']

axes[0].bar(models, num_layers, color=colors, width=0.4, edgecolor='black')
axes[0].set_title('Number of Conv Layers', fontsize=13, fontweight='bold')
axes[0].set_ylabel('Layers')
axes[0].set_ylim(0, 8)
for i, v in enumerate(num_layers):
    axes[0].text(i, v + 0.1, str(v), ha='center', fontsize=14, fontweight='bold')

# Right — Parameter comparison
num_params = [orig_params, changed_params]
axes[1].bar(models, num_params, color=colors, width=0.4, edgecolor='black')
axes[1].set_title('Total Trainable Parameters', fontsize=13, fontweight='bold')
axes[1].set_ylabel('Parameters')
for i, v in enumerate(num_params):
    axes[1].text(i, v + 5000, f'{v:,}', ha='center', fontsize=11, fontweight='bold')

plt.suptitle('Task 1 — Original vs Changed Backbone', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()