# -*- coding: utf-8 -*-
"""Eman Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjpvY14qubKGsRQ9IDfqmtEAlPFEH_hi
"""

# ─────────────────────────────────────────────
# STEP 1 — Import Libraries
# ─────────────────────────────────────────────
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau
import torchvision
import torchvision.transforms as transforms
import torchvision.models as models
import numpy as np
import matplotlib.pyplot as plt
import time
import copy
import os

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ─────────────────────────────────────────────
# STEP 2 — Load and Preprocess CIFAR-10
# ─────────────────────────────────────────────

# ImageNet statistics for normalization (required for pretrained models)
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

# Standard transforms (resize 32x32 → 224x224 for VGG/ResNet)
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),          # Data augmentation
    transforms.RandomCrop(224, padding=8),      # Data augmentation
    transforms.ColorJitter(brightness=0.2,
                           contrast=0.2,
                           saturation=0.2),     # Data augmentation
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

# Load CIFAR-10
print("Downloading CIFAR-10 dataset...")
train_dataset = torchvision.datasets.CIFAR10(
    root='./data', train=True, download=True, transform=train_transform
)
test_dataset = torchvision.datasets.CIFAR10(
    root='./data', train=False, download=True, transform=test_transform
)

# Use a subset for faster experimentation (remove slicing to use full dataset)
SUBSET = 5000   # Use 5000 training, 1000 test for speed; set to None for full
if SUBSET:
    train_dataset = torch.utils.data.Subset(train_dataset, range(SUBSET))
    test_dataset  = torch.utils.data.Subset(test_dataset,  range(1000))

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True,  num_workers=0)
test_loader  = DataLoader(test_dataset,  batch_size=32, shuffle=False, num_workers=0)

CLASSES = ['airplane','automobile','bird','cat','deer',
           'dog','frog','horse','ship','truck']
NUM_CLASSES = 10

print(f"Training samples : {len(train_dataset)}")
print(f"Test samples     : {len(test_dataset)}")


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def train_model(model, train_loader, test_loader,
                criterion, optimizer, scheduler=None,
                num_epochs=10, patience=5, model_name="model"):
    """
    Generic training loop with:
      - Early stopping (patience)
      - Learning-rate scheduling
      - Best-model checkpointing
    Returns history dict with train/val loss and accuracy.
    """
    history = {"train_loss": [], "train_acc": [],
               "val_loss":   [], "val_acc":   []}

    best_val_acc = 0.0
    best_weights = copy.deepcopy(model.state_dict())
    epochs_no_improve = 0
    start = time.time()

    for epoch in range(num_epochs):
        # ── Train phase ──────────────────────────────
        model.train()
        running_loss, correct, total = 0.0, 0, 0

        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            _, predicted = outputs.max(1)
            correct += predicted.eq(labels).sum().item()
            total   += labels.size(0)

        train_loss = running_loss / total
        train_acc  = correct / total

        # ── Validation phase ─────────────────────────
        model.eval()
        val_loss, val_correct, val_total = 0.0, 0, 0
        with torch.no_grad():
            for inputs, labels in test_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                val_loss    += loss.item() * inputs.size(0)
                _, predicted = outputs.max(1)
                val_correct += predicted.eq(labels).sum().item()
                val_total   += labels.size(0)

        val_loss /= val_total
        val_acc   = val_correct / val_total

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        if scheduler:
            if isinstance(scheduler, ReduceLROnPlateau):
                scheduler.step(val_loss)
            else:
                scheduler.step()

        print(f"[{model_name}] Epoch {epoch+1:02d}/{num_epochs} | "
              f"Train Loss: {train_loss:.4f} Acc: {train_acc:.4f} | "
              f"Val Loss: {val_loss:.4f} Acc: {val_acc:.4f}")

        # Early stopping & best-model checkpoint
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_weights = copy.deepcopy(model.state_dict())
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1
            if epochs_no_improve >= patience:
                print(f"  ↳ Early stopping triggered at epoch {epoch+1}")
                break

    elapsed = time.time() - start
    print(f"\n{model_name} — Best Val Acc: {best_val_acc:.4f} | "
          f"Time: {elapsed/60:.1f} min\n")

    model.load_state_dict(best_weights)   # Restore best weights
    return history, best_val_acc


def evaluate_model(model, test_loader, model_name="model"):
    """Evaluate a model and return accuracy."""
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, predicted = outputs.max(1)
            correct += predicted.eq(labels).sum().item()
            total   += labels.size(0)
    acc = correct / total
    print(f"{model_name} — Test Accuracy: {acc:.4f} ({acc*100:.2f}%)")
    return acc


def plot_history(histories, titles, save_path="results.png"):
    """Plot loss and accuracy curves for multiple models."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    colors = ['blue', 'red', 'green', 'purple', 'orange']
    for i, (hist, title) in enumerate(zip(histories, titles)):
        c = colors[i % len(colors)]
        axes[0].plot(hist["val_loss"], label=f"{title} Val", color=c)
        axes[1].plot(hist["val_acc"],  label=f"{title} Val", color=c)

    axes[0].set_title("Validation Loss")
    axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Loss")
    axes[0].legend(); axes[0].grid(True, alpha=0.3)

    axes[1].set_title("Validation Accuracy")
    axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Accuracy")
    axes[1].legend(); axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"Plot saved → {save_path}")
    plt.show()


# ─────────────────────────────────────────────
# STEP 3A — FEATURE EXTRACTION with VGG16
# ─────────────────────────────────────────────
print("=" * 60)
print("STEP 3A: Feature Extraction — VGG16")
print("=" * 60)

# Load pretrained VGG16
vgg16_fe = models.vgg16(weights=models.VGG16_Weights.IMAGENET1K_V1)

# Freeze ALL layers
for param in vgg16_fe.parameters():
    param.requires_grad = False

# Replace the final classifier layer
in_features = vgg16_fe.classifier[6].in_features   # 4096
vgg16_fe.classifier[6] = nn.Sequential(
    nn.Dropout(0.5),
    nn.Linear(in_features, NUM_CLASSES)
)
vgg16_fe = vgg16_fe.to(device)

# Only the new layer's parameters are updated
optimizer_vgg_fe = optim.Adam(
    vgg16_fe.classifier[6].parameters(), lr=1e-3
)
criterion = nn.CrossEntropyLoss()

print("Trainable parameters (VGG16 Feature Extraction):",
      sum(p.numel() for p in vgg16_fe.parameters() if p.requires_grad))

history_vgg_fe, acc_vgg_fe = train_model(
    vgg16_fe, train_loader, test_loader,
    criterion, optimizer_vgg_fe,
    num_epochs=10, patience=5,
    model_name="VGG16-FE"
)


# ─────────────────────────────────────────────
# STEP 3B — FINE-TUNING with ResNet50
# ─────────────────────────────────────────────
print("=" * 60)
print("STEP 3B: Fine-Tuning — ResNet50 (Last 5 Layers)")
print("=" * 60)

resnet50_ft = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)

# Freeze all layers first
for param in resnet50_ft.parameters():
    param.requires_grad = False

# Replace final FC layer
resnet50_ft.fc = nn.Sequential(
    nn.Dropout(0.5),
    nn.Linear(resnet50_ft.fc.in_features, NUM_CLASSES)
)
resnet50_ft = resnet50_ft.to(device)

# Unfreeze last 5 layers
children = list(resnet50_ft.children())
for layer in children[-5:]:
    for param in layer.parameters():
        param.requires_grad = True

print("Trainable parameters (ResNet50 Fine-Tuning):",
      sum(p.numel() for p in resnet50_ft.parameters() if p.requires_grad))

# Two param groups: unfrozen backbone gets lower lr
optimizer_res_ft = optim.SGD([
    {"params": [p for n, p in resnet50_ft.named_parameters()
                if "fc" not in n and p.requires_grad], "lr": 1e-4},
    {"params": resnet50_ft.fc.parameters(), "lr": 1e-3},
], momentum=0.9, weight_decay=1e-4)

scheduler_res_ft = ReduceLROnPlateau(
    optimizer_res_ft, mode='min', factor=0.5, patience=3
)

history_res_ft, acc_res_ft = train_model(
    resnet50_ft, train_loader, test_loader,
    criterion, optimizer_res_ft, scheduler_res_ft,
    num_epochs=15, patience=5,
    model_name="ResNet50-FT"
)


# ─────────────────────────────────────────────
# STEP 4 — FEATURE EXTRACTION with ResNet50
#           (NEW TASK — compare vs VGG16-FE & custom)
# ─────────────────────────────────────────────
print("=" * 60)
print("TASK: Feature Extraction — ResNet50")
print("=" * 60)

resnet50_fe = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)

# Freeze everything
for param in resnet50_fe.parameters():
    param.requires_grad = False

# Replace final FC
resnet50_fe.fc = nn.Sequential(
    nn.Dropout(0.5),
    nn.Linear(resnet50_fe.fc.in_features, NUM_CLASSES)
)
resnet50_fe = resnet50_fe.to(device)

optimizer_res_fe = optim.Adam(resnet50_fe.fc.parameters(), lr=1e-3)

print("Trainable parameters (ResNet50 Feature Extraction):",
      sum(p.numel() for p in resnet50_fe.parameters() if p.requires_grad))

history_res_fe, acc_res_fe = train_model(
    resnet50_fe, train_loader, test_loader,
    criterion, optimizer_res_fe,
    num_epochs=10, patience=5,
    model_name="ResNet50-FE"
)


# ─────────────────────────────────────────────
# TASK — FINE-TUNING with VGG16
# ─────────────────────────────────────────────
print("=" * 60)
print("TASK: Fine-Tuning — VGG16 (Last 5 Layers + Improvements)")
print("=" * 60)

vgg16_ft = models.vgg16(weights=models.VGG16_Weights.IMAGENET1K_V1)

# Freeze all first
for param in vgg16_ft.parameters():
    param.requires_grad = False

# Replace classifier
vgg16_ft.classifier = nn.Sequential(
    nn.Linear(512 * 7 * 7, 4096),
    nn.ReLU(inplace=True),
    nn.Dropout(0.5),                    # Prevent overfitting
    nn.Linear(4096, 1024),
    nn.ReLU(inplace=True),
    nn.Dropout(0.4),                    # Prevent overfitting
    nn.Linear(1024, NUM_CLASSES)
)
vgg16_ft = vgg16_ft.to(device)

# Unfreeze last 5 feature layers
feature_children = list(vgg16_ft.features.children())
for layer in feature_children[-5:]:
    for param in layer.parameters():
        param.requires_grad = True

print("Trainable parameters (VGG16 Fine-Tuning):",
      sum(p.numel() for p in vgg16_ft.parameters() if p.requires_grad))

# Differential learning rates
optimizer_vgg_ft = optim.SGD([
    {"params": [p for n, p in vgg16_ft.named_parameters()
                if "classifier" not in n and p.requires_grad], "lr": 5e-5},
    {"params": vgg16_ft.classifier.parameters(), "lr": 1e-3},
], momentum=0.9, weight_decay=1e-4, nesterov=True)

scheduler_vgg_ft = ReduceLROnPlateau(
    optimizer_vgg_ft, mode='min', factor=0.3, patience=3
)

history_vgg_ft, acc_vgg_ft = train_model(
    vgg16_ft, train_loader, test_loader,
    criterion, optimizer_vgg_ft, scheduler_vgg_ft,
    num_epochs=20, patience=6,
    model_name="VGG16-FT"
)


# ─────────────────────────────────────────────
# TASK — CUSTOM CNN BASELINE (for comparison)
# ─────────────────────────────────────────────
print("=" * 60)
print("TASK: Custom CNN Baseline")
print("=" * 60)

class CustomCNN(nn.Module):
    """A simple 3-block CNN trained from scratch for comparison."""
    def __init__(self, num_classes=10):
        super().__init__()
        self.features = nn.Sequential(
            # Block 1
            nn.Conv2d(3, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(inplace=True),
            nn.Conv2d(32, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2), nn.Dropout2d(0.25),
            # Block 2
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(inplace=True),
            nn.Conv2d(64, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2), nn.Dropout2d(0.25),
            # Block 3
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(inplace=True),
            nn.Conv2d(128, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2), nn.Dropout2d(0.25),
        )
        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d((4, 4)),
            nn.Flatten(),
            nn.Linear(128 * 4 * 4, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x


custom_cnn = CustomCNN(NUM_CLASSES).to(device)

optimizer_custom = optim.Adam(custom_cnn.parameters(), lr=1e-3,
                              weight_decay=1e-4)
scheduler_custom = ReduceLROnPlateau(
    optimizer_custom, mode='min', factor=0.5, patience=3
)

print("Trainable parameters (Custom CNN):",
      sum(p.numel() for p in custom_cnn.parameters() if p.requires_grad))

history_custom, acc_custom = train_model(
    custom_cnn, train_loader, test_loader,
    criterion, optimizer_custom, scheduler_custom,
    num_epochs=20, patience=6,
    model_name="CustomCNN"
)


# ─────────────────────────────────────────────
# STEP 4 & 5 — EVALUATE AND COMPARE ALL MODELS
# ─────────────────────────────────────────────
print("=" * 60)
print("STEP 4 & 5: Final Evaluation & Comparison")
print("=" * 60)

results = {
    "VGG16 Feature Extraction":    evaluate_model(vgg16_fe,     test_loader, "VGG16-FE"),
    "ResNet50 Feature Extraction":  evaluate_model(resnet50_fe,  test_loader, "ResNet50-FE"),
    "ResNet50 Fine-Tuning":         evaluate_model(resnet50_ft,  test_loader, "ResNet50-FT"),
    "VGG16 Fine-Tuning":            evaluate_model(vgg16_ft,     test_loader, "VGG16-FT"),
    "Custom CNN (Baseline)":        evaluate_model(custom_cnn,   test_loader, "CustomCNN"),
}

# ─── Summary Table ───────────────────────────
print("\n" + "─" * 55)
print(f"{'Model':<35} {'Test Accuracy':>12} {'%':>6}")
print("─" * 55)
for name, acc in sorted(results.items(), key=lambda x: -x[1]):
    print(f"{name:<35} {acc:>12.4f} {acc*100:>5.2f}%")
print("─" * 55)

# ─── Plot All Curves ─────────────────────────
plot_history(
    [history_vgg_fe, history_res_fe, history_res_ft,
     history_vgg_ft, history_custom],
    ["VGG16-FE", "ResNet50-FE", "ResNet50-FT",
     "VGG16-FT", "CustomCNN"],
    save_path="training_curves.png"
)

# ─── Bar chart of final accuracies ───────────
plt.figure(figsize=(10, 5))
names = list(results.keys())
accs  = [results[n] * 100 for n in names]
bars  = plt.bar(names, accs,
                color=['steelblue','cornflowerblue','tomato','salmon','seagreen'])
plt.xticks(rotation=20, ha='right', fontsize=9)
plt.ylabel("Test Accuracy (%)")
plt.title("Model Comparison — CIFAR-10 Test Accuracy")
plt.ylim(0, 100)
for bar, acc in zip(bars, accs):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
             f"{acc:.1f}%", ha='center', va='bottom', fontsize=9)
plt.tight_layout()
plt.savefig("model_comparison.png", dpi=150, bbox_inches='tight')
print("Bar chart saved → model_comparison.png")
plt.show()


# ─────────────────────────────────────────────
# FINE-TUNING IMPROVEMENTS — SUMMARY
# ─────────────────────────────────────────────
print("""
╔══════════════════════════════════════════════════════════╗
║         FINE-TUNING IMPROVEMENT STRATEGIES USED         ║
╠══════════════════════════════════════════════════════════╣
║ 1. Differential Learning Rates                          ║
║    - Backbone unfrozen layers : lr = 5e-5 / 1e-4        ║
║    - New classifier head      : lr = 1e-3               ║
║                                                          ║
║ 2. Dropout Regularization (Prevent Overfitting)         ║
║    - Dropout(0.5) after first FC                        ║
║    - Dropout(0.4) after second FC                       ║
║                                                          ║
║ 3. Early Stopping (patience=6)                          ║
║    - Restores best-validation-accuracy weights          ║
║                                                          ║
║ 4. ReduceLROnPlateau Scheduler                          ║
║    - factor=0.3 / 0.5, patience=3                       ║
║    - Reduces LR when val_loss plateaus                  ║
║                                                          ║
║ 5. ImageNet Normalization + Data Augmentation           ║
║    - RandomHorizontalFlip, RandomCrop                   ║
║    - ColorJitter (brightness, contrast, saturation)     ║
║                                                          ║
║ 6. More Unfrozen Layers                                 ║
║    - Last 5 feature/conv layers unfrozen               ║
║    - Larger part of backbone adapts to CIFAR-10         ║
║                                                          ║
║ 7. SGD + Nesterov Momentum (VGG16-FT)                  ║
║    - Better generalization than plain Adam              ║
║    - weight_decay=1e-4 as L2 regularization            ║
╚══════════════════════════════════════════════════════════╝
""")